// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.000000.0
#pragma once
#include "winrt/impl/Windows.Foundation.Collections.0.h"
namespace winrt::Windows::Foundation::Collections
{
    template <typename T>
    struct WINRT_EBO IIterable :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IIterable<T>>
    {
        IIterable(std::nullptr_t = nullptr) noexcept {}
        IIterable(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename T>
    struct WINRT_EBO IIterator :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IIterator<T>>
    {
        IIterator(std::nullptr_t = nullptr) noexcept {}
        IIterator(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}

        using iterator_category = std::input_iterator_tag;
        using value_type = T;
        using difference_type = ptrdiff_t;
        using pointer = T*;
        using reference = T&;
    };
    template <typename K, typename V>
    struct WINRT_EBO IKeyValuePair :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IKeyValuePair<K, V>>
    {
        IKeyValuePair(std::nullptr_t = nullptr) noexcept {}
        IKeyValuePair(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename K>
    struct WINRT_EBO IMapChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IMapChangedEventArgs<K>>
    {
        IMapChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMapChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename K, typename V>
    struct WINRT_EBO IMapView :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IMapView<K, V>>,
        impl::require<Windows::Foundation::Collections::IMapView<K, V>, Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<K, V>>>
    {
        IMapView(std::nullptr_t = nullptr) noexcept {}
        IMapView(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename K, typename V>
    struct WINRT_EBO IObservableMap :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IObservableMap<K, V>>,
        impl::require<Windows::Foundation::Collections::IObservableMap<K, V>, Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<K, V>>, Windows::Foundation::Collections::IMap<K, V>>
    {
        IObservableMap(std::nullptr_t = nullptr) noexcept {}
        IObservableMap(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename T>
    struct WINRT_EBO IObservableVector :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IObservableVector<T>>,
        impl::require<Windows::Foundation::Collections::IObservableVector<T>, Windows::Foundation::Collections::IIterable<T>, Windows::Foundation::Collections::IVector<T>>
    {
        IObservableVector(std::nullptr_t = nullptr) noexcept {}
        IObservableVector(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IPropertySet :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPropertySet>,
        impl::require<Windows::Foundation::Collections::IPropertySet, Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<hstring, Windows::Foundation::IInspectable>>, Windows::Foundation::Collections::IMap<hstring, Windows::Foundation::IInspectable>, Windows::Foundation::Collections::IObservableMap<hstring, Windows::Foundation::IInspectable>>
    {
        IPropertySet(std::nullptr_t = nullptr) noexcept {}
        IPropertySet(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IVectorChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVectorChangedEventArgs>
    {
        IVectorChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IVectorChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename T>
    struct WINRT_EBO IVectorView :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IVectorView<T>>,
        impl::require<Windows::Foundation::Collections::IVectorView<T>, Windows::Foundation::Collections::IIterable<T>>
    {
        IVectorView(std::nullptr_t = nullptr) noexcept {}
        IVectorView(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    template <typename T>
    struct WINRT_EBO IVector :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::Collections::IVector<T>>,
        impl::require<Windows::Foundation::Collections::IVector<T>, Windows::Foundation::Collections::IIterable<T>>
    {
        IVector(std::nullptr_t = nullptr) noexcept {}
        IVector(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
