# WARNING: Please don't edit this file. It was generated by Python/WinRT

from pyrt import _import_ns
import typing
import enum

__ns__ = _import_ns("Windows.Devices.Geolocation")

try:
    import pyrt.windows.foundation
except:
    pass

try:
    import pyrt.windows.foundation.collections
except:
    pass

class AltitudeReferenceSystem(enum.IntEnum):
    Unspecified = 0
    Terrain = 1
    Ellipsoid = 2
    Geoid = 3
    Surface = 4

class GeolocationAccessStatus(enum.IntEnum):
    Unspecified = 0
    Allowed = 1
    Denied = 2

class GeoshapeType(enum.IntEnum):
    Geopoint = 0
    Geocircle = 1
    Geopath = 2
    GeoboundingBox = 3

class PositionAccuracy(enum.IntEnum):
    Default = 0
    High = 1

class PositionSource(enum.IntEnum):
    Cellular = 0
    Satellite = 1
    WiFi = 2
    IPAddress = 3
    Unknown = 4
    Default = 5
    Obfuscated = 6

class PositionStatus(enum.IntEnum):
    Ready = 0
    Initializing = 1
    NoData = 2
    Disabled = 3
    NotInitialized = 4
    NotAvailable = 5

class VisitMonitoringScope(enum.IntEnum):
    Venue = 0
    City = 1

class VisitStateChange(enum.IntEnum):
    TrackingLost = 0
    Arrived = 1
    Departed = 2
    OtherMovement = 3

CivicAddress = __ns__.CivicAddress
GeoboundingBox = __ns__.GeoboundingBox
Geocircle = __ns__.Geocircle
Geocoordinate = __ns__.Geocoordinate
GeocoordinateSatelliteData = __ns__.GeocoordinateSatelliteData
Geolocator = __ns__.Geolocator
Geopath = __ns__.Geopath
Geopoint = __ns__.Geopoint
Geoposition = __ns__.Geoposition
Geovisit = __ns__.Geovisit
GeovisitMonitor = __ns__.GeovisitMonitor
GeovisitStateChangedEventArgs = __ns__.GeovisitStateChangedEventArgs
GeovisitTriggerDetails = __ns__.GeovisitTriggerDetails
PositionChangedEventArgs = __ns__.PositionChangedEventArgs
StatusChangedEventArgs = __ns__.StatusChangedEventArgs
VenueData = __ns__.VenueData
IGeoshape = __ns__.IGeoshape
BasicGeoposition = __ns__.BasicGeoposition
