// This file was generated by CMake

#pragma once

namespace pywinrt::strings {

extern char const custom_struct_convert[972];

extern char const enter_function[99];

extern char const module_methods[3976];

extern char const ns_module_def[295];

extern char const package_init[480];

extern char const pybase[32005];

extern char const setup[306];

}

