resources:
  containers:
  - container: build_container
    image: devhawk/xlang-build

pool:
  vmImage: 'ubuntu-16.04'

container: build_container

steps:
- script: cmake ./src -B_build -GNinja -DCMAKE_CXX_COMPILER=clang++
  displayName: 'CMake'
- script: ninja -C _build -v 
  displayName: 'Ninja'
  