resources:
  containers:
  - container: my_container
    image: devhawk/xlang-build

pool:
  vmImage: 'ubuntu-16.04'

container: my_container

steps:
- script: cmake -B $(Build.BinariesDirectory) -GNinja -DCMAKE_CXX_COMPILER=clang++
  workingDirectory: src
  displayName: 'CMake'
- script: ninja -C $(Build.BinariesDirectory) -v 
  workingDirectory: src
  displayName: 'Ninja'
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'



