FROM ubuntu:18.04

RUN apt-get update

RUN apt-get install apt-utils -y

RUN apt-get install -y \
    git \
    nodejs \
    zip \
    clang \
    cmake \
    ninja-build \
    libc++-dev \
    libc++abi-dev