resources:
  containers:
  - container: build_container
    image:   msftxlang.azurecr.io/xlang-windows-build
    endpoint: msftxlang_acr

pool:
  vmImage: 'win1803'

container: build_container

steps:
- script: systeminfo
  displayName: 'SystemInfo'
