resources:
  containers:
  - container: build_container
    image:  microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803

pool:
  vmImage: 'win1803'

container: build_container

steps:
- script: systeminfo
  displayName: 'SystemInfo'
