pool:
  vmImage: 'windows-2019'

steps:
- script: C:\BuildTools\Common7\Tools\VsDevCmd.bat && cmake ./src -B_build\Windows\x86\Release -GNinja -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX=install && ninja -C _build\Windows\x86\Release install -v
  displayName: 'build'
- script: .\install\test\library\test_library.exe -r junit -o TEST-test_library.xml
  displayName: 'test_library'
  continueOnError: true
- script: .\install\test\platform\test_platform.exe -r junit -o TEST-test_platform.xml
  displayName: 'test_platform'
  continueOnError: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
