resources:
  containers:
  - container: build_container
    image:  microsoft/windowsservercore:1803

pool:
  vmImage: 'win1803'

container: build_container

steps:
- script: systeminfo
  displayName: 'SystemInfo'
