pool:
  vmImage: 'windows-2019'

# TODO: reuse src\package\pywinrt\projection\AzurePipelinesTemplates\task-vsdevcmd.yml instead of copying the next two 
#       steps from that YML file into this pipeline. 

steps:
- script: |
    @echo off
    
    set vswherepath="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
    for /f "usebackq delims=" %%i in (`%vswherepath% -latest -property installationPath`) do (
      set vslatest="%%i"
      if exist "%%i\Common7\Tools\vsdevcmd.bat" (
        set vsdevcmd="%%i\Common7\Tools\vsdevcmd.bat"
      )
    )
    
    @echo vslatest %vslatest%
    @echo vsdevcmd %vsdevcmd%
    
    @echo ##vso[task.setvariable variable=vslatest]%vslatest%
    @echo ##vso[task.setvariable variable=vsdevcmd]%vsdevcmd%
  displayName: 'locate vsdevcmd via vswhere'
- task: BatchScript@1
  displayName: 'Configure environment with VSDevCmd'
  inputs:
    filename: $(vsdevcmd)
    modifyEnvironment: true

- task: CMake@1
  displayName: 'Generate xlang build files via cmake'
  inputs:
    cwd: '.'
    cmakeArgs: -S src -B_build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX=install
- task: CMake@1
  displayName: 'build xlang'
  inputs:
    cwd: '.'
    cmakeArgs: --build .\_build -- -v install
- script: .\install\test\library\test_library.exe -r junit -o TEST-test_library.xml
  displayName: 'test_library'
  continueOnError: true
- script: .\install\test\platform\test_platform.exe -r junit -o TEST-test_platform.xml
  displayName: 'test_platform'
  continueOnError: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
