resources:
  containers:
  - container: build_container
    image: msftxlang.azurecr.io/xlang-windows-build
    endpoint: msftxlang_acr

pool:
  vmImage: 'win1803'

container: build_container

steps:
- script: cmake ./src -B_build -GNinja
  displayName: 'CMake'
- script: ninja -C _build -v 
  displayName: 'Ninja'
