# WARNING: Please don't edit this file. It was generated by Python/WinRT

from pyrt import _import_ns
import typing
import enum

__ns__ = _import_ns("Windows.Foundation.Collections")

try:
    import pyrt.windows.foundation
except:
    pass

class CollectionChange(enum.IntEnum):
    Reset = 0
    ItemInserted = 1
    ItemRemoved = 2
    ItemChanged = 3

PropertySet = __ns__.PropertySet
StringMap = __ns__.StringMap
ValueSet = __ns__.ValueSet
IIterable = __ns__.IIterable
IIterator = __ns__.IIterator
IKeyValuePair = __ns__.IKeyValuePair
IMapChangedEventArgs = __ns__.IMapChangedEventArgs
IMapView = __ns__.IMapView
IMap = __ns__.IMap
IObservableMap = __ns__.IObservableMap
IObservableVector = __ns__.IObservableVector
IPropertySet = __ns__.IPropertySet
IVectorChangedEventArgs = __ns__.IVectorChangedEventArgs
IVectorView = __ns__.IVectorView
IVector = __ns__.IVector
