// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.000000.0
#pragma once
#include "winrt/impl/Windows.Foundation.Numerics.2.h"
#include "winrt/Windows.Foundation.h"
namespace winrt::impl
{
}
namespace winrt::Windows::Foundation::Numerics
{
}
namespace std
{
}
