namespace N
{
    delegate void StringListEvent(Int32 sender);
    interface I1
    {
        event StringListEvent Changed;
        void m0();
        Int32 property1;
    }

    runtimeclass C1 requires I1
    {
    }
}