# WARNING: Please don't edit this file. It was generated by Python/WinRT

from pyrt import _import_ns
import typing

__ns__ = _import_ns("Windows.Foundation.Numerics")

Matrix3x2 = __ns__.Matrix3x2
Matrix4x4 = __ns__.Matrix4x4
Plane = __ns__.Plane
Quaternion = __ns__.Quaternion
Rational = __ns__.Rational
Vector2 = __ns__.Vector2
Vector3 = __ns__.Vector3
Vector4 = __ns__.Vector4
