namespace Sample
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 MyProperty;

		event Windows.Foundation.TypedEventHandler<Class, IInspectable> MyPropertyChanged;
    }
}
