// WARNING: Please don't edit this file. It was generated by Python/WinRT

#include "py.Windows.Foundation.Collections.h"

// ----- PropertySet class --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::PropertySet>::python_type;


PyObject* PropertySet_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::PropertySet instance{  };
            return py::wrap(instance, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static void PropertySet_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* PropertySet__from(PyObject* /*unused*/, PyObject* arg)
{
    try
    {
        auto instance = py::converter<winrt::Windows::Foundation::IInspectable>::convert_to(arg);
        return py::converter<winrt::Windows::Foundation::Collections::PropertySet>::convert(instance.as<winrt::Windows::Foundation::Collections::PropertySet>());
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyObject* PropertySet_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::Windows::Foundation::IInspectable>> return_value = self->obj.First();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::Windows::Foundation::IInspectable> return_value = self->obj.GetView();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::Windows::Foundation::IInspectable>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::Windows::Foundation::IInspectable return_value = self->obj.Lookup(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_add_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::Windows::Foundation::Collections::MapChangedEventHandler<winrt::hstring, winrt::Windows::Foundation::IInspectable>>::convert_to(args);

            winrt::event_token return_value = self->obj.MapChanged(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* PropertySet_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    if (args != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "arguments not supported for get methods");
        return nullptr;
    }
        try
        {
            uint32_t return_value = self->obj.Size();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* PropertySet_remove_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::event_token>::convert_to(args);

            self->obj.MapChanged(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyMethodDef PropertySet_methods[] = {
    { "Clear", (PyCFunction)PropertySet_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)PropertySet_First, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)PropertySet_GetView, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)PropertySet_HasKey, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)PropertySet_Insert, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)PropertySet_Lookup, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)PropertySet_Remove, METH_VARARGS, nullptr },
    { "add_MapChanged", (PyCFunction)PropertySet_add_MapChanged, METH_O, nullptr },
    { "get_Size", (PyCFunction)PropertySet_get_Size, METH_NOARGS, nullptr },
    { "remove_MapChanged", (PyCFunction)PropertySet_remove_MapChanged, METH_O, nullptr },
    { "_from", (PyCFunction)PropertySet__from, METH_O | METH_STATIC, nullptr },
    { nullptr }
};

static PyType_Slot PropertySet_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, PropertySet_dealloc },
    { Py_tp_new, PropertySet_new },
    { Py_tp_methods, PropertySet_methods },
    { 0, nullptr },
};

static PyType_Spec PropertySet_Type_spec =
{
    "PropertySet",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>),
    0,
    Py_TPFLAGS_DEFAULT,
    PropertySet_Type_slots
};

// ----- StringMap class --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::StringMap>::python_type;


PyObject* StringMap_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::StringMap instance{  };
            return py::wrap(instance, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static void StringMap_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* StringMap__from(PyObject* /*unused*/, PyObject* arg)
{
    try
    {
        auto instance = py::converter<winrt::Windows::Foundation::IInspectable>::convert_to(arg);
        return py::converter<winrt::Windows::Foundation::Collections::StringMap>::convert(instance.as<winrt::Windows::Foundation::Collections::StringMap>());
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyObject* StringMap_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::hstring>> return_value = self->obj.First();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::hstring> return_value = self->obj.GetView();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::hstring>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::hstring return_value = self->obj.Lookup(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_add_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::Windows::Foundation::Collections::MapChangedEventHandler<winrt::hstring, winrt::hstring>>::convert_to(args);

            winrt::event_token return_value = self->obj.MapChanged(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* StringMap_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    if (args != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "arguments not supported for get methods");
        return nullptr;
    }
        try
        {
            uint32_t return_value = self->obj.Size();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* StringMap_remove_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::event_token>::convert_to(args);

            self->obj.MapChanged(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyMethodDef StringMap_methods[] = {
    { "Clear", (PyCFunction)StringMap_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)StringMap_First, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)StringMap_GetView, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)StringMap_HasKey, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)StringMap_Insert, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)StringMap_Lookup, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)StringMap_Remove, METH_VARARGS, nullptr },
    { "add_MapChanged", (PyCFunction)StringMap_add_MapChanged, METH_O, nullptr },
    { "get_Size", (PyCFunction)StringMap_get_Size, METH_NOARGS, nullptr },
    { "remove_MapChanged", (PyCFunction)StringMap_remove_MapChanged, METH_O, nullptr },
    { "_from", (PyCFunction)StringMap__from, METH_O | METH_STATIC, nullptr },
    { nullptr }
};

static PyType_Slot StringMap_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, StringMap_dealloc },
    { Py_tp_new, StringMap_new },
    { Py_tp_methods, StringMap_methods },
    { 0, nullptr },
};

static PyType_Spec StringMap_Type_spec =
{
    "StringMap",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>),
    0,
    Py_TPFLAGS_DEFAULT,
    StringMap_Type_slots
};

// ----- ValueSet class --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::ValueSet>::python_type;


PyObject* ValueSet_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::ValueSet instance{  };
            return py::wrap(instance, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static void ValueSet_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* ValueSet__from(PyObject* /*unused*/, PyObject* arg)
{
    try
    {
        auto instance = py::converter<winrt::Windows::Foundation::IInspectable>::convert_to(arg);
        return py::converter<winrt::Windows::Foundation::Collections::ValueSet>::convert(instance.as<winrt::Windows::Foundation::Collections::ValueSet>());
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyObject* ValueSet_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::Windows::Foundation::IInspectable>> return_value = self->obj.First();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::Windows::Foundation::IInspectable> return_value = self->obj.GetView();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::Windows::Foundation::IInspectable>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::Windows::Foundation::IInspectable return_value = self->obj.Lookup(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_add_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::Windows::Foundation::Collections::MapChangedEventHandler<winrt::hstring, winrt::Windows::Foundation::IInspectable>>::convert_to(args);

            winrt::event_token return_value = self->obj.MapChanged(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* ValueSet_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    if (args != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "arguments not supported for get methods");
        return nullptr;
    }
        try
        {
            uint32_t return_value = self->obj.Size();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* ValueSet_remove_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::event_token>::convert_to(args);

            self->obj.MapChanged(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyMethodDef ValueSet_methods[] = {
    { "Clear", (PyCFunction)ValueSet_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)ValueSet_First, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)ValueSet_GetView, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)ValueSet_HasKey, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)ValueSet_Insert, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)ValueSet_Lookup, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)ValueSet_Remove, METH_VARARGS, nullptr },
    { "add_MapChanged", (PyCFunction)ValueSet_add_MapChanged, METH_O, nullptr },
    { "get_Size", (PyCFunction)ValueSet_get_Size, METH_NOARGS, nullptr },
    { "remove_MapChanged", (PyCFunction)ValueSet_remove_MapChanged, METH_O, nullptr },
    { "_from", (PyCFunction)ValueSet__from, METH_O | METH_STATIC, nullptr },
    { nullptr }
};

static PyType_Slot ValueSet_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, ValueSet_dealloc },
    { Py_tp_new, ValueSet_new },
    { Py_tp_methods, ValueSet_methods },
    { 0, nullptr },
};

static PyType_Spec ValueSet_Type_spec =
{
    "ValueSet",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>),
    0,
    Py_TPFLAGS_DEFAULT,
    ValueSet_Type_slots
};

// ----- IIterable interface --------------------
PyTypeObject* py::winrt_type<pyIIterable>::python_type;


PyObject* IIterable_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IIterable interface is not activatable");
    return nullptr;
}

static void IIterable_dealloc(py::winrt_pinterface_wrapper<pyIIterable>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IIterable_First(py::winrt_pinterface_wrapper<pyIIterable>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyMethodDef IIterable_methods[] = {
    { "First", (PyCFunction)IIterable_First, METH_VARARGS, nullptr },
    { nullptr }
};

static PyType_Slot IIterable_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IIterable_dealloc },
    { Py_tp_new, IIterable_new },
    { Py_tp_methods, IIterable_methods },
    { 0, nullptr },
};

static PyType_Spec IIterable_Type_spec =
{
    "IIterable",
    sizeof(py::winrt_pinterface_wrapper<pyIIterable>),
    0,
    Py_TPFLAGS_DEFAULT,
    IIterable_Type_slots
};

// ----- IIterator interface --------------------
PyTypeObject* py::winrt_type<pyIIterator>::python_type;


PyObject* IIterator_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IIterator interface is not activatable");
    return nullptr;
}

static void IIterator_dealloc(py::winrt_pinterface_wrapper<pyIIterator>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IIterator_GetMany(py::winrt_pinterface_wrapper<pyIIterator>* self, PyObject* args)
{ 
    return self->obj->GetMany(args);
}

static PyObject* IIterator_MoveNext(py::winrt_pinterface_wrapper<pyIIterator>* self, PyObject* args)
{ 
    return self->obj->MoveNext(args);
}

static PyObject* IIterator_get_Current(py::winrt_pinterface_wrapper<pyIIterator>* self, PyObject* args)
{ 
    return self->obj->get_Current(args);
}

static PyObject* IIterator_get_HasCurrent(py::winrt_pinterface_wrapper<pyIIterator>* self, PyObject* args)
{ 
    return self->obj->get_HasCurrent(args);
}

static PyMethodDef IIterator_methods[] = {
    { "GetMany", (PyCFunction)IIterator_GetMany, METH_VARARGS, nullptr },
    { "MoveNext", (PyCFunction)IIterator_MoveNext, METH_VARARGS, nullptr },
    { "get_Current", (PyCFunction)IIterator_get_Current, METH_NOARGS, nullptr },
    { "get_HasCurrent", (PyCFunction)IIterator_get_HasCurrent, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IIterator_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IIterator_dealloc },
    { Py_tp_new, IIterator_new },
    { Py_tp_methods, IIterator_methods },
    { 0, nullptr },
};

static PyType_Spec IIterator_Type_spec =
{
    "IIterator",
    sizeof(py::winrt_pinterface_wrapper<pyIIterator>),
    0,
    Py_TPFLAGS_DEFAULT,
    IIterator_Type_slots
};

// ----- IKeyValuePair interface --------------------
PyTypeObject* py::winrt_type<pyIKeyValuePair>::python_type;


PyObject* IKeyValuePair_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IKeyValuePair interface is not activatable");
    return nullptr;
}

static void IKeyValuePair_dealloc(py::winrt_pinterface_wrapper<pyIKeyValuePair>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IKeyValuePair_get_Key(py::winrt_pinterface_wrapper<pyIKeyValuePair>* self, PyObject* args)
{ 
    return self->obj->get_Key(args);
}

static PyObject* IKeyValuePair_get_Value(py::winrt_pinterface_wrapper<pyIKeyValuePair>* self, PyObject* args)
{ 
    return self->obj->get_Value(args);
}

static PyMethodDef IKeyValuePair_methods[] = {
    { "get_Key", (PyCFunction)IKeyValuePair_get_Key, METH_NOARGS, nullptr },
    { "get_Value", (PyCFunction)IKeyValuePair_get_Value, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IKeyValuePair_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IKeyValuePair_dealloc },
    { Py_tp_new, IKeyValuePair_new },
    { Py_tp_methods, IKeyValuePair_methods },
    { 0, nullptr },
};

static PyType_Spec IKeyValuePair_Type_spec =
{
    "IKeyValuePair",
    sizeof(py::winrt_pinterface_wrapper<pyIKeyValuePair>),
    0,
    Py_TPFLAGS_DEFAULT,
    IKeyValuePair_Type_slots
};

// ----- IMapChangedEventArgs interface --------------------
PyTypeObject* py::winrt_type<pyIMapChangedEventArgs>::python_type;


PyObject* IMapChangedEventArgs_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IMapChangedEventArgs interface is not activatable");
    return nullptr;
}

static void IMapChangedEventArgs_dealloc(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IMapChangedEventArgs_get_CollectionChange(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>* self, PyObject* args)
{ 
    return self->obj->get_CollectionChange(args);
}

static PyObject* IMapChangedEventArgs_get_Key(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>* self, PyObject* args)
{ 
    return self->obj->get_Key(args);
}

static PyMethodDef IMapChangedEventArgs_methods[] = {
    { "get_CollectionChange", (PyCFunction)IMapChangedEventArgs_get_CollectionChange, METH_NOARGS, nullptr },
    { "get_Key", (PyCFunction)IMapChangedEventArgs_get_Key, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IMapChangedEventArgs_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IMapChangedEventArgs_dealloc },
    { Py_tp_new, IMapChangedEventArgs_new },
    { Py_tp_methods, IMapChangedEventArgs_methods },
    { 0, nullptr },
};

static PyType_Spec IMapChangedEventArgs_Type_spec =
{
    "IMapChangedEventArgs",
    sizeof(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>),
    0,
    Py_TPFLAGS_DEFAULT,
    IMapChangedEventArgs_Type_slots
};

// ----- IMapView interface --------------------
PyTypeObject* py::winrt_type<pyIMapView>::python_type;


PyObject* IMapView_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IMapView interface is not activatable");
    return nullptr;
}

static void IMapView_dealloc(py::winrt_pinterface_wrapper<pyIMapView>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IMapView_First(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyObject* IMapView_HasKey(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{ 
    return self->obj->HasKey(args);
}

static PyObject* IMapView_Lookup(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{ 
    return self->obj->Lookup(args);
}

static PyObject* IMapView_Split(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{ 
    return self->obj->Split(args);
}

static PyObject* IMapView_get_Size(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{ 
    return self->obj->get_Size(args);
}

static PyMethodDef IMapView_methods[] = {
    { "First", (PyCFunction)IMapView_First, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)IMapView_HasKey, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)IMapView_Lookup, METH_VARARGS, nullptr },
    { "Split", (PyCFunction)IMapView_Split, METH_VARARGS, nullptr },
    { "get_Size", (PyCFunction)IMapView_get_Size, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IMapView_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IMapView_dealloc },
    { Py_tp_new, IMapView_new },
    { Py_tp_methods, IMapView_methods },
    { 0, nullptr },
};

static PyType_Spec IMapView_Type_spec =
{
    "IMapView",
    sizeof(py::winrt_pinterface_wrapper<pyIMapView>),
    0,
    Py_TPFLAGS_DEFAULT,
    IMapView_Type_slots
};

// ----- IMap interface --------------------
PyTypeObject* py::winrt_type<pyIMap>::python_type;


PyObject* IMap_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IMap interface is not activatable");
    return nullptr;
}

static void IMap_dealloc(py::winrt_pinterface_wrapper<pyIMap>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IMap_Clear(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->Clear(args);
}

static PyObject* IMap_First(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyObject* IMap_GetView(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->GetView(args);
}

static PyObject* IMap_HasKey(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->HasKey(args);
}

static PyObject* IMap_Insert(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->Insert(args);
}

static PyObject* IMap_Lookup(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->Lookup(args);
}

static PyObject* IMap_Remove(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->Remove(args);
}

static PyObject* IMap_get_Size(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{ 
    return self->obj->get_Size(args);
}

static PyMethodDef IMap_methods[] = {
    { "Clear", (PyCFunction)IMap_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)IMap_First, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IMap_GetView, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)IMap_HasKey, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)IMap_Insert, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)IMap_Lookup, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)IMap_Remove, METH_VARARGS, nullptr },
    { "get_Size", (PyCFunction)IMap_get_Size, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IMap_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IMap_dealloc },
    { Py_tp_new, IMap_new },
    { Py_tp_methods, IMap_methods },
    { 0, nullptr },
};

static PyType_Spec IMap_Type_spec =
{
    "IMap",
    sizeof(py::winrt_pinterface_wrapper<pyIMap>),
    0,
    Py_TPFLAGS_DEFAULT,
    IMap_Type_slots
};

// ----- IObservableMap interface --------------------
PyTypeObject* py::winrt_type<pyIObservableMap>::python_type;


PyObject* IObservableMap_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IObservableMap interface is not activatable");
    return nullptr;
}

static void IObservableMap_dealloc(py::winrt_pinterface_wrapper<pyIObservableMap>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IObservableMap_Clear(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->Clear(args);
}

static PyObject* IObservableMap_First(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyObject* IObservableMap_GetView(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->GetView(args);
}

static PyObject* IObservableMap_HasKey(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->HasKey(args);
}

static PyObject* IObservableMap_Insert(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->Insert(args);
}

static PyObject* IObservableMap_Lookup(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->Lookup(args);
}

static PyObject* IObservableMap_Remove(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->Remove(args);
}

static PyObject* IObservableMap_add_MapChanged(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->add_MapChanged(args);
}

static PyObject* IObservableMap_get_Size(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->get_Size(args);
}

static PyObject* IObservableMap_remove_MapChanged(py::winrt_pinterface_wrapper<pyIObservableMap>* self, PyObject* args)
{ 
    return self->obj->remove_MapChanged(args);
}

static PyMethodDef IObservableMap_methods[] = {
    { "Clear", (PyCFunction)IObservableMap_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)IObservableMap_First, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IObservableMap_GetView, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)IObservableMap_HasKey, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)IObservableMap_Insert, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)IObservableMap_Lookup, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)IObservableMap_Remove, METH_VARARGS, nullptr },
    { "add_MapChanged", (PyCFunction)IObservableMap_add_MapChanged, METH_O, nullptr },
    { "get_Size", (PyCFunction)IObservableMap_get_Size, METH_NOARGS, nullptr },
    { "remove_MapChanged", (PyCFunction)IObservableMap_remove_MapChanged, METH_O, nullptr },
    { nullptr }
};

static PyType_Slot IObservableMap_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IObservableMap_dealloc },
    { Py_tp_new, IObservableMap_new },
    { Py_tp_methods, IObservableMap_methods },
    { 0, nullptr },
};

static PyType_Spec IObservableMap_Type_spec =
{
    "IObservableMap",
    sizeof(py::winrt_pinterface_wrapper<pyIObservableMap>),
    0,
    Py_TPFLAGS_DEFAULT,
    IObservableMap_Type_slots
};

// ----- IObservableVector interface --------------------
PyTypeObject* py::winrt_type<pyIObservableVector>::python_type;


PyObject* IObservableVector_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IObservableVector interface is not activatable");
    return nullptr;
}

static void IObservableVector_dealloc(py::winrt_pinterface_wrapper<pyIObservableVector>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IObservableVector_Append(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->Append(args);
}

static PyObject* IObservableVector_Clear(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->Clear(args);
}

static PyObject* IObservableVector_First(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyObject* IObservableVector_GetAt(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->GetAt(args);
}

static PyObject* IObservableVector_GetMany(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->GetMany(args);
}

static PyObject* IObservableVector_GetView(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->GetView(args);
}

static PyObject* IObservableVector_IndexOf(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->IndexOf(args);
}

static PyObject* IObservableVector_InsertAt(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->InsertAt(args);
}

static PyObject* IObservableVector_RemoveAt(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->RemoveAt(args);
}

static PyObject* IObservableVector_RemoveAtEnd(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->RemoveAtEnd(args);
}

static PyObject* IObservableVector_ReplaceAll(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->ReplaceAll(args);
}

static PyObject* IObservableVector_SetAt(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->SetAt(args);
}

static PyObject* IObservableVector_add_VectorChanged(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->add_VectorChanged(args);
}

static PyObject* IObservableVector_get_Size(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->get_Size(args);
}

static PyObject* IObservableVector_remove_VectorChanged(py::winrt_pinterface_wrapper<pyIObservableVector>* self, PyObject* args)
{ 
    return self->obj->remove_VectorChanged(args);
}

static PyMethodDef IObservableVector_methods[] = {
    { "Append", (PyCFunction)IObservableVector_Append, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)IObservableVector_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)IObservableVector_First, METH_VARARGS, nullptr },
    { "GetAt", (PyCFunction)IObservableVector_GetAt, METH_VARARGS, nullptr },
    { "GetMany", (PyCFunction)IObservableVector_GetMany, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IObservableVector_GetView, METH_VARARGS, nullptr },
    { "IndexOf", (PyCFunction)IObservableVector_IndexOf, METH_VARARGS, nullptr },
    { "InsertAt", (PyCFunction)IObservableVector_InsertAt, METH_VARARGS, nullptr },
    { "RemoveAt", (PyCFunction)IObservableVector_RemoveAt, METH_VARARGS, nullptr },
    { "RemoveAtEnd", (PyCFunction)IObservableVector_RemoveAtEnd, METH_VARARGS, nullptr },
    { "ReplaceAll", (PyCFunction)IObservableVector_ReplaceAll, METH_VARARGS, nullptr },
    { "SetAt", (PyCFunction)IObservableVector_SetAt, METH_VARARGS, nullptr },
    { "add_VectorChanged", (PyCFunction)IObservableVector_add_VectorChanged, METH_O, nullptr },
    { "get_Size", (PyCFunction)IObservableVector_get_Size, METH_NOARGS, nullptr },
    { "remove_VectorChanged", (PyCFunction)IObservableVector_remove_VectorChanged, METH_O, nullptr },
    { nullptr }
};

static PyType_Slot IObservableVector_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IObservableVector_dealloc },
    { Py_tp_new, IObservableVector_new },
    { Py_tp_methods, IObservableVector_methods },
    { 0, nullptr },
};

static PyType_Spec IObservableVector_Type_spec =
{
    "IObservableVector",
    sizeof(py::winrt_pinterface_wrapper<pyIObservableVector>),
    0,
    Py_TPFLAGS_DEFAULT,
    IObservableVector_Type_slots
};

// ----- IPropertySet interface --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::IPropertySet>::python_type;


PyObject* IPropertySet_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IPropertySet interface is not activatable");
    return nullptr;
}

static void IPropertySet_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* IPropertySet__from(PyObject* /*unused*/, PyObject* arg)
{
    try
    {
        auto instance = py::converter<winrt::Windows::Foundation::IInspectable>::convert_to(arg);
        return py::converter<winrt::Windows::Foundation::Collections::IPropertySet>::convert(instance.as<winrt::Windows::Foundation::Collections::IPropertySet>());
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyObject* IPropertySet_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::Windows::Foundation::IInspectable>> return_value = self->obj.First();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::Windows::Foundation::IInspectable> return_value = self->obj.GetView();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::Windows::Foundation::IInspectable>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::Windows::Foundation::IInspectable return_value = self->obj.Lookup(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_TypeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* IPropertySet_add_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::Windows::Foundation::Collections::MapChangedEventHandler<winrt::hstring, winrt::Windows::Foundation::IInspectable>>::convert_to(args);

            winrt::event_token return_value = self->obj.MapChanged(param0);

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* IPropertySet_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
    if (args != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "arguments not supported for get methods");
        return nullptr;
    }
        try
        {
            uint32_t return_value = self->obj.Size();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* IPropertySet_remove_MapChanged(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self, PyObject* args)
{ 
        try
        {
            auto param0 = py::converter<winrt::event_token>::convert_to(args);

            self->obj.MapChanged(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyMethodDef IPropertySet_methods[] = {
    { "Clear", (PyCFunction)IPropertySet_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)IPropertySet_First, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IPropertySet_GetView, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)IPropertySet_HasKey, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)IPropertySet_Insert, METH_VARARGS, nullptr },
    { "Lookup", (PyCFunction)IPropertySet_Lookup, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)IPropertySet_Remove, METH_VARARGS, nullptr },
    { "add_MapChanged", (PyCFunction)IPropertySet_add_MapChanged, METH_O, nullptr },
    { "get_Size", (PyCFunction)IPropertySet_get_Size, METH_NOARGS, nullptr },
    { "remove_MapChanged", (PyCFunction)IPropertySet_remove_MapChanged, METH_O, nullptr },
    { "_from", (PyCFunction)IPropertySet__from, METH_O | METH_STATIC, nullptr },
    { nullptr }
};

static PyType_Slot IPropertySet_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IPropertySet_dealloc },
    { Py_tp_new, IPropertySet_new },
    { Py_tp_methods, IPropertySet_methods },
    { 0, nullptr },
};

static PyType_Spec IPropertySet_Type_spec =
{
    "IPropertySet",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>),
    0,
    Py_TPFLAGS_DEFAULT,
    IPropertySet_Type_slots
};

// ----- IVectorChangedEventArgs interface --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>::python_type;


PyObject* IVectorChangedEventArgs_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IVectorChangedEventArgs interface is not activatable");
    return nullptr;
}

static void IVectorChangedEventArgs_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* IVectorChangedEventArgs__from(PyObject* /*unused*/, PyObject* arg)
{
    try
    {
        auto instance = py::converter<winrt::Windows::Foundation::IInspectable>::convert_to(arg);
        return py::converter<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>::convert(instance.as<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>());
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyObject* IVectorChangedEventArgs_get_CollectionChange(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>* self, PyObject* args)
{ 
    if (args != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "arguments not supported for get methods");
        return nullptr;
    }
        try
        {
            winrt::Windows::Foundation::Collections::CollectionChange return_value = self->obj.CollectionChange();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyObject* IVectorChangedEventArgs_get_Index(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>* self, PyObject* args)
{ 
    if (args != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "arguments not supported for get methods");
        return nullptr;
    }
        try
        {
            uint32_t return_value = self->obj.Index();

            return py::converter<decltype(return_value)>::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
}

static PyMethodDef IVectorChangedEventArgs_methods[] = {
    { "get_CollectionChange", (PyCFunction)IVectorChangedEventArgs_get_CollectionChange, METH_NOARGS, nullptr },
    { "get_Index", (PyCFunction)IVectorChangedEventArgs_get_Index, METH_NOARGS, nullptr },
    { "_from", (PyCFunction)IVectorChangedEventArgs__from, METH_O | METH_STATIC, nullptr },
    { nullptr }
};

static PyType_Slot IVectorChangedEventArgs_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IVectorChangedEventArgs_dealloc },
    { Py_tp_new, IVectorChangedEventArgs_new },
    { Py_tp_methods, IVectorChangedEventArgs_methods },
    { 0, nullptr },
};

static PyType_Spec IVectorChangedEventArgs_Type_spec =
{
    "IVectorChangedEventArgs",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>),
    0,
    Py_TPFLAGS_DEFAULT,
    IVectorChangedEventArgs_Type_slots
};

// ----- IVectorView interface --------------------
PyTypeObject* py::winrt_type<pyIVectorView>::python_type;


PyObject* IVectorView_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IVectorView interface is not activatable");
    return nullptr;
}

static void IVectorView_dealloc(py::winrt_pinterface_wrapper<pyIVectorView>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IVectorView_First(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyObject* IVectorView_GetAt(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{ 
    return self->obj->GetAt(args);
}

static PyObject* IVectorView_GetMany(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{ 
    return self->obj->GetMany(args);
}

static PyObject* IVectorView_IndexOf(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{ 
    return self->obj->IndexOf(args);
}

static PyObject* IVectorView_get_Size(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{ 
    return self->obj->get_Size(args);
}

static PyMethodDef IVectorView_methods[] = {
    { "First", (PyCFunction)IVectorView_First, METH_VARARGS, nullptr },
    { "GetAt", (PyCFunction)IVectorView_GetAt, METH_VARARGS, nullptr },
    { "GetMany", (PyCFunction)IVectorView_GetMany, METH_VARARGS, nullptr },
    { "IndexOf", (PyCFunction)IVectorView_IndexOf, METH_VARARGS, nullptr },
    { "get_Size", (PyCFunction)IVectorView_get_Size, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IVectorView_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IVectorView_dealloc },
    { Py_tp_new, IVectorView_new },
    { Py_tp_methods, IVectorView_methods },
    { 0, nullptr },
};

static PyType_Spec IVectorView_Type_spec =
{
    "IVectorView",
    sizeof(py::winrt_pinterface_wrapper<pyIVectorView>),
    0,
    Py_TPFLAGS_DEFAULT,
    IVectorView_Type_slots
};

// ----- IVector interface --------------------
PyTypeObject* py::winrt_type<pyIVector>::python_type;


PyObject* IVector_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    PyErr_SetString(PyExc_TypeError, "IVector interface is not activatable");
    return nullptr;
}

static void IVector_dealloc(py::winrt_pinterface_wrapper<pyIVector>* self)
{
    auto hash_value = self->obj->hash();
    py::wrapped_instance(hash_value, nullptr);
    self->obj.release();
}

static PyObject* IVector_Append(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->Append(args);
}

static PyObject* IVector_Clear(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->Clear(args);
}

static PyObject* IVector_First(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->First(args);
}

static PyObject* IVector_GetAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->GetAt(args);
}

static PyObject* IVector_GetMany(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->GetMany(args);
}

static PyObject* IVector_GetView(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->GetView(args);
}

static PyObject* IVector_IndexOf(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->IndexOf(args);
}

static PyObject* IVector_InsertAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->InsertAt(args);
}

static PyObject* IVector_RemoveAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->RemoveAt(args);
}

static PyObject* IVector_RemoveAtEnd(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->RemoveAtEnd(args);
}

static PyObject* IVector_ReplaceAll(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->ReplaceAll(args);
}

static PyObject* IVector_SetAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->SetAt(args);
}

static PyObject* IVector_get_Size(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{ 
    return self->obj->get_Size(args);
}

static PyMethodDef IVector_methods[] = {
    { "Append", (PyCFunction)IVector_Append, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)IVector_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)IVector_First, METH_VARARGS, nullptr },
    { "GetAt", (PyCFunction)IVector_GetAt, METH_VARARGS, nullptr },
    { "GetMany", (PyCFunction)IVector_GetMany, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IVector_GetView, METH_VARARGS, nullptr },
    { "IndexOf", (PyCFunction)IVector_IndexOf, METH_VARARGS, nullptr },
    { "InsertAt", (PyCFunction)IVector_InsertAt, METH_VARARGS, nullptr },
    { "RemoveAt", (PyCFunction)IVector_RemoveAt, METH_VARARGS, nullptr },
    { "RemoveAtEnd", (PyCFunction)IVector_RemoveAtEnd, METH_VARARGS, nullptr },
    { "ReplaceAll", (PyCFunction)IVector_ReplaceAll, METH_VARARGS, nullptr },
    { "SetAt", (PyCFunction)IVector_SetAt, METH_VARARGS, nullptr },
    { "get_Size", (PyCFunction)IVector_get_Size, METH_NOARGS, nullptr },
    { nullptr }
};

static PyType_Slot IVector_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IVector_dealloc },
    { Py_tp_new, IVector_new },
    { Py_tp_methods, IVector_methods },
    { 0, nullptr },
};

static PyType_Spec IVector_Type_spec =
{
    "IVector",
    sizeof(py::winrt_pinterface_wrapper<pyIVector>),
    0,
    Py_TPFLAGS_DEFAULT,
    IVector_Type_slots
};

// ----- Windows.Foundation.Collections Initialization --------------------

int initialize_Windows_Foundation_Collections(PyObject* module)
{
    PyObject* type_object{ nullptr };


    PropertySet_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&PropertySet_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "PropertySet", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::PropertySet>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    StringMap_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&StringMap_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "StringMap", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::StringMap>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    ValueSet_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&ValueSet_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "ValueSet", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::ValueSet>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IIterable_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IIterable_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IIterable", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIIterable>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IIterator_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IIterator_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IIterator", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIIterator>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IKeyValuePair_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IKeyValuePair_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IKeyValuePair", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIKeyValuePair>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IMapChangedEventArgs_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IMapChangedEventArgs_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IMapChangedEventArgs", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIMapChangedEventArgs>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IMapView_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IMapView_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IMapView", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIMapView>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IMap_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IMap_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IMap", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIMap>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IObservableMap_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IObservableMap_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IObservableMap", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIObservableMap>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IObservableVector_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IObservableVector_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IObservableVector", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIObservableVector>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IPropertySet_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IPropertySet_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IPropertySet", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::IPropertySet>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IVectorChangedEventArgs_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IVectorChangedEventArgs_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IVectorChangedEventArgs", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IVectorView_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IVectorView_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IVectorView", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIVectorView>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IVector_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IVector_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IVector", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIVector>::python_type = reinterpret_cast<PyTypeObject*>(type_object);
    
    return 0;
}
