# WARNING: Please don't edit this file. It was generated by Python/WinRT

# TODO: remove explicit debug settings in favor of build_ext --debug setting

import setuptools

setuptools.setup(
    name = "pyrt",
    version = "1.0a0",
    description="Generated Python/WinRT package",
    license="MIT",
    url="http://github.com/Microsoft/xlang",
    ext_modules = [ setuptools.Extension('_pyrt', 
        sources = ['pyrt/src/py.Windows.AI.MachineLearning.cpp', 'pyrt/src/py.Windows.Data.Json.cpp', 'pyrt/src/py.Windows.Devices.Geolocation.cpp', 'pyrt/src/py.Windows.Devices.Geolocation.Geofencing.cpp', 'pyrt/src/py.Windows.Foundation.cpp', 'pyrt/src/py.Windows.Foundation.Collections.cpp', 'pyrt/src/py.Windows.Foundation.Numerics.cpp', 'pyrt/src/py.Windows.Graphics.DirectX.cpp', 'pyrt/src/py.Windows.Graphics.DirectX.Direct3D11.cpp', 'pyrt/src/py.Windows.Graphics.Imaging.cpp', 'pyrt/src/py.Windows.Media.cpp', 'pyrt/src/py.Windows.Storage.cpp', 'pyrt/src/py.Windows.Storage.Search.cpp', 'pyrt/src/py.Windows.Storage.Streams.cpp', 'pyrt/src/_pyrt.cpp'],
        extra_compile_args = ["/std:c++17", "/await"],
        include_dirs = ['.'],
        extra_link_args=['/DEBUG'],
        libraries = ['windowsapp']) ],
    packages = setuptools.find_namespace_packages())
