# WARNING: Please don't edit this file. It was generated by Python/WinRT

from pyrt import _import_ns
import typing
import enum

__ns__ = _import_ns("Windows.Storage")

try:
    import pyrt.windows.foundation
except:
    pass

try:
    import pyrt.windows.foundation.collections
except:
    pass

try:
    import pyrt.windows.storage.fileproperties
except:
    pass

try:
    import pyrt.windows.storage.provider
except:
    pass

try:
    import pyrt.windows.storage.search
except:
    pass

try:
    import pyrt.windows.storage.streams
except:
    pass

try:
    import pyrt.windows.system
except:
    pass

class ApplicationDataCreateDisposition(enum.IntEnum):
    Always = 0
    Existing = 1

class ApplicationDataLocality(enum.IntEnum):
    Local = 0
    Roaming = 1
    Temporary = 2
    LocalCache = 3

class CreationCollisionOption(enum.IntEnum):
    GenerateUniqueName = 0
    ReplaceExisting = 1
    FailIfExists = 2
    OpenIfExists = 3

class FileAccessMode(enum.IntEnum):
    Read = 0
    ReadWrite = 1

class FileAttributes(enum.IntFlag):
    Normal = 0
    ReadOnly = 0x1
    Directory = 0x10
    Archive = 0x20
    Temporary = 0x100
    LocallyIncomplete = 0x200

class KnownFolderId(enum.IntEnum):
    AppCaptures = 0
    CameraRoll = 1
    DocumentsLibrary = 2
    HomeGroup = 3
    MediaServerDevices = 4
    MusicLibrary = 5
    Objects3D = 6
    PicturesLibrary = 7
    Playlists = 8
    RecordedCalls = 9
    RemovableDevices = 10
    SavedPictures = 11
    Screenshots = 12
    VideosLibrary = 13
    AllAppMods = 14
    CurrentAppMods = 15

class KnownLibraryId(enum.IntEnum):
    Music = 0
    Pictures = 1
    Videos = 2
    Documents = 3

class NameCollisionOption(enum.IntEnum):
    GenerateUniqueName = 0
    ReplaceExisting = 1
    FailIfExists = 2

class StorageDeleteOption(enum.IntEnum):
    Default = 0
    PermanentDelete = 1

class StorageItemTypes(enum.IntFlag):
    NONE = 0
    File = 0x1
    Folder = 0x2

class StorageLibraryChangeType(enum.IntEnum):
    Created = 0
    Deleted = 1
    MovedOrRenamed = 2
    ContentsChanged = 3
    MovedOutOfLibrary = 4
    MovedIntoLibrary = 5
    ContentsReplaced = 6
    IndexingStatusChanged = 7
    EncryptionChanged = 8
    ChangeTrackingLost = 9

class StorageOpenOptions(enum.IntFlag):
    NONE = 0
    AllowOnlyReaders = 0x1
    AllowReadersAndWriters = 0x2

class StreamedFileFailureMode(enum.IntEnum):
    Failed = 0
    CurrentlyUnavailable = 1
    Incomplete = 2

AppDataPaths = __ns__.AppDataPaths
ApplicationData = __ns__.ApplicationData
ApplicationDataCompositeValue = __ns__.ApplicationDataCompositeValue
ApplicationDataContainer = __ns__.ApplicationDataContainer
ApplicationDataContainerSettings = __ns__.ApplicationDataContainerSettings
CachedFileManager = __ns__.CachedFileManager
DownloadsFolder = __ns__.DownloadsFolder
FileIO = __ns__.FileIO
KnownFolders = __ns__.KnownFolders
PathIO = __ns__.PathIO
SetVersionDeferral = __ns__.SetVersionDeferral
SetVersionRequest = __ns__.SetVersionRequest
StorageFile = __ns__.StorageFile
StorageFolder = __ns__.StorageFolder
StorageLibrary = __ns__.StorageLibrary
StorageLibraryChange = __ns__.StorageLibraryChange
StorageLibraryChangeReader = __ns__.StorageLibraryChangeReader
StorageLibraryChangeTracker = __ns__.StorageLibraryChangeTracker
StorageProvider = __ns__.StorageProvider
StorageStreamTransaction = __ns__.StorageStreamTransaction
StreamedFileDataRequest = __ns__.StreamedFileDataRequest
SystemAudioProperties = __ns__.SystemAudioProperties
SystemDataPaths = __ns__.SystemDataPaths
SystemGPSProperties = __ns__.SystemGPSProperties
SystemImageProperties = __ns__.SystemImageProperties
SystemMediaProperties = __ns__.SystemMediaProperties
SystemMusicProperties = __ns__.SystemMusicProperties
SystemPhotoProperties = __ns__.SystemPhotoProperties
SystemProperties = __ns__.SystemProperties
SystemVideoProperties = __ns__.SystemVideoProperties
UserDataPaths = __ns__.UserDataPaths
IStorageFile = __ns__.IStorageFile
IStorageFile2 = __ns__.IStorageFile2
IStorageFilePropertiesWithAvailability = __ns__.IStorageFilePropertiesWithAvailability
IStorageFolder = __ns__.IStorageFolder
IStorageFolder2 = __ns__.IStorageFolder2
IStorageItem = __ns__.IStorageItem
IStorageItem2 = __ns__.IStorageItem2
IStorageItemProperties = __ns__.IStorageItemProperties
IStorageItemProperties2 = __ns__.IStorageItemProperties2
IStorageItemPropertiesWithProvider = __ns__.IStorageItemPropertiesWithProvider
IStreamedFileDataRequest = __ns__.IStreamedFileDataRequest
