import "Windows.Foundation.idl";

namespace test_component
{
    delegate void AgileDelegate();

    enum Signed
    {
        First = -1,
        Second = 0,
        Third = 1
    };

    [flags]
    enum Unsigned
    {
        First = 0,
        Second = 1,
        Third = 2
    };

    struct Struct
    {
        String First;
        String Second;
    };

    runtimeclass Class
    {
        Class();

        void Fail(Boolean value);

        String InInt32(Int32 value);
        String InString(String value);
        String InObject(Object value);
        String InStringable(Windows.Foundation.IStringable value);
        String InStruct(Struct value);
        String InStructRef(ref const Struct value);

        void OutInt32(out Int32 value);
        void OutString(out String value);
        void OutObject(out Object value);
        void OutStringable(out Windows.Foundation.IStringable value);
        void OutStruct(out Struct value);

        Int32 ReturnInt32();
        String ReturnString();
        Object ReturnObject();
        Windows.Foundation.IStringable ReturnStringable();
        Struct ReturnStruct();

        String InInt32Array(Int32[] value);
        String InStringArray(String[] value);
        String InObjectArray(Object[] value);
        String InStringableArray(Windows.Foundation.IStringable[] value);
        String InStructArray(Struct[] value);

        void OutInt32Array(out Int32[] value);
        void OutStringArray(out String[] value);
        void OutObjectArray(out Object[] value);
        void OutStringableArray(out Windows.Foundation.IStringable[] value);
        void OutStructArray(out Struct[] value);

        void RefInt32Array(ref Int32[] value);
        void RefStringArray(ref String[] value);
        void RefObjectArray(ref Object[] value);
        void RefStringableArray(ref Windows.Foundation.IStringable[] value);
        void RefStructArray(ref Struct[] value);

        Int32[] ReturnInt32Array();
        String[] ReturnStringArray();
        Object[] ReturnObjectArray();
        Windows.Foundation.IStringable[] ReturnStringableArray();
        Struct[] ReturnStructArray();
    }
}
