# WARNING: Please don't edit this file. It was generated by Python/WinRT

import %
%.init_apartment()

def _import_ns(ns):
    module_name = "%_" + ns.replace('.', '_')

    import importlib.machinery
    import importlib.util
    loader = importlib.machinery.ExtensionFileLoader(module_name, %.__file__)
    spec = importlib.util.spec_from_loader(module_name, loader)
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module
