

namespace Windows.Internal.Foundation.Contracts
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};


    [uuid(da805a35-961f-4194-a4bb-e9e86347d589)]
    [contract(Windows.Internal.Foundation.Contracts.InternalContract, 1)]
    interface IActivationFactoryContractRedirector
    {
        Object TryActivateInstance(String contractId, ActivationFactoryContractRedirectorContext context);
        Boolean IsSupported(String contractId, ActivationFactoryContractRedirectorContext context);
    };

    [contract(Windows.Internal.Foundation.Contracts.InternalContract, 1)]
    [interface_name("Windows.Internal.Foundation.Contracts.IActivationFactoryContractRedirectorContext", 7d6e17e4-e332-45e3-a8c9-b7291a38c23b)]
    runtimeclass ActivationFactoryContractRedirectorContext
    {
        Windows.Internal.ApplicationModel.WindowManagement.WindowId WindowId{ set; };
        Windows.Internal.ApplicationModel.WindowManagement.WindowId WindowId{ get; };
        UInt32 ProcessId{ set; };
        UInt32 ProcessId{ get; };
    }

}
