







namespace Windows.System.Profile
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Profile.IAnalyticsVersionInfo", 926130b8-9955-4c74-bdc1-7cd0decf9b03)]
    runtimeclass AnalyticsVersionInfo
    {
        String DeviceFamily{ get; };
        String DeviceFamilyVersion{ get; };
    }



    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.System.Profile.IAnalyticsInfoStatics", 1d5ee066-188d-5ba9-4387-acaeb0e7e305)]
    [threading(both)]
    runtimeclass AnalyticsInfo
    {

        [contract(Windows.Foundation.UniversalApiContract, 6)]
        [static_name("Windows.System.Profile.IAnalyticsInfoStatics2", 101704ea-a7f9-46d2-ab94-016865afdb25)]
        {
            static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IMapView <String, String> >  GetSystemPropertiesAsync(Windows.Foundation.Collections.IIterable <String>  attributeNames);
        }
        static Windows.System.Profile.AnalyticsVersionInfo VersionInfo{ get; };
        static String DeviceForm{ get; };
    }

}
