








namespace Windows.Media.Capture
{
    [contractversion(4)]
    apicontract AppCaptureContract{};

}
namespace Windows.Media.Capture.Internal
{
    [contractversion(1)]
    [internal]
    apicontract AppCaptureContractInternal{};

    [contractversion(1)]
    [internal]
    apicontract AppCaptureContract_Proposed{};

}
namespace Windows.Media.Capture
{
    [contract(Windows.Media.Capture.AppCaptureContract, 1)]
    enum AppCaptureVideoEncodingBitrateMode
    {
        Custom,
        High,
        Standard,
    };

    [contract(Windows.Media.Capture.AppCaptureContract, 1)]
    enum AppCaptureVideoEncodingResolutionMode
    {
        Custom,
        High,
        Standard,
    };

    [contract(Windows.Media.Capture.AppCaptureContract, 3)]
    enum AppCaptureVideoEncodingFrameRateMode
    {
        Standard,
        High,
    };

    [contract(Windows.Media.Capture.AppCaptureContract, 1)]
    enum AppCaptureHistoricalBufferLengthUnit
    {
        Megabytes,
        Seconds,
    };


    [contract(Windows.Media.Capture.AppCaptureContract, 1)]
    [interface_name("Windows.Media.Capture.IAppCaptureSettings", 14683a86-8807-48d3-883a-970ee4532a39)]
    runtimeclass AppCaptureSettings
    {
        Windows.Storage.StorageFolder AppCaptureDestinationFolder{ set; };
        Windows.Storage.StorageFolder AppCaptureDestinationFolder{ get; };
        UInt32 AudioEncodingBitrate{ set; };
        UInt32 AudioEncodingBitrate{ get; };
        Boolean IsAudioCaptureEnabled{ set; };
        Boolean IsAudioCaptureEnabled{ get; };
        UInt32 CustomVideoEncodingBitrate{ set; };
        UInt32 CustomVideoEncodingBitrate{ get; };
        UInt32 CustomVideoEncodingHeight{ set; };
        UInt32 CustomVideoEncodingHeight{ get; };
        UInt32 CustomVideoEncodingWidth{ set; };
        UInt32 CustomVideoEncodingWidth{ get; };
        UInt32 HistoricalBufferLength{ set; };
        UInt32 HistoricalBufferLength{ get; };
        Windows.Media.Capture.AppCaptureHistoricalBufferLengthUnit HistoricalBufferLengthUnit{ set; };
        Windows.Media.Capture.AppCaptureHistoricalBufferLengthUnit HistoricalBufferLengthUnit{ get; };
        Boolean IsHistoricalCaptureEnabled{ set; };
        Boolean IsHistoricalCaptureEnabled{ get; };
        Boolean IsHistoricalCaptureOnBatteryAllowed{ set; };
        Boolean IsHistoricalCaptureOnBatteryAllowed{ get; };
        Boolean IsHistoricalCaptureOnWirelessDisplayAllowed{ set; };
        Boolean IsHistoricalCaptureOnWirelessDisplayAllowed{ get; };
        Windows.Foundation.TimeSpan MaximumRecordLength{ set; };
        Windows.Foundation.TimeSpan MaximumRecordLength{ get; };
        Windows.Storage.StorageFolder ScreenshotDestinationFolder{ set; };
        Windows.Storage.StorageFolder ScreenshotDestinationFolder{ get; };
        Windows.Media.Capture.AppCaptureVideoEncodingBitrateMode VideoEncodingBitrateMode{ set; };
        Windows.Media.Capture.AppCaptureVideoEncodingBitrateMode VideoEncodingBitrateMode{ get; };
        Windows.Media.Capture.AppCaptureVideoEncodingResolutionMode VideoEncodingResolutionMode{ set; };
        Windows.Media.Capture.AppCaptureVideoEncodingResolutionMode VideoEncodingResolutionMode{ get; };
        Boolean IsAppCaptureEnabled{ set; };
        Boolean IsAppCaptureEnabled{ get; };
        Boolean IsCpuConstrained{ get; };
        Boolean IsDisabledByPolicy{ get; };
        Boolean IsMemoryConstrained{ get; };
        Boolean HasHardwareEncoder{ get; };

        [interface_name("Windows.Media.Capture.IAppCaptureSettings2", fcb8cee7-e26b-476f-9b1a-ec342d2a8fde)]
        {
            Boolean IsGpuConstrained{ get; };
            Windows.Media.Capture.AppCaptureAlternateShortcutKeys AlternateShortcutKeys{ get; };
        }

        [contract(Windows.Media.Capture.AppCaptureContract, 2)]
        [interface_name("Windows.Media.Capture.IAppCaptureSettings3", a93502fe-88c2-42d6-aaaa-40feffd75aec)]
        {
            Boolean IsMicrophoneCaptureEnabled{ set; };
            Boolean IsMicrophoneCaptureEnabled{ get; };
        }

        [contract(Windows.Media.Capture.AppCaptureContract, 3)]
        [interface_name("Windows.Media.Capture.IAppCaptureSettings4", 07c2774c-1a81-482f-a244-049d95f25b0b)]
        {
            Boolean IsMicrophoneCaptureEnabledByDefault{ set; };
            Boolean IsMicrophoneCaptureEnabledByDefault{ get; };
            Double SystemAudioGain{ set; };
            Double SystemAudioGain{ get; };
            Double MicrophoneGain{ set; };
            Double MicrophoneGain{ get; };
            Windows.Media.Capture.AppCaptureVideoEncodingFrameRateMode VideoEncodingFrameRateMode{ set; };
            Windows.Media.Capture.AppCaptureVideoEncodingFrameRateMode VideoEncodingFrameRateMode{ get; };
        }

        [contract(Windows.Media.Capture.AppCaptureContract, 4)]
        [interface_name("Windows.Media.Capture.IAppCaptureSettings5", 18894522-b0e8-4ba0-8f13-3eaa5fa4013b)]
        {
            Boolean IsEchoCancellationEnabled{ set; };
            Boolean IsEchoCancellationEnabled{ get; };
            Boolean IsCursorImageCaptureEnabled{ set; };
            Boolean IsCursorImageCaptureEnabled{ get; };
        }
    }






    [contract(Windows.Media.Capture.AppCaptureContract, 1)]
    [interface_name("Windows.Media.Capture.IAppCaptureAlternateShortcutKeys", 19e8e0ef-236c-40f9-b38f-9b7dd65d1ccc)]
    runtimeclass AppCaptureAlternateShortcutKeys
    {
        Windows.System.VirtualKey ToggleGameBarKey{ set; };
        Windows.System.VirtualKey ToggleGameBarKey{ get; };
        Windows.System.VirtualKeyModifiers ToggleGameBarKeyModifiers{ set; };
        Windows.System.VirtualKeyModifiers ToggleGameBarKeyModifiers{ get; };
        Windows.System.VirtualKey SaveHistoricalVideoKey{ set; };
        Windows.System.VirtualKey SaveHistoricalVideoKey{ get; };
        Windows.System.VirtualKeyModifiers SaveHistoricalVideoKeyModifiers{ set; };
        Windows.System.VirtualKeyModifiers SaveHistoricalVideoKeyModifiers{ get; };
        Windows.System.VirtualKey ToggleRecordingKey{ set; };
        Windows.System.VirtualKey ToggleRecordingKey{ get; };
        Windows.System.VirtualKeyModifiers ToggleRecordingKeyModifiers{ set; };
        Windows.System.VirtualKeyModifiers ToggleRecordingKeyModifiers{ get; };
        Windows.System.VirtualKey TakeScreenshotKey{ set; };
        Windows.System.VirtualKey TakeScreenshotKey{ get; };
        Windows.System.VirtualKeyModifiers TakeScreenshotKeyModifiers{ set; };
        Windows.System.VirtualKeyModifiers TakeScreenshotKeyModifiers{ get; };
        Windows.System.VirtualKey ToggleRecordingIndicatorKey{ set; };
        Windows.System.VirtualKey ToggleRecordingIndicatorKey{ get; };
        Windows.System.VirtualKeyModifiers ToggleRecordingIndicatorKeyModifiers{ set; };
        Windows.System.VirtualKeyModifiers ToggleRecordingIndicatorKeyModifiers{ get; };

        [contract(Windows.Media.Capture.AppCaptureContract, 2)]
        [interface_name("Windows.Media.Capture.IAppCaptureAlternateShortcutKeys2", c3669090-dd17-47f0-95e5-ce42286cf338)]
        {
            Windows.System.VirtualKey ToggleMicrophoneCaptureKey{ set; };
            Windows.System.VirtualKey ToggleMicrophoneCaptureKey{ get; };
            Windows.System.VirtualKeyModifiers ToggleMicrophoneCaptureKeyModifiers{ set; };
            Windows.System.VirtualKeyModifiers ToggleMicrophoneCaptureKeyModifiers{ get; };
        }

        [contract(Windows.Media.Capture.AppCaptureContract, 3)]
        [interface_name("Windows.Media.Capture.IAppCaptureAlternateShortcutKeys3", 7b81448c-418e-469c-a49a-45b597c826b6)]
        {
            Windows.System.VirtualKey ToggleCameraCaptureKey{ set; };
            Windows.System.VirtualKey ToggleCameraCaptureKey{ get; };
            Windows.System.VirtualKeyModifiers ToggleCameraCaptureKeyModifiers{ set; };
            Windows.System.VirtualKeyModifiers ToggleCameraCaptureKeyModifiers{ get; };
            Windows.System.VirtualKey ToggleBroadcastKey{ set; };
            Windows.System.VirtualKey ToggleBroadcastKey{ get; };
            Windows.System.VirtualKeyModifiers ToggleBroadcastKeyModifiers{ set; };
            Windows.System.VirtualKeyModifiers ToggleBroadcastKeyModifiers{ get; };
        }
    }




    [contract(Windows.Media.Capture.AppCaptureContract, 1)]
    [static_name("Windows.Media.Capture.IAppCaptureManagerStatics", 7d9e3ea7-6282-4735-8d4e-aa45f90f6723)]
    [threading(both)]
    runtimeclass AppCaptureManager
    {
        static Windows.Media.Capture.AppCaptureSettings GetCurrentSettings();
        static void ApplySettings(AppCaptureSettings appCaptureSettings);
    }

    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    enum AppCaptureMicrophoneCaptureState
    {
        Stopped,
        Started,
        Failed,
    };

    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    enum AppCaptureRecordingState
    {
        InProgress,
        Completed,
        Failed,
    };


    [marshaling_behavior(agile)]
    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [interface_name("Windows.Media.Capture.IAppCaptureRecordOperation", c66020a9-1538-495c-9bbb-2ba870ec5861)]
    runtimeclass AppCaptureRecordOperation
    {
        void StopRecording();
        Windows.Media.Capture.AppCaptureRecordingState State{ get; };
        Windows.Foundation.IReference <UInt32>  ErrorCode{ get; };
        Windows.Foundation.IReference <Windows.Foundation.TimeSpan>  Duration{ get; };
        Windows.Storage.StorageFile File{ get; };
        Windows.Foundation.IReference <Boolean>  IsFileTruncated{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Media.Capture.AppCaptureRecordOperation, Windows.Media.Capture.AppCaptureRecordingStateChangedEventArgs>  StateChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Media.Capture.AppCaptureRecordOperation, Windows.Media.Capture.AppCaptureDurationGeneratedEventArgs>  DurationGenerated;
        event Windows.Foundation.TypedEventHandler <Windows.Media.Capture.AppCaptureRecordOperation, Windows.Media.Capture.AppCaptureFileGeneratedEventArgs>  FileGenerated;
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [interface_name("Windows.Media.Capture.IAppCaptureState", 73134372-d4eb-44ce-9538-465f506ac4ea)]
    runtimeclass AppCaptureState
    {
        Boolean IsTargetRunning{ get; };
        Boolean IsHistoricalCaptureEnabled{ get; };
        Boolean ShouldCaptureMicrophone{ get; };
        Boolean ShouldCaptureMicrophone{ set; };
        void RestartMicrophoneCapture();
        Windows.Media.Capture.AppCaptureMicrophoneCaptureState MicrophoneCaptureState{ get; };
        UInt32 MicrophoneCaptureError{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Media.Capture.AppCaptureState, Windows.Media.Capture.AppCaptureMicrophoneCaptureStateChangedEventArgs>  MicrophoneCaptureStateChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Media.Capture.AppCaptureState, Object>  CaptureTargetClosed;
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [interface_name("Windows.Media.Capture.IAppCaptureMicrophoneCaptureStateChangedEventArgs", 324d249e-45bc-4c35-bc35-e469fc7a69e0)]
    runtimeclass AppCaptureMicrophoneCaptureStateChangedEventArgs
    {
        Windows.Media.Capture.AppCaptureMicrophoneCaptureState State{ get; };
        UInt32 ErrorCode{ get; };
    }



    [marshaling_behavior(agile)]
    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [interface_name("Windows.Media.Capture.IAppCaptureRecordingStateChangedEventArgs", 24fc8712-e305-490d-b415-6b1c9049736b)]
    runtimeclass AppCaptureRecordingStateChangedEventArgs
    {
        Windows.Media.Capture.AppCaptureRecordingState State{ get; };
        UInt32 ErrorCode{ get; };
    }

    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Media.Capture.IAppCaptureDurationGeneratedEventArgs", c1f5563b-ffa1-44c9-975f-27fbeb553b35)]
    runtimeclass AppCaptureDurationGeneratedEventArgs
    {
        Windows.Foundation.TimeSpan Duration{ get; };
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [interface_name("Windows.Media.Capture.IAppCaptureFileGeneratedEventArgs", 4189fbf4-465e-45bf-907f-165b3fb23758)]
    runtimeclass AppCaptureFileGeneratedEventArgs
    {
        Windows.Storage.StorageFile File{ get; };
    }




    [marshaling_behavior(agile)]
    [contract(Windows.Media.Capture.AppCaptureContract, 4)]
    [interface_name("Windows.Media.Capture.IAppCaptureServices", 44fec0b5-34f5-4f18-ae8c-b9123abbfc0d)]
    runtimeclass AppCaptureServices
    {
        Windows.Media.Capture.AppCaptureRecordOperation Record();
        Windows.Media.Capture.AppCaptureRecordOperation RecordTimeSpan(Windows.Foundation.DateTime startTime, Windows.Foundation.TimeSpan duration);
        Boolean CanCapture{ get; };
        Windows.Media.Capture.AppCaptureState State{ get; };
    }

}
