











namespace Windows.ApplicationModel.Core
{
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.Core.IAppListEntry", ef00f07f-2108-490a-877a-8a9f17c25fad)]
    runtimeclass AppListEntry
    {
        Windows.ApplicationModel.AppDisplayInfo DisplayInfo{ get; };
        Windows.Foundation.IAsyncOperation <Boolean>  LaunchAsync();

        [contract(Windows.Foundation.UniversalApiContract, 5)]
        [interface_name("Windows.ApplicationModel.Core.IAppListEntry2", d0a618ad-bf35-42ac-ac06-86eeeb41d04b)]
        {
            String AppUserModelId{ get; };
        }

        [contract(Windows.Foundation.UniversalApiContract, 6)]
        [interface_name("Windows.ApplicationModel.Core.IAppListEntry3", 6099f28d-fc32-470a-bc69-4b061a76ef2e)]
        {
            Windows.Foundation.IAsyncOperation <Boolean>  LaunchForUserAsync(Windows.System.User user);
        }
    }

}
