













namespace Windows.Internal.Shell.CapturePicker
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};


    [contract(Windows.Internal.Shell.CapturePicker.InternalContract, 1)]
    [interface_name("Windows.Internal.Shell.CapturePicker.ICapturePickerActivatedEventArgs", c189b6bb-14bc-46cd-b504-c76080a3d791)]
    runtimeclass CapturePickerActivatedEventArgs
        : Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
        Windows.Foundation.Collections.IVector <Windows.Internal.PlatformExtensions.Capture.CapturableItem>  Items{ get; };
        Windows.Internal.PlatformExtensions.Capture.CapturableItem SelectedItem{ set; };
        Windows.Internal.PlatformExtensions.Capture.CapturableItem SelectedItem{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.CapturePicker.CapturePickerActivatedEventArgs, Windows.Internal.PlatformExtensions.Capture.CapturableItem>  ItemSelected;
    }

    [contract(Windows.Internal.Shell.CapturePicker.InternalContract, 1)]
    runtimeclass CapturePickerItemDataSource
        : [default]Windows.Internal.Shell.PlatformExtensions.ICapturePickerItemDataSource
    {
        CapturePickerItemDataSource();
    }

    [contract(Windows.Internal.Shell.CapturePicker.InternalContract, 1)]
    runtimeclass CapturePickerExperience
        : [default]Windows.Internal.PlatformExtensions.Capture.ICapturePickerExperience
    {
    }

}
