





namespace Windows.Internal.ComposableShell.TestHooks
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    enum ComposerType
    {
        Productivity,
        Tablet,
        Andromeda,
        Hub,
        Game = 3,
    };

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    [uuid(12fe5f97-40a7-471a-b920-0091b973579f)]
    interface IShellExperienceTestHook
    {
        void Show();
        void Hide();
        void SetRuntimePolicy(Int32 policyIndex);
    };

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    [uuid(1e52a1dd-033c-413b-a0f6-a153192c506f)]
    interface IAppsListTestHook
    {
        Boolean ConfirmAppsListHostingCorrectNumberOfViews(Int32 numViewsExpected);
        Boolean ConfirmAppsListHostsMultipleViewTypes();
    };

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    [uuid(83e1ecc1-d3b7-43f8-a881-c23065722d07)]
    interface IMulticomposerTestHook
    {
        void SwitchToComposerOnPrimaryDisplay(ComposerType type);
    };

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    [uuid(702426e3-cd90-4bd2-b63e-5c8108267bef)]
    interface IPolicyTestHook
    {
        void SetPolicy(Int32 policy);
    };

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    [uuid(5183b629-83c0-402e-95fb-1d44d00b2d23)]
    interface IDisplayManagerTestHook
    {
        void TurnUserPresenceOn();
        void TurnUserPresenceOff();
    };

    [contract(Windows.Internal.ComposableShell.TestHooks.InternalContract, 1)]
    [uuid(9562b160-3095-4915-8584-6592673699fe)]
    interface IComponentTestHookService
    {
        Windows.Internal.ComposableShell.TestHooks.IShellExperienceTestHook ExperienceTestHook{ get; };
        Windows.Internal.ComposableShell.TestHooks.IAppsListTestHook AppsListTestHook{ get; };
        Windows.Internal.ComposableShell.TestHooks.IMulticomposerTestHook MulticomposerTestHook{ get; };
        Windows.Internal.ComposableShell.TestHooks.IDisplayManagerTestHook DisplayManagerTestHook{ get; };
        Windows.Internal.ComposableShell.TestHooks.IPolicyTestHook PolicyTestHook{ get; };
    };

}
