

















namespace Windows.Internal.ComposableShell
{
    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    [static_name("Windows.Internal.ComposableShell.IComposerViewStatics", e05ad0f0-d56f-4983-aa01-dd788e4c31d1)]
    [interface_name("Windows.Internal.ComposableShell.IComposerView", 8fecc6e6-705d-4190-980e-103a37b170fb)]
    runtimeclass ComposerView
        : Windows.Internal.ComposableShell.IForegroundTarget
        , Windows.Internal.ComposableShell.IComposableView
        , Windows.Internal.ComposableShell.ITreeNode
        , Windows.Internal.ComposableShell.IResizableView
        , Windows.Internal.ComposableShell.IViewPointerActivationPolicy
        , Windows.Internal.ComposableShell.IRotatableView
    {
        static Windows.Internal.ComposableShell.ComposerView GetForCurrentView();
        UInt32 ProcessId{ get; };
        void SetContext(IComposerContext context);
    }

}
