






namespace Windows.Internal.ComposableShell
{
    [uuid(3073a0e2-f6b6-4e0e-b3d3-38c440b06f26)]
    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    interface IContainerManagerController
    {
        void InitializeContainer(out Guid containerId, out String ipAddress, out String userName, out String password);
        void ShowWindow(UInt32 windowId);
        void HideWindow(UInt32 windowId);
        void InitializeUiaManagerConnection();
        void ReleaseContainer();
        void DisableLifetimeManagement(String packageFamilyName);
    };

    [marshaling_behavior(agile)]
    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    [threading(both)]
    runtimeclass ContainerManagerController
        : [default]Windows.Internal.ComposableShell.IContainerManagerController
    {
        ContainerManagerController();
    }

}
