







namespace Windows.Security.Credentials.UI
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum AuthenticationProtocol
    {
        Basic,
        Digest,
        Ntlm,
        Kerberos,
        Negotiate,
        CredSsp,
        Custom,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum CredentialSaveOption
    {
        Unselected,
        Selected,
        Hidden,
    };


    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Security.Credentials.UI.ICredentialPickerOptions", 965a0b4c-95fa-467f-992b-0b22e5859bf6)]
    [threading(both)]
    runtimeclass CredentialPickerOptions
    {
        CredentialPickerOptions();
        String Caption{ set; };
        String Caption{ get; };
        String Message{ set; };
        String Message{ get; };
        UInt32 ErrorCode{ set; };
        UInt32 ErrorCode{ get; };
        String TargetName{ set; };
        String TargetName{ get; };
        Windows.Security.Credentials.UI.AuthenticationProtocol AuthenticationProtocol{ set; };
        Windows.Security.Credentials.UI.AuthenticationProtocol AuthenticationProtocol{ get; };
        String CustomAuthenticationProtocol{ set; };
        String CustomAuthenticationProtocol{ get; };
        Windows.Storage.Streams.IBuffer PreviousCredential{ set; };
        Windows.Storage.Streams.IBuffer PreviousCredential{ get; };
        Boolean AlwaysDisplayDialog{ set; };
        Boolean AlwaysDisplayDialog{ get; };
        Boolean CallerSavesCredential{ set; };
        Boolean CallerSavesCredential{ get; };
        Windows.Security.Credentials.UI.CredentialSaveOption CredentialSaveOption{ set; };
        Windows.Security.Credentials.UI.CredentialSaveOption CredentialSaveOption{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Security.Credentials.UI.ICredentialPickerResults", 1948f99a-cc30-410c-9c38-cc0884c5b3d7)]
    runtimeclass CredentialPickerResults
    {
        UInt32 ErrorCode{ get; };
        Windows.Security.Credentials.UI.CredentialSaveOption CredentialSaveOption{ get; };
        Boolean CredentialSaved{ get; };
        Windows.Storage.Streams.IBuffer Credential{ get; };
        String CredentialDomainName{ get; };
        String CredentialUserName{ get; };
        String CredentialPassword{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.Security.Credentials.UI.ICredentialPickerStatics", aa3a5c73-c9ea-4782-99fb-e6d7e938e12d)]
    [threading(both)]
    runtimeclass CredentialPicker
    {
        [method_name("PickWithOptionsAsync")] [remote_sync]static Windows.Foundation.IAsyncOperation <Windows.Security.Credentials.UI.CredentialPickerResults>  PickAsync(CredentialPickerOptions options);
        [method_name("PickWithMessageAsync")] static Windows.Foundation.IAsyncOperation <Windows.Security.Credentials.UI.CredentialPickerResults>  PickAsync(String targetName, String message);
        [method_name("PickWithCaptionAsync")] static Windows.Foundation.IAsyncOperation <Windows.Security.Credentials.UI.CredentialPickerResults>  PickAsync(String targetName, String message, String caption);
    }


}
