






namespace Windows.Internal
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Internal.InternalContract, 1)]
    [uuid(9ada2dc6-0666-4849-97a0-5f3d9320ce9b)]
    interface ICustomDialogWindowRequestPriv
    {
        void UpdateDialogTitle(String value);
        void UpdateDialogSize(Windows.Foundation.Size value);
        void RequestClose();
    };


    [contract(Windows.Internal.InternalContract, 1)]
    [interface_name("Windows.Internal.ICustomDialogWindowRequest", 20861bd4-741e-4ea8-9523-a494907a3df8)]
    runtimeclass CustomDialogWindowRequest
    {
        CustomDialogWindowRequest();
        String DialogType{ set; };
        String DialogType{ get; };
        String DialogTitle{ set; };
        String DialogTitle{ get; };
        UInt32 InvokingWindow{ set; };
        UInt32 InvokingWindow{ get; };
        UInt32 ConnectCookie{ set; };
        UInt32 ConnectCookie{ get; };
        UInt32 ComponentPid{ set; };
        UInt32 ComponentPid{ get; };
        Windows.Foundation.Size RequestedSize{ set; };
        Windows.Foundation.Size RequestedSize{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Internal.CustomDialogWindowRequest, Boolean>  CloseRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.CustomDialogWindowRequest, Windows.Foundation.Size>  RequestedSizeChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.CustomDialogWindowRequest, String>  TitleChanged;
        void Close();
    }

    [contract(Windows.Internal.InternalContract, 1)]
    [uuid(158b1c42-fefd-459f-8f5e-a00083f42a92)]
    interface ICustomSystemDialogWindowManagerPriv
    {
        Windows.Internal.ICustomDialogWindowRequestPriv RequestDialogWindow(String dialogType, String title, UInt32 invokingWindow, UInt32 connectCookie, UInt32 componentPid, Windows.Foundation.Size requestedSize, Windows.Foundation.EventHandler <Boolean>  windowClosedHandler, UInt64 lifetimeMonitorHandle);
    };


    [contract(Windows.Internal.InternalContract, 1)]
    [static_name("Windows.Internal.ICustomSystemDialogWindowManagerStatics", 0f246b46-807a-459a-93a2-7e906089c013)]
    [interface_name("Windows.Internal.ICustomSystemDialogWindowManager", 73efe9ff-8773-42f5-b28b-8caf30c86a2c)]
    runtimeclass CustomSystemDialogWindowManager
    {
        static Windows.Internal.CustomSystemDialogWindowManager GetForCurrentView();
        event Windows.Foundation.TypedEventHandler <Windows.Internal.CustomSystemDialogWindowManager, Windows.Internal.CustomDialogWindowRequest>  CustomDialogWindowRequested;
    }


}
