






namespace Windows.UI.Input
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum EdgeGestureKind
    {
        Touch,
        Keyboard,
        Mouse,
    };


    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.UI.Input.IEdgeGestureEventArgs", 44fa4a24-2d09-42e1-8b5e-368208796a4c)]
    runtimeclass EdgeGestureEventArgs
    {
        Windows.UI.Input.EdgeGestureKind Kind{ get; };
    }


    [muse(0x6020000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(standard)]
    [static_name("Windows.UI.Input.IEdgeGestureStatics", bc6a8519-18ee-4043-9839-4fc584d60a14)]
    [interface_name("Windows.UI.Input.IEdgeGesture", 580d5292-2ab1-49aa-a7f0-33bd3f8df9f1)]
    [threading(sta)]
    runtimeclass EdgeGesture
    {
        static Windows.UI.Input.EdgeGesture GetForCurrentView();
        event Windows.Foundation.TypedEventHandler <Windows.UI.Input.EdgeGesture, Windows.UI.Input.EdgeGestureEventArgs>  Starting;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Input.EdgeGesture, Windows.UI.Input.EdgeGestureEventArgs>  Completed;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Input.EdgeGesture, Windows.UI.Input.EdgeGestureEventArgs>  Canceled;
    }


}
