






namespace Windows.Graphics.Imaging
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum BitmapPixelFormat
    {
        Unknown,
        Rgba16 = 12,
        Rgba8 = 30,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Gray16 = 57,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Gray8 = 62,
        Bgra8 = 87,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Nv12 = 103,
        [contract(Windows.Foundation.UniversalApiContract, 6)]
        P010,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Yuy2 = 107,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum BitmapAlphaMode
    {
        Premultiplied,
        Straight,
        Ignore,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    struct BitmapBounds
    {
        UInt32 X;
        UInt32 Y;
        UInt32 Width;
        UInt32 Height;
    };

}
