









namespace Windows.UI.ViewManagement
{
    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.UI.ViewManagement.IInputPaneVisibilityEventArgs", d243e016-d907-4fcc-bb8d-f77baa5028f1)]
    runtimeclass InputPaneVisibilityEventArgs
    {
        Windows.Foundation.Rect OccludedRect{ get; };
        Boolean EnsuredFocusedElementInView{ set; };
        Boolean EnsuredFocusedElementInView{ get; };
    }


    [muse(0x6020000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000002)]
    [marshaling_behavior(standard)]
    [static_name("Windows.UI.ViewManagement.IInputPaneStatics", 95f4af3a-ef47-424a-9741-fd2815eba2bd)]
    [interface_name("Windows.UI.ViewManagement.IInputPane", 640ada70-06f3-4c87-a678-9829c9127c28)]
    runtimeclass InputPane
    {
        static Windows.UI.ViewManagement.InputPane GetForCurrentView();

        [contract(Windows.Foundation.UniversalApiContract, 8)]
        [feature(Velocity_AlwaysAlwaysEnabled)]
        [static_name("Windows.UI.ViewManagement.IInputPaneStatics2", 1b63529b-d9ec-4531-8445-71bab9fb828e)]
        {
            static Windows.UI.ViewManagement.InputPane GetForUIContext(Windows.UI.UIContext context);
        }
        event Windows.Foundation.TypedEventHandler <Windows.UI.ViewManagement.InputPane, Windows.UI.ViewManagement.InputPaneVisibilityEventArgs>  Showing;
        event Windows.Foundation.TypedEventHandler <Windows.UI.ViewManagement.InputPane, Windows.UI.ViewManagement.InputPaneVisibilityEventArgs>  Hiding;
        Windows.Foundation.Rect OccludedRect{ get; };

        [contract(Windows.Foundation.UniversalApiContract, 1)]
        [interface_name("Windows.UI.ViewManagement.IInputPane2", 8a6b3f26-7090-4793-944c-c3f2cde26276)]
        {
            Boolean TryShow();
            Boolean TryHide();
        }

        [contract(Windows.Foundation.UniversalApiContract, 1)]
        [interface_name("Windows.UI.ViewManagement.IInputPaneControl", 088bb24f-962f-489d-aa6e-c6be1a0a6e52)]
        {
            Boolean Visible{ get; };
            Boolean Visible{ set; };
        }
    }





}
