







namespace Windows.UI.StartScreen
{
    [contract(Windows.Foundation.UniversalApiContract, 2)]
    enum JumpListSystemGroupKind
    {
        None,
        Frequent,
        Recent,
    };

    [contract(Windows.Foundation.UniversalApiContract, 2)]
    enum JumpListItemKind
    {
        Arguments,
        Separator,
    };



    [contract(Windows.Foundation.UniversalApiContract, 2)]
    [marshaling_behavior(agile)]
    [static_name("Windows.UI.StartScreen.IJumpListItemStatics", f1bfc4e8-c7aa-49cb-8dde-ecfccd7ad7e4)]
    [interface_name("Windows.UI.StartScreen.IJumpListItem", 7adb6717-8b5d-4820-995b-9b418dbe48b0)]
    runtimeclass JumpListItem
    {
        static Windows.UI.StartScreen.JumpListItem CreateWithArguments(String arguments, String displayName);
        static Windows.UI.StartScreen.JumpListItem CreateSeparator();
        Windows.UI.StartScreen.JumpListItemKind Kind{ get; };
        String Arguments{ get; };
        Boolean RemovedByUser{ get; };
        String Description{ get; };
        String Description{ set; };
        String DisplayName{ get; };
        String DisplayName{ set; };
        String GroupName{ get; };
        String GroupName{ set; };
        Windows.Foundation.Uri Logo{ get; };
        Windows.Foundation.Uri Logo{ set; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 2)]
    [marshaling_behavior(agile)]
    [static_name("Windows.UI.StartScreen.IJumpListStatics", a7e0c681-e67e-4b74-8250-3f322c4d92c3)]
    [interface_name("Windows.UI.StartScreen.IJumpList", b0234c3e-cd6f-4cb6-a611-61fd505f3ed1)]
    runtimeclass JumpList
    {
        static Windows.Foundation.IAsyncOperation <Windows.UI.StartScreen.JumpList>  LoadCurrentAsync();
        static Boolean IsSupported();
        Windows.Foundation.Collections.IVector <Windows.UI.StartScreen.JumpListItem>  Items{ get; };
        Windows.UI.StartScreen.JumpListSystemGroupKind SystemGroupKind{ get; };
        Windows.UI.StartScreen.JumpListSystemGroupKind SystemGroupKind{ set; };
        Windows.Foundation.IAsyncAction SaveAsync();
    }

}
