








namespace Windows.Internal.UI.StartScreen
{
    [contractversion(1)]
    [internal]
    apicontract JumpListPrivateContract{};

    [contract(Windows.Internal.UI.StartScreen.JumpListPrivateContract, 1)]
    [uuid(380e5375-4d19-4e0e-979b-c61571fb5f8d)]
    interface IJumpListSerializationStatics
    {
        Windows.UI.StartScreen.JumpList Deserialize(String jumpListJson);
    };

    [uuid(fa29c8a5-125f-4162-806b-3a7ffdb40eed)]
    [contract(Windows.Internal.UI.StartScreen.JumpListPrivateContract, 1)]
    interface IJumpListSerialization
    {
        String Serialize();
    };

    [uuid(64384f1c-d1b5-43eb-a2b3-2befbde9a7a2)]
    [contract(Windows.Internal.UI.StartScreen.JumpListPrivateContract, 1)]
    interface IJumpListItemPrivate
    {
        void SetRemovedByUser(Boolean value);
    };

    [uuid(5a8d03ba-b9c5-49ce-9af4-7167904e7d3c)]
    [contract(Windows.Internal.UI.StartScreen.JumpListPrivateContract, 1)]
    interface IJumpListItemSerializationStatics
    {
        Windows.UI.StartScreen.JumpListItem Deserialize(Windows.Data.Json.JsonObject jumpListItemJsonObject);
    };

    [uuid(1ee2e7e7-4307-4c74-a6f4-bc9d41f8bf1c)]
    [contract(Windows.Internal.UI.StartScreen.JumpListPrivateContract, 1)]
    interface IJumpListItemSerialization
    {
        Windows.Data.Json.JsonObject Serialize();
    };



    [contract(Windows.Internal.UI.StartScreen.JumpListPrivateContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Internal.UI.StartScreen.IJumpListBrokeredStatics", 4a35d108-6b22-4d9f-be4f-66f682062751)]
    [interface_name("Windows.Internal.UI.StartScreen.IJumpListBrokered", dbcb3ef5-c950-4e55-8c56-108bf02e7b72)]
    runtimeclass JumpListBrokered
    {
        [return_name("result")] static Windows.Internal.UI.StartScreen.JumpListBrokered LoadCurrent(out String serializedJumpList);
        void Save(String jumpListJson);
    }

}
