







namespace Windows.UI.Internal.Popups
{
    [contractversion(1)]
    [internal]
    apicontract MessageDialogInternalContract{};

    [contract(Windows.UI.Internal.Popups.MessageDialogInternalContract, 1)]
    [uuid(b83e0e2f-5dfd-4492-acb4-e96c848b6fab)]
    interface IMessageDialogFactoryWithOwnerWindow
    {
        Windows.UI.Popups.MessageDialog CreateForWindow(UInt32 ownerWindow, String content, String title);
    };

}
