









namespace Windows.Internal.Shell.ModalShareHost
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Internal.Shell.ModalShareHost.InternalContract, 1)]
    [uuid(a88145b2-eccf-455d-8428-830fbb324304)]
    interface ISharePickerLaunchActivatedEventArgs requires Windows.ApplicationModel.Activation.ILaunchActivatedEventArgs, Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
        Windows.ApplicationModel.Internal.DataTransfer.ISharingOperation SharingOperation{ get; };
        Windows.Internal.Shell.Share.IShareExperienceCallbacks ShareExperienceCallbacks{ get; };
        String CorrelationVector{ get; };
    };

    [contract(Windows.Internal.Shell.ModalShareHost.InternalContract, 1)]
    [marshaling_behavior(agile)]
    runtimeclass SharePickerLaunchActivatedEventArgs
        : [default]Windows.Internal.Shell.ModalShareHost.ISharePickerLaunchActivatedEventArgs
        , Windows.ApplicationModel.Activation.ILaunchActivatedEventArgs
        , Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
    }

}
