






namespace Windows.Management.Deployment.Preview
{
    [contractversion(1)]
    apicontract DeploymentPreviewContract{};


    [dualapipartition(0xa000000)]
    [contract(Windows.Management.Deployment.Preview.DeploymentPreviewContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Management.Deployment.Preview.IInstalledClassicAppInfo", 0a7d3da3-65d0-4086-80d6-0610d760207d)]
    runtimeclass InstalledClassicAppInfo
    {
        String DisplayName{ get; };
        String DisplayVersion{ get; };
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Management.Deployment.Preview.DeploymentPreviewContract, 1)]
    [static_name("Windows.Management.Deployment.Preview.IClassicAppManagerStatics", e2fad668-882c-4f33-b035-0df7b90d67e6)]
    [threading(both)]
    runtimeclass ClassicAppManager
    {
        static Windows.Management.Deployment.Preview.InstalledClassicAppInfo FindInstalledApp(String appUninstallKey);
    }

}
