







namespace Windows.Internal.PlatformExtensions
{
    [contract(Windows.Internal.PlatformExtensions.InternalContract, 1)]
    enum ProjectionTaskType
    {
        StartProjecting,
        SwapDisplays,
        StopProjecting,
        Validate,
    };

    [contract(Windows.Internal.PlatformExtensions.InternalContract, 1)]
    [uuid(01bda893-f5fc-46d0-aa5e-3688b2289f05)]
    interface IProjectionManagerContract
    {
        void ExecuteProjectionTask(ProjectionTaskType tasktype, Windows.Internal.ApplicationModel.WindowManagement.WindowId targetAppViewId, Windows.Internal.ApplicationModel.WindowManagement.WindowId anchorAppViewId, String displayInstanceId, String AEPDeviceIdToDisconnect);
    };

}
