







namespace Windows.Storage.Streams
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [uuid(33ee3134-1dd6-4e3a-8067-d1c162e8642b)]
    interface IRandomAccessStreamReference
    {
        Windows.Foundation.IAsyncOperation <Windows.Storage.Streams.IRandomAccessStreamWithContentType>  OpenReadAsync();
    };

}
