









namespace Windows.System.RemoteDesktop.Input
{
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    enum RemoteDesktopTouchState
    {
        Released,
        Pressed,
    };

    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    enum RemoteDesktopButtonState
    {
        Released,
        Pressed,
    };

    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [flags]
    [feature(Velocity_SometimesAlwaysDisabled)]
    enum RemoteDesktopMouseButton
    {
        Left = 1,
        Middle,
        Right = 4,
        X1 = 8,
        X2 = 16,
    };

    [feature(Velocity_SometimesAlwaysDisabled)]
    [flags]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    enum RemoteDesktopKeyboardLockState
    {
        ScrollLockOn = 1,
        NumLockOn,
        CapsLockOn = 4,
        KanaLockOn = 8,
    };


    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopAvailableTouchPointsChangedEventArgs", c15bbdb8-8403-5ea6-94b3-102aac83efa2)]
    runtimeclass RemoteDesktopAvailableTouchPointsChangedEventArgs
    {
        Boolean MultitouchEnabled{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopMousePointer", 37f27227-34b4-5639-a138-dfe1eff0de11)]
    runtimeclass RemoteDesktopMousePointer
    {
        Windows.Graphics.Imaging.SoftwareBitmap Bitmap{ get; };
        Windows.Foundation.Point Hotspot{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopMousePointerShapeChangedEventArgs", dd0b7fa9-7c54-5065-b200-5dbe93fd566a)]
    runtimeclass RemoteDesktopMousePointerShapeChangedEventArgs
    {
        Windows.System.RemoteDesktop.Input.RemoteDesktopMousePointer MousePointerShape{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [interface_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopMousePointerVisibilityChangedEventArgs", 2ba639dd-4ac0-5318-87d4-261eb907a6c8)]
    runtimeclass RemoteDesktopMousePointerVisibilityChangedEventArgs
    {
        Boolean IsVisible{ get; };
    }


    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopMousePositionChangedEventArgs", c487a5ff-434a-532e-84db-4a131fb34185)]
    runtimeclass RemoteDesktopMousePositionChangedEventArgs
    {
        Windows.Foundation.Point MouseCursorPosition{ get; };
    }




    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [static_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopConnectionInputStatics", 3164ac3e-3024-513b-9bfa-9d699d240c33)]
    [interface_name("Windows.System.RemoteDesktop.Input.IRemoteDesktopConnectionInput", d9e05249-d04b-5687-9701-078148ef25f3)]
    [threading(both)]
    runtimeclass RemoteDesktopConnectionInput
    {
        static UInt32 TranslateToScanCode(Windows.System.VirtualKey vKey, UInt16 languageIdentifier, UInt16 keyboardIdentifier);
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.Input.RemoteDesktopAvailableTouchPointsChangedEventArgs>  AvailableTouchPointsChanged;
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.Input.RemoteDesktopMousePointerShapeChangedEventArgs>  MousePointerShapeChanged;
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.Input.RemoteDesktopMousePointerVisibilityChangedEventArgs>  MousePointerVisibilityChanged;
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.Input.RemoteDesktopMousePositionChangedEventArgs>  MousePositionChanged;
        Windows.System.RemoteDesktop.Input.RemoteDesktopMousePointer MousePointerShape{ get; };
        Boolean SupportsScancode{ get; };
        Boolean SupportsUnicode{ get; };
        void ResetKeyboardAndMouseState(RemoteDesktopKeyboardLockState keyboardLockState);
        void RequestInputLocale(UInt16 languageIdentifier, UInt16 keyboardIdentifier);
        void SendMouseButtonState(Windows.Foundation.Point position, RemoteDesktopMouseButton mouseButton, RemoteDesktopButtonState mouseState);
        void SendMouseMove(Windows.Foundation.Point position);
        void SendMouseWheel(Int32 horizontalRotationDelta, Int32 verticalRotationDelta);
        Boolean MultitouchSupported{ get; };
        UInt32 MaxSupportedTouchPoints{ get; };
        void SendTouchState(RemoteDesktopTouchState state, UInt32 contactId, Windows.Foundation.Point position, UInt64 timestamp, UInt16 touchForce);
        void SendTouchMove(UInt32 contactId, Windows.Foundation.Point position, UInt64 timestamp, UInt16 touchForce);
        void SendKeyStatusAsScanCode(Windows.UI.Core.CorePhysicalKeyStatus keyStatus);
        void SendUnicode(Int32 unicode, RemoteDesktopButtonState keyState);
    }

}
