







namespace Windows.System.RemoteDesktop
{
    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    enum StreamState
    {
        Invalid = 1,
        Created,
        OpenCalled,
        Opened,
        Closed,
    };



    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [constructor_name("Windows.System.RemoteDesktop.IAsyncTransportInBufferFactory", 064641b6-1089-58c3-a04f-7e68c58eeee6)]
    [interface_name("Windows.System.RemoteDesktop.IAsyncTransportInBuffer", d15a7f17-5cb5-5aa0-9195-facdb689843e)]
    [threading(both)]
    runtimeclass AsyncTransportInBuffer
    {
        [method_name( "CreateInstance" )] AsyncTransportInBuffer(UInt32 length);
        Windows.System.RemoteDesktop.ContinuousBuffer Data{ get; };
        Object InIoDescriptor{ get; };
    }


    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.System.RemoteDesktop.IAsyncTransportOutBuffer", ba0f060d-a6ff-55b7-a132-1f2bf42b73d8)]
    runtimeclass AsyncTransportOutBuffer
    {
        Windows.System.RemoteDesktop.SegmentedBuffer Data{ get; };
        Object OutIoDescriptor{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [default_interface]
    [interface_name("Windows.System.RemoteDesktop.IAsyncTransportOpenedEventArgs", c350d276-5684-59d2-8650-b266e0e37cb6)]
    [threading(both)]
    runtimeclass AsyncTransportOpenedEventArgs
    {
        AsyncTransportOpenedEventArgs();
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [default_interface]
    [interface_name("Windows.System.RemoteDesktop.IAsyncTransportClosedEventArgs", 96a7b77f-9fc8-56af-9f34-96b01037536f)]
    [threading(both)]
    runtimeclass AsyncTransportClosedEventArgs
    {
        AsyncTransportClosedEventArgs();
    }



    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [constructor_name("Windows.System.RemoteDesktop.IAsyncTransportDataReceivedEventArgsFactory", 1341f71d-987a-55d9-8e6f-13619fbdc22d)]
    [interface_name("Windows.System.RemoteDesktop.IAsyncTransportDataReceivedEventArgs", db28b277-1fa7-54d5-aabd-0836baf8afdc)]
    [threading(both)]
    runtimeclass AsyncTransportDataReceivedEventArgs
    {
        [method_name( "CreateInstance" )] AsyncTransportDataReceivedEventArgs(AsyncTransportInBuffer inBuffer);
        Windows.System.RemoteDesktop.AsyncTransportInBuffer InBuffer{ get; };
    }

    [feature(Velocity_SometimesAlwaysDisabled)]
    [uuid(9de0b2ed-a822-5b76-8b36-36156922aa29)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    interface IAsyncTransport
    {
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.AsyncTransportOpenedEventArgs>  Opened;
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.AsyncTransportClosedEventArgs>  Closed;
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.AsyncTransportDataReceivedEventArgs>  DataReceived;
        void Open();
        void Close();
        void QueueWrite(AsyncTransportOutBuffer sendData);
        Windows.System.RemoteDesktop.StreamState State{ get; };
    };

}
