





namespace Windows.Internal.System.RemoteDesktop
{
    [contractversion(1)]
    [internal]
    apicontract RdWinRTInternalContract2{};

    [contract(Windows.Internal.System.RemoteDesktop.RdWinRTInternalContract2, 1)]
    enum RemoteDesktopTransportType
    {
        Tcp,
        NamedPipe,
        WebSocket,
    };


    [contract(Windows.Internal.System.RemoteDesktop.RdWinRTInternalContract2, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.System.RemoteDesktop.IRemoteDesktopConnectionSettingsEx", 4d924780-3c6d-5774-981a-86f52233bdf4)]
    [threading(both)]
    runtimeclass RemoteDesktopConnectionSettingsEx
    {
        RemoteDesktopConnectionSettingsEx();
        Windows.Internal.System.RemoteDesktop.RemoteDesktopTransportType TransportType{ get; };
        Windows.Internal.System.RemoteDesktop.RemoteDesktopTransportType TransportType{ set; };
        String ConnectionUri{ get; };
        String ConnectionUri{ set; };
    }



    [marshaling_behavior(agile)]
    [contract(Windows.Internal.System.RemoteDesktop.RdWinRTInternalContract2, 1)]
    [static_name("Windows.Internal.System.RemoteDesktop.IInternalRemoteDesktopConnectionFactoryStatics", abf36091-113b-5e27-8810-3cf4c042a167)]
    [default_interface]
    [interface_name("Windows.Internal.System.RemoteDesktop.IInternalRemoteDesktopConnectionFactory", 0f86ed63-b83f-5032-9844-5922aa5ca941)]
    [threading(both)]
    runtimeclass InternalRemoteDesktopConnectionFactory
    {
        static Object CreateConnectionUsingNamedPipeTransport(Object connectionSettings, UInt64 namedPipeHandle);
        static Object CreateConnectionUsingBuiltInTransport(Object connectionSettings, RemoteDesktopConnectionSettingsEx connectionSettingsEx);
    }

}
