







namespace Windows.System.RemoteDesktop
{
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    enum RemoteDesktopVirtualChannelState
    {
        Invalid = 1,
        Created,
        Opened,
        Closed,
    };


    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.System.RemoteDesktop.IRemoteDesktopChannelClosedEventArgs", 31b17a7c-692b-5840-bec3-f9dfeaf9d07d)]
    runtimeclass RemoteDesktopChannelClosedEventArgs
    {
        UInt32 ErrorCode{ get; };
    }


    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.RemoteDesktop.IRemoteDesktopDataReceivedEventArgs", ebeecab4-be71-5fb3-8da7-3abf1c668c5c)]
    runtimeclass RemoteDesktopDataReceivedEventArgs
    {
        Windows.System.RemoteDesktop.ContinuousBuffer ReceiveBuffer{ get; };
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.System.RemoteDesktop.IRemoteDesktopDataWrittenResult", 23205605-a786-5d2c-b4de-48552b9f8f1b)]
    runtimeclass RemoteDesktopDataWrittenResult
    {
        Windows.System.RemoteDesktop.ContinuousBuffer WriteBuffer{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.RemoteDesktop.IVirtualChannel", 2ccbde7d-4e3c-5c16-b515-dfd271be449d)]
    runtimeclass VirtualChannel
    {
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.RemoteDesktopChannelClosedEventArgs>  ChannelClosed;
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.RemoteDesktopDataReceivedEventArgs>  DataReceived;
        Windows.System.RemoteDesktop.RemoteDesktopVirtualChannelState State{ get; };
        String ChannelName{ get; };
        void Close();
        Windows.Foundation.IAsyncOperation <Windows.System.RemoteDesktop.RemoteDesktopDataWrittenResult>  WriteAsync(ContinuousBuffer sendData);
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.System.RemoteDesktop.IRemoteDesktopChannelOpenedEventArgs", ff43799c-68f1-525c-a45b-4de3d11961fc)]
    runtimeclass RemoteDesktopChannelOpenedEventArgs
    {
        Windows.System.RemoteDesktop.VirtualChannel Channel{ get; };
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_SometimesAlwaysDisabled)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.System.RemoteDesktop.IVirtualChannels", c6f154cf-6a71-5cb8-b5f2-9005fa0604a3)]
    runtimeclass VirtualChannels
    {
        event Windows.Foundation.EventHandler <Windows.System.RemoteDesktop.RemoteDesktopChannelOpenedEventArgs>  ChannelOpened;
        void RegisterDynamicVirtualChannel(String channelName);
    }

}
