







namespace Windows.Internal.UI.StartScreen
{
    [contractversion(1)]
    [internal]
    apicontract SecondaryTilePrivateContract{};

    [contract(Windows.Internal.UI.StartScreen.SecondaryTilePrivateContract, 1)]
    [flags]
    enum SecondaryTileCreationBehaviors
    {
        None,
        SuppressPinToStart,
        SuppressBackgroundPolicyCheck,
        SuppressPinRequest = 4,
    };

    [contract(Windows.Internal.UI.StartScreen.SecondaryTilePrivateContract, 1)]
    [uuid(2d7f0d3b-ec36-463b-9f69-d7238d77c122)]
    interface ISecondaryTilePrivate
    {
        void PopulateIdentity(String hstrAUMID);
        void SetTileCreationBehaviors(SecondaryTileCreationBehaviors creationBehaviors);
        void RefreshPropertiesFromPrimaryTile();
        void GetUniqueId(out Guid uniqueId);
        void GetDefaultTileSize(out Windows.UI.StartScreen.TileSize tileSize);
        void GetAppUserModelId(out String appUserModelId);
        void ValidatePropertiesForCreate();
        void CreateInTileStore();
    };

    [contract(Windows.Internal.UI.StartScreen.SecondaryTilePrivateContract, 1)]
    [uuid(5365d67e-eedb-4ecd-a099-a195558a9f80)]
    interface ISecondaryTileStaticsPrivate
    {
        Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.UI.StartScreen.SecondaryTile> >  FindAllForAUMIDAsync(String hstrAUMID);
        Windows.Foundation.IAsyncOperation <Boolean>  DeleteAsync(String aumid, String tileId);
        void Delete(String aumid, String tileId);
        void DeleteIfNotPinned(String aumid, String tileId);
        Windows.Foundation.IAsyncOperation <Boolean>  DeleteIfNotPinnedAsync(String aumid, String tileId);
    };

}
