










namespace Windows.ApplicationModel.SocialInfo
{
    [contractversion(2)]
    apicontract SocialInfoContract{};

    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [deprecated("SocialItemBadgeStyle is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    enum SocialItemBadgeStyle
    {
        Hidden,
        Visible,
        VisibleWithCount,
    };

    [deprecated("SocialFeedKind is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    enum SocialFeedKind
    {
        HomeFeed,
        ContactFeed,
        Dashboard,
    };

    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [deprecated("SocialFeedItemStyle is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    enum SocialFeedItemStyle
    {
        Default,
        Photo,
    };

    [deprecated("SocialFeedUpdateMode is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    enum SocialFeedUpdateMode
    {
        Append,
        Replace,
    };





    [marshaling_behavior(agile)]
    [deprecated("SocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [interface_name("Windows.ApplicationModel.SocialInfo.ISocialUserInfo", 9e5e1bd1-90d0-4e1d-9554-844d46607f61)]
    runtimeclass SocialUserInfo
    {
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String DisplayName{ get; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String DisplayName{ set; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String UserName{ get; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String UserName{ set; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String RemoteId{ get; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String RemoteId{ set; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialUserInfo is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
    }

    [deprecated("SocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.SocialInfo.ISocialFeedContent", a234e429-3e39-494d-a37c-f462a2494514)]
    runtimeclass SocialFeedContent
    {
        [deprecated("ISocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String Title{ get; };
        [deprecated("ISocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String Title{ set; };
        [deprecated("ISocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String Message{ get; };
        [deprecated("ISocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String Message{ set; };
        [deprecated("ISocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialFeedContent is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
    }

    [marshaling_behavior(agile)]
    [deprecated("SocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [interface_name("Windows.ApplicationModel.SocialInfo.ISocialItemThumbnail", 5cbf831a-3f08-497f-917f-57e09d84b141)]
    [threading(both)]
    runtimeclass SocialItemThumbnail
    {
        SocialItemThumbnail();
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri ImageUri{ get; };
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri ImageUri{ set; };
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Graphics.Imaging.BitmapSize BitmapSize{ get; };
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Graphics.Imaging.BitmapSize BitmapSize{ set; };
        [deprecated("ISocialItemThumbnail is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.IAsyncAction SetImageAsync(Windows.Storage.Streams.IInputStream image);
    }

    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [deprecated("SocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.SocialInfo.ISocialFeedSharedItem", 7bfb9e40-a6aa-45a7-9ff6-54c42105dd1f)]
    [threading(both)]
    runtimeclass SocialFeedSharedItem
    {
        SocialFeedSharedItem();
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri OriginalSource{ get; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri OriginalSource{ set; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedContent Content{ get; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ get; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ set; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialItemThumbnail Thumbnail{ set; };
        [deprecated("ISocialFeedSharedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialItemThumbnail Thumbnail{ get; };
    }

    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("SocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [interface_name("Windows.ApplicationModel.SocialInfo.ISocialFeedChildItem", 0b6a985a-d59d-40be-980c-488a2ab30a83)]
    [threading(both)]
    runtimeclass SocialFeedChildItem
    {
        SocialFeedChildItem();
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialUserInfo Author{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedContent PrimaryContent{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedContent SecondaryContent{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ set; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Collections.IVector <Windows.ApplicationModel.SocialInfo.SocialItemThumbnail>  Thumbnails{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedSharedItem SharedItem{ get; };
        [deprecated("ISocialFeedChildItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedSharedItem SharedItem{ set; };
    }




    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("SocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [interface_name("Windows.ApplicationModel.SocialInfo.ISocialFeedItem", 4f1392ab-1f72-4d33-b695-de3e1db60317)]
    [threading(both)]
    runtimeclass SocialFeedItem
    {
        SocialFeedItem();
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialUserInfo Author{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedContent PrimaryContent{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedContent SecondaryContent{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Collections.IVector <Windows.ApplicationModel.SocialInfo.SocialItemThumbnail>  Thumbnails{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedSharedItem SharedItem{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedSharedItem SharedItem{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialItemBadgeStyle BadgeStyle{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialItemBadgeStyle BadgeStyle{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Int32 BadgeCountValue{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Int32 BadgeCountValue{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String RemoteId{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String RemoteId{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedChildItem ChildItem{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedChildItem ChildItem{ set; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedItemStyle Style{ get; };
        [deprecated("ISocialFeedItem is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedItemStyle Style{ set; };
    }



}
namespace Windows.ApplicationModel.SocialInfo.Provider
{
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("SocialFeedUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [interface_name("Windows.ApplicationModel.SocialInfo.Provider.ISocialFeedUpdater", 7a0c0aa7-ed89-4bd5-a8d9-15f4d9861c10)]
    runtimeclass SocialFeedUpdater
    {
        [deprecated("ISocialFeedUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String OwnerRemoteId{ get; };
        [deprecated("ISocialFeedUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedKind Kind{ get; };
        [deprecated("ISocialFeedUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Collections.IVector <Windows.ApplicationModel.SocialInfo.SocialFeedItem>  Items{ get; };
        [deprecated("ISocialFeedUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.IAsyncAction CommitAsync();
    }

    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [deprecated("SocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.SocialInfo.Provider.ISocialDashboardItemUpdater", 3cde9dc9-4800-46cd-869b-1973ec685bde)]
    runtimeclass SocialDashboardItemUpdater
    {
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        String OwnerRemoteId{ get; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialFeedContent Content{ get; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ get; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.DateTime Timestamp{ set; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialItemThumbnail Thumbnail{ set; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.ApplicationModel.SocialInfo.SocialItemThumbnail Thumbnail{ get; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.IAsyncAction CommitAsync();
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ get; };
        [deprecated("ISocialDashboardItemUpdater is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        Windows.Foundation.Uri TargetUri{ set; };
    }

    [deprecated("SocialInfoProviderManager is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
    [marshaling_behavior(agile)]
    [contract(Windows.ApplicationModel.SocialInfo.SocialInfoContract, 1)]
    [static_name("Windows.ApplicationModel.SocialInfo.Provider.ISocialInfoProviderManagerStatics", 1b88e52b-7787-48d6-aa12-d8e8f47ab85a)]
    [threading(both)]
    runtimeclass SocialInfoProviderManager
    {
        [deprecated("ISocialInfoProviderManagerStatics is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        static Windows.Foundation.IAsyncOperation <Windows.ApplicationModel.SocialInfo.Provider.SocialFeedUpdater>  CreateSocialFeedUpdaterAsync(Windows.ApplicationModel.SocialInfo.SocialFeedKind kind, Windows.ApplicationModel.SocialInfo.SocialFeedUpdateMode mode, String ownerRemoteId);
        [deprecated("ISocialInfoProviderManagerStatics is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        static Windows.Foundation.IAsyncOperation <Windows.ApplicationModel.SocialInfo.Provider.SocialDashboardItemUpdater>  CreateDashboardItemUpdaterAsync(String ownerRemoteId);
        [deprecated("ISocialInfoProviderManagerStatics is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        static void UpdateBadgeCountValue(String itemRemoteId, Int32 newCount);
        [deprecated("ISocialInfoProviderManagerStatics is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        static void ReportNewContentAvailable(String contactRemoteId, Windows.ApplicationModel.SocialInfo.SocialFeedKind kind);
        [deprecated("ISocialInfoProviderManagerStatics is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        static Windows.Foundation.IAsyncOperation <Boolean>  ProvisionAsync();
        [deprecated("ISocialInfoProviderManagerStatics is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.ApplicationModel.SocialInfo.SocialInfoContract, 0x20000)]
        static Windows.Foundation.IAsyncAction DeprovisionAsync();
    }

}
