









namespace Windows.Storage.Provider
{
    [dualapipartition(0xa000004)]
    [marshaling_behavior(agile)]
    [contract(Windows.Storage.Provider.CloudFilesContract, 1)]
    [interface_name("Windows.Storage.Provider.IStorageProviderItemProperty", 476cb558-730b-4188-b7b5-63b716ed476d)]
    [threading(both)]
    runtimeclass StorageProviderItemProperty
    {
        StorageProviderItemProperty();
        Int32 Id{ set; };
        Int32 Id{ get; };
        String Value{ set; };
        String Value{ get; };
        String IconResource{ set; };
        String IconResource{ get; };
    }


    [dualapipartition(0xa000004)]
    [contract(Windows.Storage.Provider.CloudFilesContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Storage.Provider.IStorageProviderItemPropertiesStatics", 2d2c1c97-2704-4729-8fa9-7e6b8e158c2f)]
    [threading(both)]
    runtimeclass StorageProviderItemProperties
    {
        static Windows.Foundation.IAsyncAction SetAsync(Windows.Storage.IStorageItem item, Windows.Foundation.Collections.IIterable <Windows.Storage.Provider.StorageProviderItemProperty>  itemProperties);
    }

    [uuid(8f6f9c3e-f632-4a9b-8d99-d2d7a11df56a)]
    [contract(Windows.Storage.Provider.CloudFilesContract, 1)]
    interface IStorageProviderItemPropertySource
    {
        Windows.Foundation.Collections.IIterable <Windows.Storage.Provider.StorageProviderItemProperty>  GetItemProperties(String itemPath);
    };

}
