








namespace Windows.System.Profile
{
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    enum SystemIdentificationSource
    {
        None,
        Tpm,
        Uefi,
        [contract(Windows.Foundation.UniversalApiContract, 5)]
        Registry,
    };


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [interface_name("Windows.System.Profile.ISystemIdentificationInfo", 0c659e7d-c3c2-4d33-a2df-21bc41916eb3)]
    runtimeclass SystemIdentificationInfo
    {
        Windows.Storage.Streams.IBuffer Id{ get; };
        Windows.System.Profile.SystemIdentificationSource Source{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [marshaling_behavior(agile)]
    [static_name("Windows.System.Profile.ISystemIdentificationStatics", 5581f42a-d3df-4d93-a37d-c41a616c6d01)]
    [threading(both)]
    runtimeclass SystemIdentification
    {
        static Windows.System.Profile.SystemIdentificationInfo GetSystemIdForPublisher();
        static Windows.System.Profile.SystemIdentificationInfo GetSystemIdForUser(Windows.System.User user);
    }

}
