










namespace Windows.Internal.ComposableShell.Tabs
{
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    enum ViewCommand
    {
        None,
        Minimize,
        Maximize,
        Restore,
        CloseGroup,
        EnterFullScreen,
        ExitFullScreen,
        SetForeground,
        ToggleVerticalMaximize,
        SwitchToTitleBar,
        Duplicate,
    };

    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    enum RelativeTabPosition
    {
        None,
        Next,
        Previous,
        First,
        Last,
    };


    [marshaling_behavior(agile)]
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerEventArgs", 6e401180-e040-4afe-b3fc-f4b0544de9c2)]
    runtimeclass TabControllerEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerCancellableEventArgs", 4b33d9f2-8ad5-4273-ab8c-88c490e614c2)]
    runtimeclass TabControllerCancellableEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
        Boolean Cancel{ get; };
        Boolean Cancel{ set; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerViewEventArgs", 04d2940c-9e4f-4202-ace0-789f631b6832)]
    runtimeclass TabControllerViewEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
        Windows.Internal.ComposableShell.Tabs.ViewCommand Command{ get; };
    }


    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerCloseTabGroupRequestedEventArgs", f686449b-fe9e-4648-985b-d252b237624d)]
    runtimeclass TabControllerCloseTabGroupRequestedEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTabGroup Group{ get; };
        Windows.Foundation.Collections.IVectorView <Windows.Internal.ComposableShell.Tabs.ShellTab>  Tabs{ get; };
    }


    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerThumbnailEventArgs", 9d35a4f3-974f-4f61-bb1d-1789169adaf5)]
    runtimeclass TabControllerThumbnailEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
        Windows.UI.Composition.Compositor Compositor{ get; };
        Windows.Internal.ApplicationModel.WindowManagement.WindowId HostWindowId{ get; };
        Windows.Foundation.Size Size{ get; };
        UInt64 ThumbnailHandle{ get; };
        UInt64 ThumbnailHandle{ set; };
        Windows.UI.Composition.Visual Visual{ get; };
        Windows.UI.Composition.Visual Visual{ set; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabThumbnail", 0ca9c442-5bb3-476f-ab4e-a60b8f12d768)]
    runtimeclass TabThumbnail
    {
        UInt64 ThumbnailHandle{ get; };
        Windows.UI.Composition.Visual Visual{ get; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerMenuItemsRequestedEventArgs", ec4df49a-8462-40d1-b5fb-3539dd2fef41)]
    runtimeclass TabControllerMenuItemsRequestedEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
        Windows.Foundation.Collections.IVector <Windows.Internal.ComposableShell.Tabs.ShellTabCommand>  MenuItems{ get; };
    }


    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabControllerRectEventArgs", 27cd79fb-36dc-4c18-91d3-b3078fbe71ea)]
    runtimeclass TabControllerRectEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
        Windows.Foundation.Rect Rect{ get; };
        Windows.Foundation.Rect Rect{ set; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [static_name("Windows.Internal.ComposableShell.Tabs.ITabControllerStatics", d74258ce-e073-45e7-958b-0efa76c85903)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabController", 947c042a-0955-4e95-b853-d3c1877d5ef2)]
    [threading(both)]
    runtimeclass TabController
    {
        static Windows.Internal.ComposableShell.Tabs.TabController Current{ get; };
        Windows.Internal.ComposableShell.Tabs.ShellTab CreateTab(Windows.Foundation.Collections.IPropertySet viewValueSet);
        Windows.Internal.ComposableShell.Tabs.ShellTab TryGetReplacementTab(Windows.Foundation.Collections.IPropertySet viewValueSet);
        void GroupTab(ShellTab tab, Windows.Foundation.Collections.IPropertySet viewValueSet);
        void SelectTab(ShellTab tab);
        void CloseTab(ShellTab tab);
        [method_name("MoveTabToGroup")] void MoveTabToGroup(ShellTab tab, ShellTabGroup group);
        Windows.Foundation.IAsyncOperation <Windows.Internal.ComposableShell.Tabs.TabThumbnail>  GetTabThumbnailVisualAsync(ShellTab tab, Windows.UI.Composition.Compositor compositor, Windows.Internal.ApplicationModel.WindowManagement.WindowId hostWindowId, Windows.Foundation.Size size);
        Windows.Foundation.IAsyncOperation <Windows.Internal.ComposableShell.Tabs.TabControllerMenuItemsRequestedEventArgs>  GetMenuItemsAsync(ShellTab tab);
        Windows.Foundation.Rect GetTabBoundingRect(ShellTab tab);
        void RequestCloseTab(ShellTab tab);
        void RequestCloseTabById(ShellTabId tabId);
        void RequestCloseTabGroup(ShellTabGroup group);
        [method_name("RequestSelectTabAsync")] Windows.Foundation.IAsyncOperation <Boolean>  RequestSelectTabAsync(ShellTabGroup group, ShellTab tab);
        Windows.Foundation.IAsyncOperation <Boolean>  RequestSelectTabByIdAsync(ShellTabGroupId groupId, ShellTabId tabId);
        [method_name("RequestSelectTabWithPositionAsync")] Windows.Foundation.IAsyncOperation <Boolean>  RequestSelectTabAsync(ShellTabGroup group, ShellTab tab, RelativeTabPosition position);
        Windows.Foundation.IAsyncOperation <Boolean>  RequestSelectTabByIndexAsync(ShellTabGroup group, ShellTab tab, UInt32 targetIndex);
        void RequestTabViewOperation(ShellTab tab, ViewCommand command);
        void RequestTabViewOperationById(ShellTabGroupId groupId, ViewCommand command);
        [method_name("MoveTabToGroupById")] Windows.Internal.ComposableShell.Tabs.ShellTabGroupId MoveTabToGroupById(ShellTabId tabId, ShellTabGroupId groupId);
        [method_name("MoveTabToGroupByIdWithIndex")] Windows.Internal.ComposableShell.Tabs.ShellTabGroupId MoveTabToGroupById(ShellTabId tabId, ShellTabGroupId groupId, UInt32 desiredIndex);
        [method_name("MoveTabToGroupWithIndex")] void MoveTabToGroup(ShellTab tab, ShellTabGroup group, UInt32 desiredIndex);
        void UngroupTab(ShellTab tab);
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerCancellableEventArgs>  SelectTabRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerEventArgs>  CloseTabRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerViewEventArgs>  TabViewOperationRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerCloseTabGroupRequestedEventArgs>  CloseTabGroupRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerEventArgs>  TabMovedGroups;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerThumbnailEventArgs>  ThumbnailRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerMenuItemsRequestedEventArgs>  TabMenuItemsRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerRectEventArgs>  BoundingRectRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabController, Windows.Internal.ComposableShell.Tabs.TabControllerEventArgs>  TabUngrouping;
    }


}
