








namespace Windows.Web
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [uuid(b0aba86a-9aeb-4d3a-9590-003e3ca7e290)]
    interface IUriToStreamResolver
    {
        Windows.Foundation.IAsyncOperation <Windows.Storage.Streams.IInputStream>  UriToStreamAsync(Windows.Foundation.Uri uri);
    };

}
