









namespace Windows.ApplicationModel.UserDataAccounts.Provider
{
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    enum UserDataAccountProviderOperationKind
    {
        AddAccount,
        Settings,
        ResolveErrors,
    };

    [contract(Windows.Foundation.UniversalApiContract, 3)]
    enum UserDataAccountProviderPartnerAccountKind
    {
        Exchange,
        PopOrImap,
    };

    [uuid(a20aad63-888c-4a62-a3dd-34d07a802b2b)]
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    interface IUserDataAccountProviderOperation
    {
        Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountProviderOperationKind Kind{ get; };
    };


    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountPartnerAccountInfo", 5f200037-f6ef-4ec3-8630-012c59c1149f)]
    runtimeclass UserDataAccountPartnerAccountInfo
    {
        String DisplayName{ get; };
        UInt32 Priority{ get; };
        Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountProviderPartnerAccountKind AccountKind{ get; };
    }




    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderAddAccountOperation", b9c72530-3f84-4b5d-8eaa-45e97aa842ed)]
    runtimeclass UserDataAccountProviderAddAccountOperation
        : Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderOperation
    {
        Windows.ApplicationModel.UserDataAccounts.UserDataAccountContentKinds ContentKinds{ get; };
        Windows.Foundation.Collections.IVectorView <Windows.ApplicationModel.UserDataAccounts.Provider.UserDataAccountPartnerAccountInfo>  PartnerAccountInfos{ get; };
        void ReportCompleted(String userDataAccountId);
    }

    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderSettingsOperation", 92034db7-8648-4f30-acfa-3002658ca80d)]
    runtimeclass UserDataAccountProviderSettingsOperation
        : Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderOperation
    {
        String UserDataAccountId{ get; };
        void ReportCompleted();
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [interface_name("Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderResolveErrorsOperation", 6235dc15-bfcb-41e1-9957-9759a28846cc)]
    runtimeclass UserDataAccountProviderResolveErrorsOperation
        : Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderOperation
    {
        String UserDataAccountId{ get; };
        void ReportCompleted();
    }

}
namespace Windows.ApplicationModel.Activation
{
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [uuid(1bc9f723-8ef1-4a51-a63a-fe711eeab607)]
    interface IUserDataAccountProviderActivatedEventArgs requires Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
        Windows.ApplicationModel.UserDataAccounts.Provider.IUserDataAccountProviderOperation Operation{ get; };
    };

    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [marshaling_behavior(agile)]
    runtimeclass UserDataAccountProviderActivatedEventArgs
        : [default]Windows.ApplicationModel.Activation.IUserDataAccountProviderActivatedEventArgs
        , Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
    }

}
namespace Windows.UI.WebUI
{
    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 3)]
    runtimeclass WebUIUserDataAccountProviderActivatedEventArgs
        : [default]Windows.ApplicationModel.Activation.IUserDataAccountProviderActivatedEventArgs
        , Windows.ApplicationModel.Activation.IActivatedEventArgs
        , Windows.UI.WebUI.IActivatedEventArgsDeferral
    {
    }

}
