










namespace Windows.Internal.Shell.Holographic
{
    [contractversion(1)]
    [internal]
    apicontract ShellCommonContract{};

    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    [uuid(8617b1d7-3b33-466f-8815-453f12f41119)]
    interface IPresentationReadyChangedEventArgs
    {
        Boolean ReadyForPresentation{ get; };
    };

    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    [uuid(c62d3f50-1650-4fb6-a68c-63b17dd08c3f)]
    interface IPrepareForInitialPresentationEventArgs
    {
        Boolean PreparingForPresentation{ get; };
    };

    [uuid(a674aa3e-63b4-4b3b-bb4b-0c4ef3227b4f)]
    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    interface IViewSizePreferencesChangedEventArgs
    {
        Windows.Foundation.Size RequestedSize{ get; };
        void ResizeAttemptHonored();
    };

    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    enum ViewMode
    {
        Normal,
        FullScreen_Standard,
        FullScreen_Minimal,
        SuppressSystemOverlays,
    };

    [uuid(9fc146ad-647a-44fa-b14a-4eaf40f1aba0)]
    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    interface IViewHostViewModeChangeRequestedEventArgs
    {
        Windows.Internal.Shell.Holographic.ViewMode Mode{ get; };
    };

    [uuid(70ced100-1336-479f-801f-f19189ba7fb7)]
    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    interface ITitleBarChangedEventArgs
    {
        String Title{ get; };
    };

    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    [uuid(e545cb13-8407-4ad5-badc-92724606be12)]
    interface IFrameworkViewTypeSetEventArgs
    {
        Int32 ViewType{ get; };
    };

    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    [uuid(c126df4f-0ea7-48c6-875c-23b737939cd1)]
    interface IViewHostItem
    {
        String AppUserModelId{ get; };
        UInt32 CompositionId{ get; };
        UInt32 UniqueId{ get; };
        UInt32 ProcessId{ get; };
        Boolean Visibility{ get; };
        Boolean Visibility{ set; };
        Boolean ReadyToPresent{ get; };
        Boolean IsBackButtonVisible{ get; };
        Windows.Internal.Shell.Holographic.ViewMode ViewMode{ get; };
        Int32 FrameworkViewType{ get; };
        void TryBack();
        void TryClose(Boolean userInitiated);
        void ChangeBounds(Windows.Internal.Shell.ViewManagerInterop.ViewBounds bounds);
        void Activate();
        void NotifySplashScreenDismissed();
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Windows.Internal.Shell.Holographic.IPresentationReadyChangedEventArgs>  PresentationReadyChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Windows.Internal.Shell.Holographic.IPrepareForInitialPresentationEventArgs>  PrepareforInitialPresentation;
        Windows.Foundation.Size Size{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Windows.Internal.Shell.Holographic.IViewSizePreferencesChangedEventArgs>  SizePreferencesChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Object>  BackButtonVisibilityChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Windows.Internal.Shell.Holographic.IViewHostViewModeChangeRequestedEventArgs>  ViewModeChangeRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Windows.Internal.Shell.Holographic.ITitleBarChangedEventArgs>  TitleBarChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.Shell.Holographic.IViewHostItem, Windows.Internal.Shell.Holographic.IFrameworkViewTypeSetEventArgs>  FrameworkViewTypeSet;
    };

    [uuid(f6d877c6-db78-4dda-8280-9ac7a7fea0a1)]
    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    interface IViewHostItemVmiInternal
    {
        void Navigate(Windows.Internal.Shell.ViewManagerInterop.NavigationLevel value);
        Windows.Internal.Shell.ViewManagerInterop.NavigationLevel NavigationLevel{ get; };
        void GetClientWindowState(out Windows.Internal.Shell.ViewManagerInterop.IClientWindowState clientWindowState);
        void GetMobileViewWrapper(out Windows.Internal.Shell.ViewManagerInterop.Mobile.IMobileViewWrapper mobileViewWrapper);
        Boolean IsEqual(Windows.Internal.Shell.ViewManagerInterop.IViewWrapper other);
        void RaiseBackButtonVisibleChanged();
        void RaiseViewModeChanged();
        void RaiseFrameworkViewTypeSet();
        void EnsurePresentationNotReadyEventRaised();
    };

    [contract(Windows.Internal.Shell.Holographic.ShellCommonContract, 1)]
    [uuid(0cfc8c70-0442-4d54-ab51-7f5a0c9e44ad)]
    interface IViewHostItemAppViewInternal
    {
        UInt32 CoreWindowId{ get; };
        void SetActivationPropertySet(Windows.Foundation.Collections.PropertySet value);
        Windows.Foundation.Collections.PropertySet GetActivationPropertySet();
        void RaiseSizePreferencesChanged(Windows.Foundation.Size value);
        void RaisePresentationNotReady();
        void RaiseFrameworkViewTypeSet();
        void BindSizeToRectangle(Windows.Foundation.Rect rectangle);
        void EnterFullScreen();
        void ExitFullScreen();
        void DisconnectFromPresentationLayer();
    };

}
