












namespace Windows.Internal.ComposableShell.Tabs
{
    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Internal.ComposableShell.Tabs.IBrokeredViewTabConverterStatics", fb7d2c9e-f26c-49db-8031-0da0f4ed5643)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.IBrokeredViewTabConverter", 8c38bf7c-d9e5-4cb9-a404-fb4e74e5c9a8)]
    [threading(both)]
    runtimeclass BrokeredViewTabConverter
    {
        static Windows.Internal.ComposableShell.Tabs.BrokeredViewTabConverter Current{ get; };
        Windows.Internal.ComposableShell.Tabs.ShellTab GetTabForWindowId(Windows.Internal.ApplicationModel.WindowManagement.WindowId windowId);
        Windows.Internal.ComposableShell.Tabs.ShellTabGroup TryGetTabGroupForWindowId(Windows.Internal.ApplicationModel.WindowManagement.WindowId windowId);
        Windows.Internal.ComposableShell.Tabs.ShellTab AddVirtualTabForWindow(ShellTab tab, Windows.Internal.ApplicationModel.WindowManagement.WindowId windowId);
        void RemoveVirtualTab(ShellTab tab);
        void NewViewForTab(UInt32 viewId, ShellTabId tabId);
        void CancelTabTransfer(ShellTabId tabId);
        void TabTransferReceived(ShellTabId tabId);
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.BrokeredViewTabConverter, Windows.Internal.ComposableShell.Tabs.ViewTabEventArgs>  ViewTabAssociated;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.BrokeredViewTabConverter, Windows.Internal.ComposableShell.Tabs.ViewTabEventArgs>  ViewTabDeassociated;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.BrokeredViewTabConverter, Windows.Internal.ComposableShell.Tabs.ViewTabEventArgs>  ViewTabClosed;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.BrokeredViewTabConverter, Windows.Internal.ComposableShell.Tabs.ViewTabEventArgs>  ViewTabLostFocus;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.BrokeredViewTabConverter, Windows.Internal.ComposableShell.Tabs.ViewTabEventArgs>  TabDeselectedViewActive;
        Windows.Internal.ComposableShell.Tabs.ShellTab AddAndInsertTabAtDefaultPositionForWindowId(ShellTab tab, Windows.UI.Internal.ViewManagement.ApplicationViewTabInsertionContext defaultInsertionContext, Windows.Internal.ApplicationModel.WindowManagement.WindowId windowId);
        String GetDisplayNameForShellTab(ShellTab tab);
        Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker TabTransferEventBroker{ get; };
    }

    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.IViewTabEventArgs", 000b144c-de5b-45c6-8404-b4d06e056130)]
    runtimeclass ViewTabEventArgs
    {
        Windows.Internal.ApplicationModel.WindowManagement.WindowId View{ get; };
        Windows.Internal.ComposableShell.Tabs.ShellTab Tab{ get; };
    }

    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabTransferEventBroker", 4897dc3a-5143-5478-912e-a6edc7c5a2ab)]
    runtimeclass TabTransferEventBroker
    {
        void RaiseTabViewProvided(ShellTabId tabId, Int32 viewId);
        void RaiseTabTransferStarting(ShellTabId tabId);
        void RaiseTabTransferReceiving(ShellTabId tabId);
        void RaiseTabTransferCompleted(ShellTabId tabId);
        void RaiseTabTransferCanceled(ShellTabId tabId);
        void RaiseTabDropped(ShellTabGroupId groupId, ShellTabId tabId, Int32 dropIndex);
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker, Windows.Internal.ComposableShell.Tabs.TabViewProvidedEventArgs>  TabViewProvided;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker, Windows.Internal.ComposableShell.Tabs.ShellTabId>  TabTransferStarting;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker, Windows.Internal.ComposableShell.Tabs.ShellTabId>  TabTransferReceiving;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker, Windows.Internal.ComposableShell.Tabs.ShellTabId>  TabTransferCompleted;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker, Windows.Internal.ComposableShell.Tabs.ShellTabId>  TabTransferCanceled;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.Tabs.TabTransferEventBroker, Windows.Internal.ComposableShell.Tabs.TabDroppedEventArgs>  TabDropped;
    }




    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.IBrokeredTabAppPolicySettings", ee654811-7557-4bad-8afd-7a28272e4d92)]
    runtimeclass BrokeredTabAppPolicySettings
    {
        Boolean UseCustomTabsWhenLaunchedIntoNewGroup{ get; };
        Boolean UseCustomTabsWhenLaunchedIntoNewGroup{ set; };
        Boolean IsActivatingIntoExistingGroup(Windows.ApplicationModel.Activation.IActivatedEventArgs activatedEventArgs);
        Boolean IsViewInActivationGroup(Int32 viewId, Windows.ApplicationModel.Activation.IActivatedEventArgs activatedEventArgs);
        Windows.UI.Internal.ViewManagement.ApplicationViewTabInsertionContext GetInsertionContextForActivation(Windows.ApplicationModel.Activation.IActivatedEventArgs activatedEventArgs);
    }


    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabViewProvidedEventArgs", f35523bf-7020-5a86-8a00-d24d7a013b36)]
    runtimeclass TabViewProvidedEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTabId TabId{ get; };
        Int32 ViewId{ get; };
    }


    [contract(Windows.Internal.ComposableShell.Tabs.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Internal.ComposableShell.Tabs.ITabDroppedEventArgs", feee0d59-7016-5542-a655-53dd241de069)]
    runtimeclass TabDroppedEventArgs
    {
        Windows.Internal.ComposableShell.Tabs.ShellTabGroupId GroupId{ get; };
        Windows.Internal.ComposableShell.Tabs.ShellTabId TabId{ get; };
        Int32 DropIndex{ get; };
    }


}
