













namespace Windows.Internal.ComposableShell
{
    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    enum TitleBarColorElement
    {
        Invalid,
        TitleBarTextColor,
        TitleBarBackgroundColor,
        TitleBarButtonTextColor,
        TitleBarButtonBackgroundColor,
        TitleBarButtonHoverTextColor,
        TitleBarButtonHoverBackgroundColor,
        TitleBarButtonPressedTextColor,
        TitleBarButtonPressedBackgroundColor,
        TitleBarInactiveTextColor,
        TitleBarInactiveBackgroundColor,
        TitleBarInactiveButtonTextColor,
        TitleBarInactiveButtonBackgroundColor,
    };

    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    [uuid(50478b2e-5ee9-447a-8545-5b85557c613f)]
    interface ITitleBarColorOverrideChangedEventArgs
    {
        Windows.Internal.ComposableShell.TitleBarColorElement ChangedColorElement{ get; };
    };

    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    struct OptionalColor
    {
        Boolean HasValue;
        Windows.UI.Color Value;
    };

    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    struct ViewWithTitleBarProperties
    {
        Boolean BackButtonVisible;
        Boolean ViewExtendedIntoTitleBar;
        Boolean TitleBarInputVisualSet;
        OptionalColor TitleBarTextColorOverride;
        OptionalColor TitleBarBackgroundColorOverride;
        OptionalColor TitleBarButtonTextColorOverride;
        OptionalColor TitleBarButtonBackgroundColorOverride;
        OptionalColor TitleBarButtonHoverTextColorOverride;
        OptionalColor TitleBarButtonHoverBackgroundColorOverride;
        OptionalColor TitleBarButtonPressedTextColorOverride;
        OptionalColor TitleBarButtonPressedBackgroundColorOverride;
        OptionalColor TitleBarInactiveTextColorOverride;
        OptionalColor TitleBarInactiveBackgroundColorOverride;
        OptionalColor TitleBarInactiveButtonTextColorOverride;
        OptionalColor TitleBarInactiveButtonBackgroundColorOverride;
    };

    [contract(Windows.Internal.ComposableShell.InternalContract, 1)]
    [uuid(0bbd1e52-6ebd-4d9e-84fa-68b30734a87f)]
    interface IViewWithTitleBar requires Windows.Internal.ComposableShell.IComposableView, Windows.Internal.ComposableShell.ITreeNode
    {
        String Title{ get; };
        String ApplicationDisplayName{ get; };
        Boolean IsBackButtonVisible{ get; };
        Boolean IsViewExtendedIntoTitleBar{ get; };
        Boolean IsTitleBarInputVisualSet{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarTextColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarBackgroundColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarButtonTextColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarButtonBackgroundColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarButtonHoverTextColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarButtonHoverBackgroundColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarButtonPressedTextColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarButtonPressedBackgroundColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarInactiveTextColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarInactiveBackgroundColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarInactiveButtonTextColorOverride{ get; };
        Windows.Internal.ComposableShell.OptionalColor TitleBarInactiveButtonBackgroundColorOverride{ get; };
        Windows.Internal.ComposableShell.ViewWithTitleBarProperties TitleBarProperties{ get; };
        void ChangeTitleBarHeight(Double value);
        void ChangeIsTitleBarVisible(Boolean value);
        void ChangeTitleBarSystemOverlayLeftInset(Double value);
        void ChangeTitleBarSystemOverlayRightInset(Double value);
        void ChangeTitleBarInputRoutingInfo(Windows.Internal.Shell.ViewManagerInterop.InputRoutingInfo value);
        void ChangeTitleBarInputRoutingHwnd(UInt32 value);
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.IViewWithTitleBar, Windows.Internal.ComposableShell.ITitleBarColorOverrideChangedEventArgs>  TitleBarColorOverrideChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.IViewWithTitleBar, Object>  TitleChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.IViewWithTitleBar, Object>  ApplicationDisplayNameChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.IViewWithTitleBar, Object>  BackButtonVisibilityChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.IViewWithTitleBar, Object>  IsViewExtendedIntoTitleBarChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Internal.ComposableShell.IViewWithTitleBar, Object>  IsTitleBarInputVisualSetChanged;
    };

}
