








namespace Windows.Foundation.Diagnostics
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Foundation.Diagnostics.IErrorDetailsStatics", b7703750-0b1d-46c8-aa0e-4b8178e4fce9)]
    [interface_name("Windows.Foundation.Diagnostics.IErrorDetails", 378cbb01-2cc9-428f-8c55-2c990d463e8f)]
    [threading(both)]
    runtimeclass ErrorDetails
    {
        static Windows.Foundation.IAsyncOperation <Windows.Foundation.Diagnostics.ErrorDetails>  CreateFromHResultAsync(Int32 errorCode);
        String Description{ get; };
        String LongDescription{ get; };
        Windows.Foundation.Uri HelpUri{ get; };
    }


}
