









namespace Windows.Internal.StateRepository
{
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [dualapipartition(0xa000000)]
    [static_name("Windows.Internal.StateRepository.ISecondaryTileUserNotificationChannelStatics", fe39030f-8455-4bf4-af4a-a34c336e4c13)]
    [interface_name("Windows.Internal.StateRepository.ISecondaryTileUserNotificationChannel", 100e0fe5-f8e6-4211-b7ad-21085e53a12e)]
    [threading(both)]
    runtimeclass SecondaryTileUserNotificationChannel
    {
        static Windows.Internal.StateRepository.SecondaryTileUserNotificationChannel CreateForUser(User user);
        static Windows.Internal.StateRepository.SecondaryTileUserNotificationChannel CreateForUserSid(String userSid);
        static Windows.Internal.StateRepository.SecondaryTileUserNotificationChannel CreateForUserSecurityIdentifier(UInt8[] userSecurityIdentifier);
        SecondaryTileUserNotificationChannel();
        void RegisterForNotifications();
        void DeregisterForNotifications();
        Boolean IsRegisteredForNotifications{ get; };
        String Name{ get; };
        String UserSid{ get; };
        void RaiseNotification();
    }


}
