







namespace Windows.ApplicationModel.Calls
{
    [contractversion(1)]
    apicontract LockScreenCallContract{};



    [contract(Windows.ApplicationModel.Calls.LockScreenCallContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.Calls.ILockScreenCallEndCallDeferral", 2dd7ed0d-98ed-4041-9632-50ff812b773f)]
    runtimeclass LockScreenCallEndCallDeferral
    {
        void Complete();
    }


    [contract(Windows.ApplicationModel.Calls.LockScreenCallContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.Calls.ILockScreenCallUI", c596fd8d-73c9-4a14-b021-ec1c50a3b727)]
    runtimeclass LockScreenCallUI
    {
        void Dismiss();
        event Windows.Foundation.TypedEventHandler <Windows.ApplicationModel.Calls.LockScreenCallUI, Windows.ApplicationModel.Calls.LockScreenCallEndRequestedEventArgs>  EndRequested;
        event Windows.Foundation.TypedEventHandler <Windows.ApplicationModel.Calls.LockScreenCallUI, Object>  Closed;
        String CallTitle{ get; };
        String CallTitle{ set; };
    }

    [contract(Windows.ApplicationModel.Calls.LockScreenCallContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.ApplicationModel.Calls.ILockScreenCallEndRequestedEventArgs", 8190a363-6f27-46e9-aeb6-c0ae83e47dc7)]
    runtimeclass LockScreenCallEndRequestedEventArgs
    {
        Windows.ApplicationModel.Calls.LockScreenCallEndCallDeferral GetDeferral();
        Windows.Foundation.DateTime Deadline{ get; };
    }

}
