









namespace Windows.Internal.StateRepository
{
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Internal.StateRepository.ISecondaryTileUserChangedEventArgsStatics", 3940ce31-f32f-4fba-b877-1a1beea68f77)]
    [interface_name("Windows.Internal.StateRepository.ISecondaryTileUserChangedEventArgs", 05358beb-1382-413f-80fa-4573f01ab802)]
    [threading(both)]
    runtimeclass SecondaryTileUserChangedEventArgs
    {
        SecondaryTileUserChangedEventArgs();
        static Windows.Internal.StateRepository.SecondaryTileUserChangedEventArgs Create(String userSid);
        Windows.Internal.StateRepository.User TryGetUser();
    }


}
