








namespace Windows.System.Diagnostics
{
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.System.Diagnostics.IProcessDiagnosticInfoStatics", 2f41b260-b49f-428c-aa0e-84744f49ca95)]
    [interface_name("Windows.System.Diagnostics.IProcessDiagnosticInfo", e830b04b-300e-4ee6-a0ab-5b5f5231b434)]
    [threading(both)]
    runtimeclass ProcessDiagnosticInfo
    {

        [contract(Windows.Foundation.UniversalApiContract, 5)]
        [static_name("Windows.System.Diagnostics.IProcessDiagnosticInfoStatics2", 4a869897-9899-4a44-a29b-091663be09b6)]
        {
            static Windows.System.Diagnostics.ProcessDiagnosticInfo TryGetForProcessId(UInt32 processId);
        }
        static Windows.Foundation.Collections.IVectorView <Windows.System.Diagnostics.ProcessDiagnosticInfo>  GetForProcesses();
        static Windows.System.Diagnostics.ProcessDiagnosticInfo GetForCurrentProcess();
        UInt32 ProcessId{ get; };
        String ExecutableFileName{ get; };
        Windows.System.Diagnostics.ProcessDiagnosticInfo Parent{ get; };
        Windows.Foundation.DateTime ProcessStartTime{ get; };
        Windows.System.Diagnostics.ProcessDiskUsage DiskUsage{ get; };
        Windows.System.Diagnostics.ProcessMemoryUsage MemoryUsage{ get; };
        Windows.System.Diagnostics.ProcessCpuUsage CpuUsage{ get; };

        [contract(Windows.Foundation.UniversalApiContract, 5)]
        [interface_name("Windows.System.Diagnostics.IProcessDiagnosticInfo2", 9558cb1a-3d0b-49ec-ab70-4f7a112805de)]
        {
            Windows.Foundation.Collections.IVector <Windows.System.AppDiagnosticInfo>  GetAppDiagnosticInfos();
            Boolean IsPackaged{ get; };
        }
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000004)]
    [interface_name("Windows.System.Diagnostics.IProcessDiskUsage", 5ad78bfd-7e51-4e53-bfaa-5a6ee1aabbf8)]
    runtimeclass ProcessDiskUsage
    {
        Windows.System.Diagnostics.ProcessDiskUsageReport GetReport();
    }

    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Diagnostics.IProcessMemoryUsage", f50b229b-827c-42b7-b07c-0e32627e6b3e)]
    runtimeclass ProcessMemoryUsage
    {
        Windows.System.Diagnostics.ProcessMemoryUsageReport GetReport();
    }

    [marshaling_behavior(agile)]
    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.System.Diagnostics.IProcessCpuUsage", 0bbb2472-c8bf-423a-a810-b559ae4354e2)]
    runtimeclass ProcessCpuUsage
    {
        Windows.System.Diagnostics.ProcessCpuUsageReport GetReport();
    }





    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Diagnostics.IProcessMemoryUsageReport", c2c77cba-1951-4685-8532-7e749ecf8eeb)]
    runtimeclass ProcessMemoryUsageReport
    {
        UInt64 NonPagedPoolSizeInBytes{ get; };
        UInt32 PageFaultCount{ get; };
        UInt64 PageFileSizeInBytes{ get; };
        UInt64 PagedPoolSizeInBytes{ get; };
        UInt64 PeakNonPagedPoolSizeInBytes{ get; };
        UInt64 PeakPageFileSizeInBytes{ get; };
        UInt64 PeakPagedPoolSizeInBytes{ get; };
        UInt64 PeakVirtualMemorySizeInBytes{ get; };
        UInt64 PeakWorkingSetSizeInBytes{ get; };
        UInt64 PrivatePageCount{ get; };
        UInt64 VirtualMemorySizeInBytes{ get; };
        UInt64 WorkingSetSizeInBytes{ get; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000004)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Diagnostics.IProcessDiskUsageReport", 401627fd-535d-4c1f-81b8-da54e1be635e)]
    runtimeclass ProcessDiskUsageReport
    {
        Int64 ReadOperationCount{ get; };
        Int64 WriteOperationCount{ get; };
        Int64 OtherOperationCount{ get; };
        Int64 BytesReadCount{ get; };
        Int64 BytesWrittenCount{ get; };
        Int64 OtherBytesCount{ get; };
    }



    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Diagnostics.IProcessCpuUsageReport", 8a6d9cac-3987-4e2f-a119-6b5fa214f1b4)]
    runtimeclass ProcessCpuUsageReport
    {
        Windows.Foundation.TimeSpan KernelTime{ get; };
        Windows.Foundation.TimeSpan UserTime{ get; };
    }



    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 4)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Diagnostics.ISystemMemoryUsage", 17ffc595-1702-49cf-aa27-2f0a32591404)]
    runtimeclass SystemMemoryUsage
    {
        Windows.System.Diagnostics.SystemMemoryUsageReport GetReport();
    }

    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 4)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Diagnostics.ISystemCpuUsage", 6037b3ac-02d6-4234-8362-7fe3adc81f5f)]
    runtimeclass SystemCpuUsage
    {
        Windows.System.Diagnostics.SystemCpuUsageReport GetReport();
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 4)]
    [static_name("Windows.System.Diagnostics.ISystemDiagnosticInfoStatics", d404ac21-fc7d-45f0-9a3f-39203aed9f7e)]
    [interface_name("Windows.System.Diagnostics.ISystemDiagnosticInfo", a290fe05-dff3-407f-9a1b-0b2b317ca800)]
    [threading(both)]
    runtimeclass SystemDiagnosticInfo
    {
        static Windows.System.Diagnostics.SystemDiagnosticInfo GetForCurrentSystem();
        Windows.System.Diagnostics.SystemMemoryUsage MemoryUsage{ get; };
        Windows.System.Diagnostics.SystemCpuUsage CpuUsage{ get; };
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 4)]
    [interface_name("Windows.System.Diagnostics.ISystemMemoryUsageReport", 38663c87-2a9f-403a-bd19-2cf3e8169500)]
    runtimeclass SystemMemoryUsageReport
    {
        UInt64 TotalPhysicalSizeInBytes{ get; };
        UInt64 AvailableSizeInBytes{ get; };
        UInt64 CommittedSizeInBytes{ get; };
    }



    [dualapipartition(0xa000004)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 4)]
    [interface_name("Windows.System.Diagnostics.ISystemCpuUsageReport", 2c26d0b2-9483-4f62-ab57-82b29d9719b8)]
    runtimeclass SystemCpuUsageReport
    {
        Windows.Foundation.TimeSpan KernelTime{ get; };
        Windows.Foundation.TimeSpan UserTime{ get; };
        Windows.Foundation.TimeSpan IdleTime{ get; };
    }


}
