







namespace Windows.UI.Accessibility
{
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.Accessibility.IScreenReaderPositionChangedEventArgs", 557eb5e5-54d0-5ccd-9fc5-ed33357f8a9f)]
    runtimeclass ScreenReaderPositionChangedEventArgs
    {
        Windows.Foundation.Rect ScreenPositionInRawPixels{ get; };
        Boolean IsReadingText{ get; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.UI.Accessibility.IScreenReaderService", 19475427-eac0-50d3-bdd9-9b487a226256)]
    [threading(both)]
    runtimeclass ScreenReaderService
    {
        ScreenReaderService();
        Windows.UI.Accessibility.ScreenReaderPositionChangedEventArgs CurrentScreenReaderPosition{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.UI.Accessibility.ScreenReaderService, Windows.UI.Accessibility.ScreenReaderPositionChangedEventArgs>  ScreenReaderPositionChanged;
    }

}
