








namespace Windows.UI.Internal.Input
{
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.Internal.Input.IActivatableEntity", 037ca861-30b8-5067-a85b-0ba56acaf7b2)]
    runtimeclass ActivatableEntity
    {
        UInt64 Id{ get; };
        Boolean IsActivated{ get; };
        void Activate();
    }


    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [interface_name("Windows.UI.Internal.Input.IActivationWatcherEventArgs", c0c8233a-4f58-53aa-8ba9-dc97d8ab0858)]
    runtimeclass ActivationWatcherEventArgs
    {
        Windows.UI.Internal.Input.ActivatableEntity ActivatableEntity{ get; };
    }

    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    enum ActivationWatcherStatus
    {
        Created,
        Started,
        EnumerationCompleted,
        Stopping,
        Stopped,
        Aborted,
    };


    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.UI.Internal.Input.IActivationWatcherStatics", 038be120-ab59-5abb-ba7f-bccc2ccd8549)]
    [interface_name("Windows.UI.Internal.Input.IActivationWatcher", 618b9642-45d1-4312-a941-cf8f497f3a38)]
    [threading(both)]
    runtimeclass ActivationWatcher
    {
        static Windows.UI.Internal.Input.ActivationWatcher Create();
        void Start();
        void Stop();
        Windows.UI.Internal.Input.ActivationWatcherStatus ActivationWatcherStatus{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.ActivationWatcher, Windows.UI.Internal.Input.ActivationWatcherEventArgs>  ActivatableEntityAdded;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.ActivationWatcher, Windows.UI.Internal.Input.ActivationWatcherEventArgs>  ActivatableEntityRemoved;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.ActivationWatcher, Windows.UI.Internal.Input.ActivationWatcherEventArgs>  ActivationChanged;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.ActivationWatcher, Windows.UI.Internal.Input.ActivationWatcherEventArgs>  EnumerationCompleted;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.ActivationWatcher, Windows.UI.Internal.Input.ActivationWatcherEventArgs>  Stopped;
    }


}
