





namespace Windows.Media.SpeechSynthesis.Internal
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [uuid(36d1caa6-9da3-4827-a6d1-53bdd2115f10)]
    [contract(Windows.Media.SpeechSynthesis.Internal.InternalContract, 1)]
    interface ISpeechSynthesizerInternal
    {
        void ParseSsmlIntoText(String ssmlText, out String pRawText);
        void SetVoicePropertyNum(String name, Int32 value);
    };

    [contract(Windows.Media.SpeechSynthesis.Internal.InternalContract, 1)]
    [uuid(f0626d83-e091-4e62-945d-aad32eed512a)]
    interface IVoiceInformationAllProperties
    {
        String SampleText{ get; };
        Windows.Foundation.Collections.IMapView <String, String>  AllProperties{ get; };
    };

}
