







namespace Windows.Internal.Shell.PlatformExtensions
{
    [contract(Windows.Internal.Shell.PlatformExtensions.InternalContract, 1)]
    [uuid(0bf58e7e-3a14-4749-8a26-0f77920a13ea)]
    interface IThumbnailDevice
    {
        Windows.Internal.ComposableShell.Multitasking.IThumbnailFactory CreateLocalFactory(Windows.Internal.ComposableShell.Multitasking.IThumbnailFactory remote);
    };

}
