









namespace Windows.UI.WebUI.Core
{
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    enum WebUICommandBarClosedDisplayMode
    {
        Default,
        Minimal,
        Compact,
    };


    [marshaling_behavior(agile)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBarItemInvokedEventArgs", 304edbdd-e741-41ef-bdc4-a45cea2a4f70)]
    runtimeclass WebUICommandBarItemInvokedEventArgs
    {
        Boolean IsPrimaryCommand{ get; };
    }

    [uuid(c9069ec2-284a-4633-8aad-637a27e282c3)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    interface IWebUICommandBarElement
    {
    };

    [uuid(d587655d-2014-42be-969a-7d14ca6c8a49)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    interface IWebUICommandBarIcon
    {
    };


    [marshaling_behavior(agile)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBarIconButton", 8f1bc93a-3a7c-4842-a0cf-aff6ea308586)]
    runtimeclass WebUICommandBarIconButton
        : Windows.UI.WebUI.Core.IWebUICommandBarElement
    {
        WebUICommandBarIconButton();
        Boolean Enabled{ get; };
        Boolean Enabled{ set; };
        String Label{ get; };
        String Label{ set; };
        Boolean IsToggleButton{ get; };
        Boolean IsToggleButton{ set; };
        Boolean IsChecked{ get; };
        Boolean IsChecked{ set; };
        Windows.UI.WebUI.Core.IWebUICommandBarIcon Icon{ get; };
        Windows.UI.WebUI.Core.IWebUICommandBarIcon Icon{ set; };
        event Windows.Foundation.TypedEventHandler <Windows.UI.WebUI.Core.WebUICommandBarIconButton, Windows.UI.WebUI.Core.WebUICommandBarItemInvokedEventArgs>  ItemInvoked;
    }


    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBarConfirmationButton", 86e7824a-e3d5-4eb6-b2ff-8f018a172105)]
    runtimeclass WebUICommandBarConfirmationButton
        : Windows.UI.WebUI.Core.IWebUICommandBarElement
    {
        WebUICommandBarConfirmationButton();
        String Text{ get; };
        String Text{ set; };
        event Windows.Foundation.TypedEventHandler <Windows.UI.WebUI.Core.WebUICommandBarConfirmationButton, Windows.UI.WebUI.Core.WebUICommandBarItemInvokedEventArgs>  ItemInvoked;
    }



    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [marshaling_behavior(agile)]
    [constructor_name("Windows.UI.WebUI.Core.IWebUICommandBarBitmapIconFactory", f3f7d78a-7673-444a-be62-ac12d31c2231)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBarBitmapIcon", 858f4f45-08d8-4a46-81ec-00015b0b1c6c)]
    runtimeclass WebUICommandBarBitmapIcon
        : Windows.UI.WebUI.Core.IWebUICommandBarIcon
    {
        [method_name( "Create" )] WebUICommandBarBitmapIcon(Windows.Foundation.Uri uri);
        WebUICommandBarBitmapIcon();
        Windows.Foundation.Uri Uri{ get; };
        Windows.Foundation.Uri Uri{ set; };
    }



    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [marshaling_behavior(agile)]
    [constructor_name("Windows.UI.WebUI.Core.IWebUICommandBarSymbolIconFactory", 51be1a1f-3730-429e-b622-14e2b7bf6a07)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBarSymbolIcon", d4935477-fd26-46ed-8658-1a3f4400e7b3)]
    runtimeclass WebUICommandBarSymbolIcon
        : Windows.UI.WebUI.Core.IWebUICommandBarIcon
    {
        [method_name( "Create" )] WebUICommandBarSymbolIcon(String symbol);
        WebUICommandBarSymbolIcon();
        String Symbol{ get; };
        String Symbol{ set; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBarSizeChangedEventArgs", fbf1e2f6-3029-4719-8378-92f82b87af1e)]
    runtimeclass WebUICommandBarSizeChangedEventArgs
    {
        Windows.Foundation.Size Size{ get; };
    }

    [uuid(18dc0ad3-678f-4c19-8963-cc1c49a5ef9e)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    delegate void MenuOpenedEventHandler();

    [uuid(435387c8-4dd0-4c52-9489-d390ce7721d2)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    delegate void MenuClosedEventHandler();

    [uuid(d49cfe3c-dd2e-4c28-b627-303a7f911af5)]
    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    delegate void SizeChangedEventHandler(WebUICommandBarSizeChangedEventArgs eventArgs);



    [contract(Windows.UI.WebUI.Core.WebUICommandBarContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.UI.WebUI.Core.IWebUICommandBarStatics", 1449cdb9-a506-45be-8f42-b2837e2fe0c9)]
    [interface_name("Windows.UI.WebUI.Core.IWebUICommandBar", a4fc0016-dbe5-41ad-8d7b-14698bd6911d)]
    runtimeclass WebUICommandBar
    {
        static Windows.UI.WebUI.Core.WebUICommandBar GetForCurrentView();
        Boolean Visible{ get; };
        Boolean Visible{ set; };
        Double Opacity{ get; };
        Double Opacity{ set; };
        Windows.UI.Color ForegroundColor{ get; };
        Windows.UI.Color ForegroundColor{ set; };
        Windows.UI.Color BackgroundColor{ get; };
        Windows.UI.Color BackgroundColor{ set; };
        Windows.UI.WebUI.Core.WebUICommandBarClosedDisplayMode ClosedDisplayMode{ get; };
        Windows.UI.WebUI.Core.WebUICommandBarClosedDisplayMode ClosedDisplayMode{ set; };
        Boolean IsOpen{ get; };
        Boolean IsOpen{ set; };
        Windows.Foundation.Size Size{ get; };
        Windows.Foundation.Collections.IObservableVector <Windows.UI.WebUI.Core.IWebUICommandBarElement>  PrimaryCommands{ get; };
        Windows.Foundation.Collections.IObservableVector <Windows.UI.WebUI.Core.IWebUICommandBarElement>  SecondaryCommands{ get; };
        event Windows.UI.WebUI.Core.MenuOpenedEventHandler MenuOpened;
        event Windows.UI.WebUI.Core.MenuClosedEventHandler MenuClosed;
        event Windows.UI.WebUI.Core.SizeChangedEventHandler SizeChanged;
    }

}
