









namespace Windows.Management.Core
{
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.Management.Core.IApplicationDataManagerStatics", 1e1862e3-698e-49a1-9752-dee94925b9b3)]
    [default_interface]
    [interface_name("Windows.Management.Core.IApplicationDataManager", 74d10432-2e99-4000-9a3a-64307e858129)]
    [threading(mta)]
    runtimeclass ApplicationDataManager
    {
        static Windows.Storage.ApplicationData CreateForPackageFamily(String packageFamilyName);
    }

}
namespace Windows.Management.Core.Internal
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Management.Core.Internal.InternalContract, 1)]
    [uuid(bf69e560-7edb-4ef7-9d5d-8f89c087a287)]
    interface IApplicationDataManagerStaticsInternal
    {
        Windows.Storage.ApplicationData CreateForPackageFamilyWithUserImpersonation(String packageFamilyName);
    };

}
