











namespace Windows.UI.Internal.Input
{
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [static_name("Windows.UI.Internal.Input.IContainerInfoInputObjectStatics", 0c17f50f-fa46-5d2c-83c4-f36b2a035fdc)]
    [default_interface]
    [interface_name("Windows.UI.Internal.Input.IContainerInfoInputObject", 5d2d0b13-72ab-5f78-bcdc-28c10027ad37)]
    [threading(both)]
    runtimeclass ContainerInfoInputObject
        : Windows.UI.Internal.Input.InputObjectPartner
    {
        static Windows.UI.Internal.Input.ContainerInfoInputObject GetForInputSite(InputSite inputSite, Guid containerGuid);
    }

}
