





namespace Windows.UI.Input.Preview.Injection.Internal
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.UI.Input.Preview.Injection.Internal.InternalContract, 1)]
    [uuid(449fe74b-c1c6-4c16-825c-8b07df61638f)]
    interface IInputInjectorPrivate
    {
        UInt64 GamepadGipDeviceId{ get; };
    };

}
