







namespace Windows.Gaming.Input
{
    [contractversion(1)]
    apicontract GamingInputPreviewContract{};


}
namespace Windows.Gaming.Input.Preview
{
    [dualapipartition(0xa000003)]
    [contract(Windows.Gaming.Input.GamingInputPreviewContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Gaming.Input.Preview.IGameControllerProviderInfoStatics", 0be1e6c5-d9bd-44ee-8362-488b2e464bfb)]
    [threading(both)]
    runtimeclass GameControllerProviderInfo
    {
        static String GetParentProviderId(Windows.Gaming.Input.Custom.IGameControllerProvider provider);
        static String GetProviderId(Windows.Gaming.Input.Custom.IGameControllerProvider provider);
    }

}
