









namespace Windows.Services.Maps
{
    [contractversion(4)]
    apicontract LocalSearchContract{};

}
namespace Windows.Services.Maps.LocalSearch
{
    [contract(Windows.Services.Maps.LocalSearchContract, 1)]
    [webhosthidden]
    enum LocalLocationFinderStatus
    {
        Success,
        UnknownError,
        InvalidCredentials,
        InvalidCategory,
        InvalidSearchTerm,
        InvalidSearchArea,
        NetworkFailure,
        NotSupported,
    };



    [webhosthidden]
    [contract(Windows.Services.Maps.LocalSearchContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Services.Maps.LocalSearch.ILocalLocation", bb0fe9ab-4502-4f2c-94a9-0d60de0e2163)]
    runtimeclass LocalLocation
    {
        Windows.Services.Maps.MapAddress Address{ get; };
        String Identifier{ get; };
        String Description{ get; };
        String DisplayName{ get; };
        Windows.Devices.Geolocation.Geopoint Point{ get; };
        String PhoneNumber{ get; };
        String DataAttribution{ get; };

        [contract(Windows.Services.Maps.LocalSearchContract, 3)]
        [interface_name("Windows.Services.Maps.LocalSearch.ILocalLocation2", 6e9e307c-ecb5-4ffc-bb8c-ba50ba8c2dc6)]
        {
            String Category{ get; };
            Windows.Services.Maps.LocalSearch.LocalLocationRatingInfo RatingInfo{ get; };
            Windows.Foundation.Collections.IVectorView <Windows.Services.Maps.LocalSearch.LocalLocationHoursOfOperationItem>  HoursOfOperation{ get; };
        }
    }


    [contract(Windows.Services.Maps.LocalSearchContract, 1)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [interface_name("Windows.Services.Maps.LocalSearch.ILocalLocationFinderResult", d09b6cc6-f338-4191-9fd8-5440b9a68f52)]
    runtimeclass LocalLocationFinderResult
    {
        Windows.Foundation.Collections.IVectorView <Windows.Services.Maps.LocalSearch.LocalLocation>  LocalLocations{ get; };
        Windows.Services.Maps.LocalSearch.LocalLocationFinderStatus Status{ get; };
    }





    [webhosthidden]
    [marshaling_behavior(agile)]
    [contract(Windows.Services.Maps.LocalSearchContract, 3)]
    [interface_name("Windows.Services.Maps.LocalSearch.ILocalLocationRatingInfo", cb1dab56-3354-4311-8bc0-a2d4d5eb806e)]
    runtimeclass LocalLocationRatingInfo
    {
        Windows.Foundation.IReference <Double>  AggregateRating{ get; };
        Windows.Foundation.IReference <Int32>  RatingCount{ get; };
        String ProviderIdentifier{ get; };
    }

    [webhosthidden]
    [contract(Windows.Services.Maps.LocalSearchContract, 3)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Services.Maps.LocalSearch.ILocalLocationHoursOfOperationItem", 23548c72-a1c7-43f1-a4f0-1091c39ec640)]
    runtimeclass LocalLocationHoursOfOperationItem
    {
        Windows.Globalization.DayOfWeek Day{ get; };
        Windows.Foundation.TimeSpan Start{ get; };
        Windows.Foundation.TimeSpan Span{ get; };
    }


    [webhosthidden]
    [contract(Windows.Services.Maps.LocalSearchContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Services.Maps.LocalSearch.ILocalLocationFinderStatics", d2ef7344-a0de-48ca-81a8-07c7dcfd37ab)]
    [threading(both)]
    runtimeclass LocalLocationFinder
    {
        static Windows.Foundation.IAsyncOperation <Windows.Services.Maps.LocalSearch.LocalLocationFinderResult>  FindLocalLocationsAsync(String searchTerm, Windows.Devices.Geolocation.Geocircle searchArea, String localCategory, UInt32 maxResults);
    }

    [webhosthidden]
    [marshaling_behavior(agile)]
    [contract(Windows.Services.Maps.LocalSearchContract, 1)]
    [static_name("Windows.Services.Maps.LocalSearch.ILocalCategoriesStatics", f49399f5-8261-4321-9974-ef92d49a8dca)]
    [threading(both)]
    runtimeclass LocalCategories
    {
        static String BankAndCreditUnions{ get; };
        static String EatDrink{ get; };
        static String Hospitals{ get; };
        static String HotelsAndMotels{ get; };
        static String All{ get; };
        static String Parking{ get; };
        static String SeeDo{ get; };
        static String Shop{ get; };
    }

    [contract(Windows.Services.Maps.LocalSearchContract, 4)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Services.Maps.LocalSearch.IPlaceInfoHelperStatics", dd1ca9a7-a9c6-491b-bc09-e80fcea48ee6)]
    [threading(both)]
    runtimeclass PlaceInfoHelper
    {
        static Windows.Services.Maps.PlaceInfo CreateFromLocalLocation(LocalLocation location);
    }

}
