











namespace Windows.Internal.StateRepository
{
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [static_name("Windows.Internal.StateRepository.ICustomInstallProcessUserStatusStatics", 99de4b1b-555a-4d12-a863-1a9d6e59877f)]
    [interface_name("Windows.Internal.StateRepository.ICustomInstallProcessUserStatus", cffc909f-ad56-4446-bac4-8ec4379bc00d)]
    [threading(both)]
    runtimeclass CustomInstallProcessUserStatus
    {
        static Boolean Exists(Int64 customInstallProcessUserStatusID);
        static Boolean ExistsByCustomInstallProcess(CustomInstallProcess CustomInstallProcess);
        static Boolean ExistsByUser(User User);
        static Boolean ExistsByUserAndCustomInstallProcess(User User, CustomInstallProcess CustomInstallProcess);
        static Windows.Internal.StateRepository.CustomInstallProcessUserStatus TryGet(Int64 customInstallProcessUserStatusID);
        static Windows.Internal.StateRepository.CustomInstallProcessUserStatus TryGetByCustomInstallProcess(CustomInstallProcess CustomInstallProcess);
        static Windows.Internal.StateRepository.CustomInstallProcessUserStatus TryGetByUserAndCustomInstallProcess(User User, CustomInstallProcess CustomInstallProcess);
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.CustomInstallProcessUserStatus>  Find();
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.CustomInstallProcessUserStatus>  FindByUser(User User);
        static Windows.Internal.StateRepository.CustomInstallProcessUserStatus TryGetByUserAndCustomInstallProcessAnd_WorkId(User user, CustomInstallProcess customInstallProcess, Int64 workId);
        CustomInstallProcessUserStatus();
        Int64 _CustomInstallProcessStatusID{ get; };
        Int64 _CustomInstallProcessStatusID{ set; };
        UInt64 _Revision{ get; };
        UInt64 _Revision{ set; };
        Int64 CustomInstallProcess{ get; };
        Int64 CustomInstallProcess{ set; };
        Windows.Internal.StateRepository.CustomInstallProcess GetCustomInstallProcess();
        void SetCustomInstallProcess(CustomInstallProcess value);
        Int64 User{ get; };
        Int64 User{ set; };
        Windows.Internal.StateRepository.User GetUser();
        void SetUser(User value);
        Windows.Internal.StateRepository.CustomInstallProcessStatus Status{ get; };
        Windows.Internal.StateRepository.CustomInstallProcessStatus Status{ set; };
        Boolean Is_DictionaryNull{ get; };
        void Set_DictionaryToNull();
        void Get_Dictionary(out UInt8[] value);
        void Set_Dictionary(UInt8[] value);
        Windows.Foundation.Collections.IPropertySet Get_DictionaryAsPropertySet();
    }


}
