








namespace Windows.Internal.SpeechRecognition
{
    [contractversion(1)]
    [internal]
    apicontract SystemSpeechRecognitionContract{};

    [contract(Windows.Internal.SpeechRecognition.SystemSpeechRecognitionContract, 1)]
    enum SystemSpeechRecognizerType
    {
        Default,
        Cortana,
        Shell,
        SeeItSayIt,
        Dictation,
    };


    [contract(Windows.Internal.SpeechRecognition.SystemSpeechRecognitionContract, 1)]
    [static_name("Windows.Internal.SpeechRecognition.ISystemSpeechRecognizerFactoryStatics", 9fb45f16-cb93-44b9-8b57-159728d69ab6)]
    runtimeclass SystemSpeechRecognizerFactory
    {
        static Windows.Media.SpeechRecognition.SpeechRecognizer CreateSpeechRecognizer(Windows.Globalization.Language language, SystemSpeechRecognizerType type);
        static Windows.Media.SpeechRecognition.SpeechRecognizer CreateInprocSpeechRecognizer(Windows.Globalization.Language language);
    }

}
