





namespace Windows.Internal.UI.NetworkUX.NetworkIcon
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Internal.UI.NetworkUX.NetworkIcon.InternalContract, 1)]
    [uuid(beb4475f-f144-4b27-81f8-06bba3bf27a5)]
    interface IIconData
    {
        String UnderlayText{ get; };
        String BaseText{ get; };
        String OverlayText{ get; };
        String AltText{ get; };
        String ToolTipText{ get; };
    };

    [contract(Windows.Internal.UI.NetworkUX.NetworkIcon.InternalContract, 1)]
    [uuid(fd1f5a02-e156-4722-919a-d2887a1a1dfb)]
    delegate void NetworkIconEventHandler(Boolean requestDisplay, IIconData iconData);



    [contract(Windows.Internal.UI.NetworkUX.NetworkIcon.InternalContract, 1)]
    [constructor_name("Windows.Internal.UI.NetworkUX.NetworkIcon.INetworkIconFactory", e312f8eb-0392-4c54-b070-d720283162df)]
    [interface_name("Windows.Internal.UI.NetworkUX.NetworkIcon.INetworkIcon", f3acd868-52fb-430a-97ed-dfd4c0eb4b56)]
    runtimeclass NetworkIcon
    {
        [method_name( "CreateNetworkIcon" )] NetworkIcon(Boolean mapToConnectivity);
        void QueryInitialState();
        event Windows.Internal.UI.NetworkUX.NetworkIcon.NetworkIconEventHandler NetworkIconEvent;
    }

}
