





namespace Windows.Internal.PPI.CortanaHelpers
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};


    [contract(Windows.Internal.PPI.CortanaHelpers.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Internal.PPI.CortanaHelpers.ICortanaActionsStatics", 23497a42-0ac6-482b-a4f1-ecfa132a536b)]
    runtimeclass CortanaActions
    {
        static void EndSession();
    }

}
