






namespace Windows.Security.Authentication.Web.Provider
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum WebAccountProviderOperationKind
    {
        RequestToken,
        GetTokenSilently,
        AddAccount,
        ManageAccount,
        DeleteAccount,
        RetrieveCookies,
        SignOutAccount,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [uuid(6d5d2426-10b1-419a-a44e-f9c5161574e6)]
    interface IWebAccountProviderOperation
    {
        Windows.Security.Authentication.Web.Provider.WebAccountProviderOperationKind Kind{ get; };
    };

}
