











namespace Windows.Internal.StateRepository
{
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [static_name("Windows.Internal.StateRepository.IProvisionedPackageStatics", 91439a00-eb69-4e08-99eb-53ae0a6345cc)]
    [interface_name("Windows.Internal.StateRepository.IProvisionedPackage", a45f94a4-21e3-418b-9c42-b6b35e1499ee)]
    [threading(both)]
    runtimeclass ProvisionedPackage
    {
        static Boolean Exists(Int64 provisionedPackageID);
        static Boolean ExistsByPackageIdentity(PackageIdentity PackageIdentity);
        static Boolean ExistsByPath(String Path);
        static Windows.Internal.StateRepository.ProvisionedPackage TryGet(Int64 provisionedPackageID);
        static Windows.Internal.StateRepository.ProvisionedPackage TryGetByPackageIdentity(PackageIdentity PackageIdentity);
        static Windows.Internal.StateRepository.ProvisionedPackage TryGetByPath(String Path);
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.ProvisionedPackage>  Find();
        ProvisionedPackage();
        Int64 _ProvisionedPackageID{ get; };
        Int64 _ProvisionedPackageID{ set; };
        UInt64 _Revision{ get; };
        UInt64 _Revision{ set; };
        Int64 PackageIdentity{ get; };
        Int64 PackageIdentity{ set; };
        Windows.Internal.StateRepository.PackageIdentity GetPackageIdentity();
        void SetPackageIdentity(PackageIdentity value);
        Windows.Internal.StateRepository.ProvisionedPackageFlags Flags{ get; };
        Windows.Internal.StateRepository.ProvisionedPackageFlags Flags{ set; };
        Boolean DoNotKeepAfterPcReset{ get; };
        Boolean DoNotKeepAfterPcReset{ set; };
        Boolean RegisterOnlyForDefaultAccount{ get; };
        Boolean RegisterOnlyForDefaultAccount{ set; };
        String Path{ get; };
        String Path{ set; };
        Windows.Storage.StorageFolder GetPathAsStorageFolder();
        void SetPathAsStorageFolder(Windows.Storage.IStorageFolder value);
        Windows.Internal.StateRepository.SignatureOrigin SignatureOrigin{ get; };
        Windows.Internal.StateRepository.SignatureOrigin SignatureOrigin{ set; };
        Boolean IsRegionNull{ get; };
        void SetRegionToNull();
        String Region{ get; };
        String Region{ set; };
        Boolean Is_DictionaryNull{ get; };
        void Set_DictionaryToNull();
        void Get_Dictionary(out UInt8[] value);
        void Set_Dictionary(UInt8[] value);
        Windows.Foundation.Collections.IPropertySet Get_DictionaryAsPropertySet();
    }


}
