











namespace Windows.Media.Audio
{
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [static_name("Windows.Media.Audio.IAudioStateMonitorStatics", 6374ea4c-1b3b-4001-94d9-dd225330fa40)]
    [interface_name("Windows.Media.Audio.IAudioStateMonitor", 1d13d136-0199-4cdc-b84e-e72c2b581ece)]
    runtimeclass AudioStateMonitor
    {
        [method_name("CreateForRenderMonitoring")] static Windows.Media.Audio.AudioStateMonitor CreateForRenderMonitoring();
        [method_name("CreateForRenderMonitoringWithCategory")] static Windows.Media.Audio.AudioStateMonitor CreateForRenderMonitoring(Windows.Media.Render.AudioRenderCategory category);
        [method_name("CreateForRenderMonitoringWithCategoryAndDeviceRole")] static Windows.Media.Audio.AudioStateMonitor CreateForRenderMonitoring(Windows.Media.Render.AudioRenderCategory category, Windows.Media.Devices.AudioDeviceRole role);
        static Windows.Media.Audio.AudioStateMonitor CreateForRenderMonitoringWithCategoryAndDeviceId(Windows.Media.Render.AudioRenderCategory category, String deviceId);
        [method_name("CreateForCaptureMonitoring")] static Windows.Media.Audio.AudioStateMonitor CreateForCaptureMonitoring();
        [method_name("CreateForCaptureMonitoringWithCategory")] static Windows.Media.Audio.AudioStateMonitor CreateForCaptureMonitoring(Windows.Media.Capture.MediaCategory category);
        [method_name("CreateForCaptureMonitoringWithCategoryAndDeviceRole")] static Windows.Media.Audio.AudioStateMonitor CreateForCaptureMonitoring(Windows.Media.Capture.MediaCategory category, Windows.Media.Devices.AudioDeviceRole role);
        static Windows.Media.Audio.AudioStateMonitor CreateForCaptureMonitoringWithCategoryAndDeviceId(Windows.Media.Capture.MediaCategory category, String deviceId);
        event Windows.Foundation.TypedEventHandler <Windows.Media.Audio.AudioStateMonitor, Object>  SoundLevelChanged;
        Windows.Media.SoundLevel SoundLevel{ get; };
    }


}
