












namespace Windows.UI.Internal.Input
{
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [static_name("Windows.UI.Internal.Input.IInputSiteStatics", 8ca0442d-ae80-47b0-af23-813fc1da9cd0)]
    [default_interface]
    [interface_name("Windows.UI.Internal.Input.IInputSite", f77d91d0-46ca-4464-99c1-8902aed17680)]
    [threading(both)]
    runtimeclass InputSite
        : Windows.Foundation.IClosable
    {
        static Windows.UI.Internal.Input.InputSite GetForVisual(Windows.UI.Composition.Visual visual);
        static Windows.UI.Internal.Input.InputSite GetForHwnd(UInt64 hwndAsUInt64);
        static Windows.UI.Internal.Input.InputSite GetForCoreWindow(Windows.UI.Core.CoreWindow coreWindow);
        static Windows.UI.Internal.Input.InputSite GetForCoreComponentInputSource(Windows.UI.Core.ICoreInputSourceBase coreComponentInputSource);
        static Windows.UI.Internal.Input.InputSite GetForCoreIndependentInputSource(Windows.UI.Core.CoreIndependentInputSource coreIndependentInputSource);
        static Windows.UI.Internal.Input.InputSite CreateForIslandSite(Object visualIslandSite, InputSiteForIslandSitePartnerInterop interop);
        static Windows.UI.Internal.Input.InputSite GetOrCreateForIsland(Object visualTreeIsland);
        static void ConnectIsland(InputSite islandSiteInputSite, InputSite islandInputSite);
        static UInt64 ConnectIslandToCoreWindow(Windows.UI.Core.CoreWindow coreWindow, InputSite islandInputSite);
    }

    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [interface_name("Windows.UI.Internal.Input.IInputSiteForIslandSitePartnerInterop", 45e6425f-c995-4358-bc12-d02d78ac5bb2)]
    runtimeclass InputSiteForIslandSitePartnerInterop
    {
        UInt64 WindowId{ get; };
        UInt32 ViewInstanceId{ get; };
        Boolean SupportsActivation{ get; };
        Boolean UseWindowAsInputSource{ get; };
    }




    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [constructor_name("Windows.UI.Internal.Input.IInputObjectPartnerFactory", d7f24f8c-eb06-52d0-827e-94555464b9a4)]
    [interface_name("Windows.UI.Internal.Input.IInputObjectPartner", 29500e25-06ae-536c-af23-47682f700580)]
    [threading(both)]
    unsealed runtimeclass InputObjectPartner
        : Windows.Foundation.IClosable
    {
        Windows.UI.Internal.Input.InputSite InputSite{ get; };
        Windows.System.DispatcherQueue DispatcherQueue{ get; };
    }

}
