






namespace Windows.System.Profile
{
    [contract(Windows.Foundation.UniversalApiContract, 2)]
    enum PlatformDataCollectionLevel
    {
        Security,
        Basic,
        Enhanced,
        Full,
    };


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 2)]
    [static_name("Windows.System.Profile.IPlatformDiagnosticsAndUsageDataSettingsStatics", b6e24c1b-7b1c-4b32-8c62-a66597ce723a)]
    [threading(both)]
    runtimeclass PlatformDiagnosticsAndUsageDataSettings
    {
        static Windows.System.Profile.PlatformDataCollectionLevel CollectionLevel{ get; };
        static event Windows.Foundation.EventHandler <Object>  CollectionLevelChanged;
        static Boolean CanCollectDiagnostics(PlatformDataCollectionLevel level);
    }

}
