











namespace Windows.UI.Internal.Input
{
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.Internal.Input.IServerConnectionArgs", 9f292eff-5dca-4f8b-ac8d-e91d4485b1bf)]
    runtimeclass ServerConnectionArgs
    {
        Boolean IsServerConnected{ get; };
    }

    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [uuid(ee06bfee-4013-44ca-bf73-60becd27e538)]
    interface IServerConnection
    {
        Boolean IsServerConnected{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.IServerConnection, Windows.UI.Internal.Input.ServerConnectionArgs>  ServerConnectionChanged;
    };


    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [static_name("Windows.UI.Internal.Input.IMPCInputObjectStatics", 4b3a30eb-157a-5c15-a5ac-54f1c447d2ff)]
    [interface_name("Windows.UI.Internal.Input.IMPCInputObject", 08c7cfa3-9ee2-43db-aa5b-3e09e09d6358)]
    [threading(both)]
    runtimeclass MPCInputObject
        : Windows.UI.Internal.Input.InputObjectPartner
        , Windows.UI.Internal.Input.IServerConnection
    {
        static Windows.UI.Internal.Input.MPCInputObject GetForInputSite(InputSite inputSite);
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.MPCInputObject, Windows.UI.Input.Spatial.Internal.PrivHandEventArgs>  HandEvent;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.MPCInputObject, Windows.UI.Input.Spatial.Internal.PrivVoiceEventArgs>  VoiceEvent;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.MPCInputObject, Windows.UI.Input.Spatial.Internal.PrivAugmentedInputEventArgs>  AugmentedInputEvent;
        UInt32 EventSubscriptions{ get; };
        UInt32 EventSubscriptions{ set; };
        Boolean CalledGetDetectedSourcesAtTimestampRecently{ get; };
        Boolean CalledGetDetectedSourcesAtTimestampRecently{ set; };
    }


}
