








namespace Windows.UI.Internal.Core
{
    [contractversion(1)]
    [internal]
    apicontract CoreDispatcherInternalContract{};

    [contract(Windows.UI.Internal.Core.CoreDispatcherInternalContract, 1)]
    enum CoreAcceleratorKeyRoutingStage
    {
        Tunneling,
        Bubbling,
    };


    [uuid(5e59ac10-7e1f-43b2-93b9-f3fb1597dea3)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Core.CoreDispatcherInternalContract, 1)]
    interface ICoreRoutedAcceleratorKeys
    {
        event Windows.Foundation.TypedEventHandler <Windows.UI.Core.CoreDispatcher, Windows.UI.Internal.Core.RoutedAcceleratorKeyEventArgs>  RoutedAcceleratorKeyActivated;
    };

    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Core.CoreDispatcherInternalContract, 1)]
    [interface_name("Windows.UI.Internal.Core.IRoutedAcceleratorKeyEventArgs", 98d4efed-8757-4449-8ae6-06c69236e2df)]
    runtimeclass RoutedAcceleratorKeyEventArgs
        : Windows.UI.Core.ICoreWindowEventArgs
    {
        Windows.UI.Core.CoreAcceleratorKeyEventType EventType{ get; };
        Windows.System.VirtualKey VirtualKey{ get; };
        Windows.UI.Core.CorePhysicalKeyStatus KeyStatus{ get; };
        Windows.UI.Internal.Core.CoreAcceleratorKeyRoutingStage RoutingStage{ get; };
        Boolean RequestActivation{ get; };
        Boolean RequestActivation{ set; };
        String DeviceId{ get; };
    }

}
