








namespace Windows.System.UserProfile
{
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.System.UserProfile.IFirstSignInSettingsStatics", 1ce18f0f-1c41-4ea0-b7a2-6f0c1c7e8438)]
    [default_interface]
    [interface_name("Windows.System.UserProfile.IFirstSignInSettings", 3e945153-3a5e-452e-a601-f5baad2a4870)]
    [threading(both)]
    runtimeclass FirstSignInSettings
        : Windows.Foundation.Collections.IMapView<String, Object>
        , Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, Object> >
    {
        static Windows.System.UserProfile.FirstSignInSettings GetDefault();
    }

}
