






namespace Windows.Devices.Pwm.Provider
{
    [contract(Windows.Devices.DevicesLowLevelContract, 1)]
    [uuid(1300593b-e2e3-40a4-b7d9-48dff0377a52)]
    interface IPwmControllerProvider
    {
        Int32 PinCount{ get; };
        Double ActualFrequency{ get; };
        Double SetDesiredFrequency(Double frequency);
        Double MaxFrequency{ get; };
        Double MinFrequency{ get; };
        void AcquirePin(Int32 pin);
        void ReleasePin(Int32 pin);
        void EnablePin(Int32 pin);
        void DisablePin(Int32 pin);
        void SetPulseParameters(Int32 pin, Double dutyCycle, Boolean invertPolarity);
    };

    [contract(Windows.Devices.DevicesLowLevelContract, 1)]
    [uuid(a3301228-52f1-47b0-9349-66ba43d25902)]
    interface IPwmProvider
    {
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Pwm.Provider.IPwmControllerProvider>  GetControllers();
    };

}
