











namespace Windows.Internal.StateRepository
{
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [static_name("Windows.Internal.StateRepository.IAppExecutionAliasUserStatics", 344b30fe-a41d-445f-9647-71c726a7ed72)]
    [interface_name("Windows.Internal.StateRepository.IAppExecutionAliasUser", 25e7da82-5a07-42b3-8e5e-9d3b990f2164)]
    [threading(both)]
    runtimeclass AppExecutionAliasUser
    {
        AppExecutionAliasUser();
        static void Add(AppExecutionAliasUser value);
        static void Update(AppExecutionAliasUser value);
        static void Delete(AppExecutionAliasUser value);
        static void DeleteById(Int64 appExecutionAliasUserID);
        static void DeleteByApplicationIdentityAndUser(ApplicationIdentity ApplicationIdentity, User User);
        static Boolean Exists(Int64 appExecutionAliasUserID);
        static Boolean ExistsByApplicationIdentity(ApplicationIdentity ApplicationIdentity);
        static Boolean ExistsByApplicationIdentityAndUser(ApplicationIdentity ApplicationIdentity, User User);
        static Boolean ExistsByUser(User User);
        static Windows.Internal.StateRepository.AppExecutionAliasUser Get(Int64 appExecutionAliasUserID);
        static Windows.Internal.StateRepository.AppExecutionAliasUser TryGet(Int64 appExecutionAliasUserID);
        static Windows.Internal.StateRepository.AppExecutionAliasUser GetByApplicationIdentityAndUser(ApplicationIdentity ApplicationIdentity, User User);
        static Windows.Internal.StateRepository.AppExecutionAliasUser TryGetByApplicationIdentityAndUser(ApplicationIdentity ApplicationIdentity, User User);
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.AppExecutionAliasUser>  Find();
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.AppExecutionAliasUser>  FindByApplicationIdentity(ApplicationIdentity ApplicationIdentity);
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.AppExecutionAliasUser>  FindByUser(User User);
        Int64 _AppExecutionAliasUserID{ get; };
        Int64 _AppExecutionAliasUserID{ set; };
        UInt64 _Revision{ get; };
        UInt64 _Revision{ set; };
        Int64 User{ get; };
        Int64 User{ set; };
        Windows.Internal.StateRepository.User GetUser();
        void SetUser(User value);
        Int64 ApplicationIdentity{ get; };
        Int64 ApplicationIdentity{ set; };
        Windows.Internal.StateRepository.ApplicationIdentity GetApplicationIdentity();
        void SetApplicationIdentity(ApplicationIdentity value);
        Windows.Internal.StateRepository.AppExecutionAliasStatus Status{ get; };
        Windows.Internal.StateRepository.AppExecutionAliasStatus Status{ set; };
        Boolean Is_DictionaryNull{ get; };
        void Set_DictionaryToNull();
        void Get_Dictionary(out UInt8[] value);
        void Set_Dictionary(UInt8[] value);
        Windows.Foundation.Collections.IPropertySet Get_DictionaryAsPropertySet();
    }


}
