











namespace Windows.UI.Input.Core
{
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000003)]
    [contract(Windows.Foundation.UniversalApiContract, 4)]
    [static_name("Windows.UI.Input.Core.IRadialControllerIndependentInputSourceStatics", 3d577ef5-4cee-11e6-b535-001bdc06ab3b)]
    [interface_name("Windows.UI.Input.Core.IRadialControllerIndependentInputSource", 3d577ef6-4cee-11e6-b535-001bdc06ab3b)]
    runtimeclass RadialControllerIndependentInputSource
    {
        static Windows.UI.Input.Core.RadialControllerIndependentInputSource CreateForView(Windows.ApplicationModel.Core.CoreApplicationView view);
        Windows.UI.Input.RadialController Controller{ get; };
        Windows.UI.Core.CoreDispatcher Dispatcher{ get; };

        [contract(Windows.Foundation.UniversalApiContract, 6)]
        [interface_name("Windows.UI.Input.Core.IRadialControllerIndependentInputSource2", 7073aad8-35f3-4eeb-8751-be4d0a66faf4)]
        {
            Windows.System.DispatcherQueue DispatcherQueue{ get; };
        }
    }



}
