








namespace Windows.System.Internal.WCOS
{
    [contractversion(1)]
    [internal]
    apicontract UserContract{};

    [contract(Windows.System.Internal.WCOS.UserContract, 1)]
    enum UserType
    {
        Unknown,
        DefaultUser,
        Resource,
        Visitor,
        InteractiveUser,
    };


    [contract(Windows.System.Internal.WCOS.UserContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.Internal.WCOS.ISignInResult", 506bfb7a-bc18-43ee-8972-2c1a499d7bb8)]
    runtimeclass SignInResult
    {
        HRESULT Status{ get; };
        HRESULT Substatus{ get; };
        UInt32 UserId{ get; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.System.Internal.WCOS.UserContract, 1)]
    [static_name("Windows.System.Internal.WCOS.IWCOSUserManagerStatics", 730ee0a8-cf39-4164-8133-bf1aaed3c999)]
    [threading(both)]
    runtimeclass WCOSUserManager
    {
        static Windows.Foundation.IAsyncOperation <Windows.System.Internal.WCOS.SignInResult>  SignInVisitorUserAsync(String displayName);
        static Windows.Foundation.IAsyncAction SignOutVisitorUserAsync(Windows.System.User user);
        static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.System.User> >  GetVisitorUsersAsync();
        static Windows.Foundation.IAsyncOperation <Windows.System.Internal.WCOS.SignInResult>  CreateResourceUserAsync(Windows.System.Internal.CredentialSerialization creds);
        static Windows.Foundation.IAsyncOperation <Windows.System.Internal.WCOS.SignInResult>  SignInResourceUserAsync();
        static Windows.Foundation.IAsyncAction SignOutResourceUserAsync();
        static Windows.Foundation.IAsyncAction DeleteResourceUserAsync();
        static Windows.Foundation.IAsyncOperation <Windows.System.User>  GetResourceUserAsync();
        static Windows.Foundation.IAsyncOperation <Windows.System.User>  GetDefaultServiceUserAsync();
    }

}
