










namespace Windows.Devices.Input
{
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0x1)]
    [static_name("Windows.Devices.Input.IPenDeviceStatics", 9dfbbe01-0966-5180-bcb4-b85060e39479)]
    [interface_name("Windows.Devices.Input.IPenDevice", 31856eba-a738-5a8c-b8f6-f97ef68d18ef)]
    [threading(both)]
    runtimeclass PenDevice
    {
        static Windows.Devices.Input.PenDevice GetFromPointerId(UInt32 pointerId);
        Guid PenId{ get; };

        [feature(Velocity_SometimesAlwaysDisabled)]
        [interface_name("Windows.Devices.Input.IPenDevice2", 0207d327-7fb8-5566-8c34-f8342037b7f9)]
        {
            Windows.Devices.Haptics.SimpleHapticsController SimpleHapticsController{ get; };
        }
    }

}
