











namespace Windows.Devices.PointOfService.Provider
{
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    enum BarcodeScannerTriggerState
    {
        Released,
        Pressed,
    };



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerEnableScannerRequest", c0b3e9ba-816a-452b-bd77-b7e453ec446d)]
    runtimeclass BarcodeScannerEnableScannerRequest
    {
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerEnableScannerRequest2", 71a4f2a8-9905-41ac-9121-b645916a84a1)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerEnableScannerRequestEventArgs", 956c9419-7b4e-4451-8c41-8e10cfbc5b41)]
    runtimeclass BarcodeScannerEnableScannerRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerEnableScannerRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerDisableScannerRequest", 88ecf7c0-37b9-4275-8e77-c8e52ae5a9c8)]
    runtimeclass BarcodeScannerDisableScannerRequest
    {
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerDisableScannerRequest2", ccdfe625-65c3-4ccc-b457-f39c7a9ea60d)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerDisableScannerRequestEventArgs", 7006e142-e802-46f5-b604-352a15ce9232)]
    runtimeclass BarcodeScannerDisableScannerRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerDisableScannerRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerSetActiveSymbologiesRequest", db3f32b9-f7da-41a1-9f79-07bcd95f0bdf)]
    runtimeclass BarcodeScannerSetActiveSymbologiesRequest
    {
        Windows.Foundation.Collections.IVectorView <UInt32>  Symbologies{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerSetActiveSymbologiesRequest2", f5ff6edf-fa9a-4749-b11b-e8fccb75bc6b)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerSetActiveSymbologiesRequestEventArgs", 06305afa-7bf6-4d52-801a-330272f60ae1)]
    runtimeclass BarcodeScannerSetActiveSymbologiesRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerSetActiveSymbologiesRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }



    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerStartSoftwareTriggerRequest", e3fa7b27-ff62-4454-af4a-cb6144a3e3f7)]
    runtimeclass BarcodeScannerStartSoftwareTriggerRequest
    {
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerStartSoftwareTriggerRequest2", eb72a25c-6658-4765-a68e-327482653deb)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerStartSoftwareTriggerRequestEventArgs", 2305d843-c88f-4f3b-8c3b-d3df071051ec)]
    runtimeclass BarcodeScannerStartSoftwareTriggerRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerStartSoftwareTriggerRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerStopSoftwareTriggerRequest", 6f9faf35-e287-4ca8-b70d-5a91d694f668)]
    runtimeclass BarcodeScannerStopSoftwareTriggerRequest
    {
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerStopSoftwareTriggerRequest2", cb57c5dd-fe50-49f8-a0b4-bdc230814da2)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerStopSoftwareTriggerRequestEventArgs", eac34450-4eb7-481a-9273-147a273b99b8)]
    runtimeclass BarcodeScannerStopSoftwareTriggerRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerStopSoftwareTriggerRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeSymbologyAttributesBuilder", c57b0cbf-e4f5-40b9-84cf-e63fbaea42b4)]
    [threading(both)]
    runtimeclass BarcodeSymbologyAttributesBuilder
    {
        BarcodeSymbologyAttributesBuilder();
        Boolean IsCheckDigitValidationSupported{ get; };
        Boolean IsCheckDigitValidationSupported{ set; };
        Boolean IsCheckDigitTransmissionSupported{ get; };
        Boolean IsCheckDigitTransmissionSupported{ set; };
        Boolean IsDecodeLengthSupported{ get; };
        Boolean IsDecodeLengthSupported{ set; };
        Windows.Devices.PointOfService.BarcodeSymbologyAttributes CreateAttributes();
    }



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerGetSymbologyAttributesRequest", 9774c46a-58e4-4c5f-b8e9-e41467632700)]
    runtimeclass BarcodeScannerGetSymbologyAttributesRequest
    {
        UInt32 Symbology{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.BarcodeSymbologyAttributes attributes);
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerGetSymbologyAttributesRequest2", 6a6a2b13-75a8-49fb-b852-bfb93d760af7)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerGetSymbologyAttributesRequestEventArgs", 7f89de3e-fb5d-493c-b402-356b24d574a6)]
    runtimeclass BarcodeScannerGetSymbologyAttributesRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerGetSymbologyAttributesRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerSetSymbologyAttributesRequest", 32fb814f-a37f-48b0-acea-dce1480f12ae)]
    runtimeclass BarcodeScannerSetSymbologyAttributesRequest
    {
        UInt32 Symbology{ get; };
        Windows.Devices.PointOfService.BarcodeSymbologyAttributes Attributes{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerSetSymbologyAttributesRequest2", dffbbfc1-dba8-4b77-be1e-b56cd72f65b3)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerSetSymbologyAttributesRequestEventArgs", b2b89809-9824-47d4-85bd-d0077baa7bd2)]
    runtimeclass BarcodeScannerSetSymbologyAttributesRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerSetSymbologyAttributesRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }



    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerHideVideoPreviewRequest", fa4ebe7f-6670-40e1-b90b-bb10d8d425fa)]
    runtimeclass BarcodeScannerHideVideoPreviewRequest
    {
        Windows.Foundation.IAsyncAction ReportCompletedAsync();
        Windows.Foundation.IAsyncAction ReportFailedAsync();

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerHideVideoPreviewRequest2", 7e28435d-9814-431d-a2f2-d6248c5ad4b5)]
        {
            [method_name("ReportFailedWithFailedReasonAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason);
            [method_name("ReportFailedWithFailedReasonAndDescriptionAsync")] Windows.Foundation.IAsyncAction ReportFailedAsync(Int32 reason, String failedReasonDescription);
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerHideVideoPreviewRequestEventArgs", 16a281fc-d6be-4bc7-9df1-33741f3eadea)]
    runtimeclass BarcodeScannerHideVideoPreviewRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerHideVideoPreviewRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerProviderConnection", b44acbed-0b3a-4fa3-86c5-491ea30780eb)]
    runtimeclass BarcodeScannerProviderConnection
        : Windows.Foundation.IClosable
    {
        String Id{ get; };
        String VideoDeviceId{ get; };
        Windows.Foundation.Collections.IVector <UInt32>  SupportedSymbologies{ get; };
        String CompanyName{ get; };
        String CompanyName{ set; };
        String Name{ get; };
        String Name{ set; };
        String Version{ get; };
        String Version{ set; };
        void Start();
        Windows.Foundation.IAsyncAction ReportScannedDataAsync(Windows.Devices.PointOfService.BarcodeScannerReport report);
        Windows.Foundation.IAsyncAction ReportTriggerStateAsync(BarcodeScannerTriggerState state);
        [method_name("ReportErrorAsync")] Windows.Foundation.IAsyncAction ReportErrorAsync(Windows.Devices.PointOfService.UnifiedPosErrorData errorData);
        [method_name("ReportErrorAsyncWithScanReport")] Windows.Foundation.IAsyncAction ReportErrorAsync(Windows.Devices.PointOfService.UnifiedPosErrorData errorData, Boolean isRetriable, Windows.Devices.PointOfService.BarcodeScannerReport scanReport);
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerEnableScannerRequestEventArgs>  EnableScannerRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerDisableScannerRequestEventArgs>  DisableScannerRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerSetActiveSymbologiesRequestEventArgs>  SetActiveSymbologiesRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerStartSoftwareTriggerRequestEventArgs>  StartSoftwareTriggerRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerStopSoftwareTriggerRequestEventArgs>  StopSoftwareTriggerRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerGetSymbologyAttributesRequestEventArgs>  GetBarcodeSymbologyAttributesRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerSetSymbologyAttributesRequestEventArgs>  SetBarcodeSymbologyAttributesRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection, Windows.Devices.PointOfService.Provider.BarcodeScannerHideVideoPreviewRequestEventArgs>  HideVideoPreviewRequested;

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerProviderConnection2", be9b53cd-1134-418c-a06b-04423a73f3d7)]
        {
            [method_name("CreateFrameReaderAsync")] Windows.Foundation.IAsyncOperation <Windows.Devices.PointOfService.Provider.BarcodeScannerFrameReader>  CreateFrameReaderAsync();
            [method_name("CreateFrameReaderWithFormatAsync")] Windows.Foundation.IAsyncOperation <Windows.Devices.PointOfService.Provider.BarcodeScannerFrameReader>  CreateFrameReaderAsync(Windows.Graphics.Imaging.BitmapPixelFormat preferredFormat);
            [method_name("CreateFrameReaderWithFormatAndSizeAsync")] Windows.Foundation.IAsyncOperation <Windows.Devices.PointOfService.Provider.BarcodeScannerFrameReader>  CreateFrameReaderAsync(Windows.Graphics.Imaging.BitmapPixelFormat preferredFormat, Windows.Graphics.Imaging.BitmapSize preferredSize);
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerFrameReader", dbc72b07-64c3-482b-93c8-65fb33c22208)]
    runtimeclass BarcodeScannerFrameReader
        : Windows.Foundation.IClosable
    {
        Windows.Foundation.IAsyncOperation <Boolean>  StartAsync();
        Windows.Foundation.IAsyncAction StopAsync();
        Windows.Foundation.IAsyncOperation <Windows.Devices.PointOfService.Provider.BarcodeScannerVideoFrame>  TryAcquireLatestFrameAsync();
        Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection Connection{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.BarcodeScannerFrameReader, Windows.Devices.PointOfService.Provider.BarcodeScannerFrameReaderFrameArrivedEventArgs>  FrameArrived;
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerVideoFrame", 7e585248-9df7-4121-a175-801d8000112e)]
    runtimeclass BarcodeScannerVideoFrame
        : Windows.Foundation.IClosable
    {
        Windows.Graphics.Imaging.BitmapPixelFormat Format{ get; };
        UInt32 Width{ get; };
        UInt32 Height{ get; };
        Windows.Storage.Streams.IBuffer PixelData{ get; };
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerFrameReaderFrameArrivedEventArgs", b0bbd604-54fd-436d-8629-712e787223dd)]
    runtimeclass BarcodeScannerFrameReaderFrameArrivedEventArgs
    {
        Windows.Foundation.Deferral GetDeferral();
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Devices.PointOfService.Provider.IBarcodeScannerProviderTriggerDetails", 50856d82-24e3-48ce-99c7-70aac1cbc9f7)]
    runtimeclass BarcodeScannerProviderTriggerDetails
    {
        Windows.Devices.PointOfService.Provider.BarcodeScannerProviderConnection Connection{ get; };
    }




    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceGetTerminalsRequest", c2a6ddf3-be65-416d-b423-4331a81ee63f)]
    runtimeclass PaymentDeviceGetTerminalsRequest
    {
        Windows.Foundation.Collections.IVector <String>  TerminalIds{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceGetTerminalsRequestEventArgs", f6c83255-0bd7-4445-8f22-f6db7810c3db)]
    runtimeclass PaymentDeviceGetTerminalsRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceGetTerminalsRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceOpenTerminalRequest", 9c3d9fd5-1d4e-4c26-85d6-b16c5febfbb9)]
    runtimeclass PaymentDeviceOpenTerminalRequest
    {
        String TerminalId{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceOpenTerminalRequestEventArgs", e7b91384-bc3f-4843-8f35-7fcdcb97d7ab)]
    runtimeclass PaymentDeviceOpenTerminalRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceOpenTerminalRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceCloseTerminalRequest", 664af9b4-944b-416d-acee-65dfd0f1acee)]
    runtimeclass PaymentDeviceCloseTerminalRequest
    {
        String TerminalId{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceCloseTerminalRequestEventArgs", dbb54dad-276e-4651-a95f-ed656f300f1e)]
    runtimeclass PaymentDeviceCloseTerminalRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceCloseTerminalRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceReadCapabilitiesRequest", c24b5d70-0cfe-4c7e-972a-0657217a3a22)]
    runtimeclass PaymentDeviceReadCapabilitiesRequest
    {
        String TerminalManufacturer{ get; };
        String TerminalManufacturer{ set; };
        String TerminalModel{ get; };
        String TerminalModel{ set; };
        String TerminalOSVersion{ get; };
        String TerminalOSVersion{ set; };
        String TerminalSerialNumber{ get; };
        String TerminalSerialNumber{ set; };
        Windows.Foundation.Collections.IVector <Windows.Devices.PointOfService.PaymentMethodKind>  SupportedPaymentMethodKinds{ get; };
        Windows.Foundation.Collections.IVector <String>  SupportedPaymentMethodKindDescriptions{ get; };
        Windows.Foundation.Collections.IVector <String>  SupportedCurrencies{ get; };
        String DefaultCurrency{ get; };
        String DefaultCurrency{ set; };
        Boolean IsTokenizationSupported{ get; };
        Boolean IsTokenizationSupported{ set; };
        Boolean IsAvsSupported{ get; };
        Boolean IsAvsSupported{ set; };
        Boolean HasTrainingMode{ get; };
        Boolean HasTrainingMode{ set; };
        Boolean HasDisplay{ get; };
        Boolean HasDisplay{ set; };
        Boolean CanAskYesNoQuestion{ get; };
        Boolean CanAskYesNoQuestion{ set; };
        Boolean CanRequestEmail{ get; };
        Boolean CanRequestEmail{ set; };
        Boolean CanRequestTip{ get; };
        Boolean CanRequestTip{ set; };
        Boolean CanRequestDonation{ get; };
        Boolean CanRequestDonation{ set; };
        Boolean CanDisplayImage{ get; };
        Boolean CanDisplayImage{ set; };
        Boolean CanDisplayQRCode{ get; };
        Boolean CanDisplayQRCode{ set; };
        Boolean CanPrint{ get; };
        Boolean CanPrint{ set; };
        Boolean CanAutoPrintReceipts{ get; };
        Boolean CanAutoPrintReceipts{ set; };
        Windows.Foundation.Collections.IVector <String>  SupportedReportKinds{ get; };
        Windows.Foundation.Collections.IVector <String>  SupportedContentTypes{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceReadCapabilitiesRequestEventArgs", 9f310793-9bb8-4e4a-8a8d-fe5dd4982511)]
    runtimeclass PaymentDeviceReadCapabilitiesRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceReadCapabilitiesRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceReadConfigurationRequest", eb8c3c80-330f-4aed-b0e4-13048f93ae66)]
    runtimeclass PaymentDeviceReadConfigurationRequest
    {
        String TerminalName{ get; };
        String TerminalName{ set; };
        String TerminalLocation{ get; };
        String TerminalLocation{ set; };
        Windows.Foundation.DateTime TerminalDateTime{ set; };
        Windows.Foundation.DateTime TerminalDateTime{ get; };
        Boolean IsTokenizationEnabled{ get; };
        Boolean IsTokenizationEnabled{ set; };
        String TipText{ get; };
        String TipText{ set; };
        String EmailAddressText{ get; };
        String EmailAddressText{ set; };
        String DonationText{ get; };
        String DonationText{ set; };
        Boolean IsAutoPrintReceiptsEnabled{ get; };
        Boolean IsAutoPrintReceiptsEnabled{ set; };
        Boolean IsTrainingModeEnabled{ get; };
        Boolean IsTrainingModeEnabled{ set; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceReadConfigurationRequestEventArgs", 153efd46-f73b-4262-bb62-65ef1b5c16dd)]
    runtimeclass PaymentDeviceReadConfigurationRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceReadConfigurationRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceWriteConfigurationRequest", 3d6db821-890a-45dc-98cc-8e5693aa99fb)]
    runtimeclass PaymentDeviceWriteConfigurationRequest
    {
        String TerminalName{ get; };
        String TerminalLocation{ get; };
        Windows.Foundation.DateTime TerminalDateTime{ get; };
        Boolean IsTokenizationEnabled{ get; };
        String TipText{ get; };
        String EmailAddressText{ get; };
        String DonationText{ get; };
        Boolean IsAutoPrintReceiptsEnabled{ get; };
        Boolean IsTrainingModeEnabled{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceWriteConfigurationRequestEventArgs", c05613c7-900d-4b51-b875-0be4df1a1251)]
    runtimeclass PaymentDeviceWriteConfigurationRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceWriteConfigurationRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDevicePaymentAuthorizationRequest", 09895589-9a9b-4d27-9adb-8a8d4af5f3dc)]
    runtimeclass PaymentDevicePaymentAuthorizationRequest
    {
        String CashierName{ get; };
        Windows.Globalization.CurrencyAmount RequestedAmount{ get; };
        Windows.Globalization.CurrencyAmount RequestedCashBack{ get; };
        String AuthorizationCode{ get; };
        String TokenId{ get; };
        String AvsPostalCode{ get; };
        String AvsAddress{ get; };
        Boolean RequestTip{ get; };
        Boolean RequestDonation{ get; };
        Boolean RequestEmail{ get; };
        Boolean RequestAccountBalance{ get; };
        Boolean RequestSignature{ get; };
        String AuthorizationRequiredText{ get; };
        String AuthorizationRequiredText{ set; };
        String TransactionId{ get; };
        String TransactionId{ set; };
        String OutputAuthorizationCode{ get; };
        String OutputAuthorizationCode{ set; };
        String OutputTokenId{ get; };
        String OutputTokenId{ set; };
        String AvsCode{ get; };
        String AvsCode{ set; };
        Windows.Devices.PointOfService.PaymentMethodKind MethodOfPaymentKind{ get; };
        Windows.Devices.PointOfService.PaymentMethodKind MethodOfPaymentKind{ set; };
        String MethodOfPaymentDescription{ get; };
        String MethodOfPaymentDescription{ set; };
        String AccountHolderName{ get; };
        String AccountHolderName{ set; };
        String AccountIssuerName{ get; };
        String AccountIssuerName{ set; };
        String AccountLast4Digits{ get; };
        String AccountLast4Digits{ set; };
        Windows.Globalization.CurrencyAmount AuthorizedAmount{ get; };
        Windows.Globalization.CurrencyAmount AuthorizedAmount{ set; };
        Windows.Globalization.CurrencyAmount Tip{ get; };
        Windows.Globalization.CurrencyAmount Tip{ set; };
        Windows.Globalization.CurrencyAmount Donation{ get; };
        Windows.Globalization.CurrencyAmount Donation{ set; };
        Windows.Globalization.CurrencyAmount CashBack{ get; };
        Windows.Globalization.CurrencyAmount CashBack{ set; };
        Windows.Globalization.CurrencyAmount AccountBalance{ get; };
        Windows.Globalization.CurrencyAmount AccountBalance{ set; };
        String CustomerEmail{ get; };
        String CustomerEmail{ set; };
        Windows.Storage.Streams.IBuffer CustomerSignature{ get; };
        Windows.Storage.Streams.IBuffer CustomerSignature{ set; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDevicePaymentAuthorizationRequestEventArgs", f9e98a60-1059-4576-b5db-74365964d3b2)]
    runtimeclass PaymentDevicePaymentAuthorizationRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDevicePaymentAuthorizationRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDevicePaymentRequest", 081d5c54-6b84-4290-9efa-741f45ec9b57)]
    runtimeclass PaymentDevicePaymentRequest
    {
        String CashierName{ get; };
        Windows.Globalization.CurrencyAmount RequestedAmount{ get; };
        Windows.Globalization.CurrencyAmount RequestedCashBack{ get; };
        String AuthorizationCode{ get; };
        String TokenId{ get; };
        String AvsPostalCode{ get; };
        String AvsAddress{ get; };
        Boolean RequestTip{ get; };
        Boolean RequestDonation{ get; };
        Boolean RequestEmail{ get; };
        Boolean RequestAccountBalance{ get; };
        Boolean RequestSignature{ get; };
        String AuthorizationRequiredText{ get; };
        String AuthorizationRequiredText{ set; };
        String TransactionId{ get; };
        String TransactionId{ set; };
        String OutputAuthorizationCode{ get; };
        String OutputAuthorizationCode{ set; };
        String OutputTokenId{ get; };
        String OutputTokenId{ set; };
        String AvsCode{ get; };
        String AvsCode{ set; };
        Windows.Devices.PointOfService.PaymentMethodKind MethodOfPaymentKind{ get; };
        Windows.Devices.PointOfService.PaymentMethodKind MethodOfPaymentKind{ set; };
        String MethodOfPaymentDescription{ get; };
        String MethodOfPaymentDescription{ set; };
        String AccountHolderName{ get; };
        String AccountHolderName{ set; };
        String AccountIssuerName{ get; };
        String AccountIssuerName{ set; };
        String AccountLast4Digits{ get; };
        String AccountLast4Digits{ set; };
        Windows.Globalization.CurrencyAmount AuthorizedAmount{ get; };
        Windows.Globalization.CurrencyAmount AuthorizedAmount{ set; };
        Windows.Globalization.CurrencyAmount Tip{ get; };
        Windows.Globalization.CurrencyAmount Tip{ set; };
        Windows.Globalization.CurrencyAmount Donation{ get; };
        Windows.Globalization.CurrencyAmount Donation{ set; };
        Windows.Globalization.CurrencyAmount CashBack{ get; };
        Windows.Globalization.CurrencyAmount CashBack{ set; };
        Windows.Globalization.CurrencyAmount AccountBalance{ get; };
        Windows.Globalization.CurrencyAmount AccountBalance{ set; };
        String CustomerEmail{ get; };
        String CustomerEmail{ set; };
        Windows.Storage.Streams.IBuffer CustomerSignature{ get; };
        Windows.Storage.Streams.IBuffer CustomerSignature{ set; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDevicePaymentRequestEventArgs", 9103ac76-f588-4e57-beaa-36d595f8bf8c)]
    runtimeclass PaymentDevicePaymentRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDevicePaymentRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceRefundRequest", 96f1739e-81fa-4d22-a42b-68c63c5c2ff8)]
    runtimeclass PaymentDeviceRefundRequest
    {
        String CashierName{ get; };
        Windows.Globalization.CurrencyAmount RequestedAmount{ get; };
        Windows.Globalization.CurrencyAmount RequestedCashBack{ get; };
        String AuthorizationCode{ get; };
        String TokenId{ get; };
        String AvsPostalCode{ get; };
        String AvsAddress{ get; };
        Boolean RequestTip{ get; };
        Boolean RequestDonation{ get; };
        Boolean RequestEmail{ get; };
        Boolean RequestAccountBalance{ get; };
        Boolean RequestSignature{ get; };
        String AuthorizationRequiredText{ get; };
        String AuthorizationRequiredText{ set; };
        String TransactionId{ get; };
        String TransactionId{ set; };
        String OutputAuthorizationCode{ get; };
        String OutputAuthorizationCode{ set; };
        String OutputTokenId{ get; };
        String OutputTokenId{ set; };
        String AvsCode{ get; };
        String AvsCode{ set; };
        Windows.Devices.PointOfService.PaymentMethodKind MethodOfPaymentKind{ get; };
        Windows.Devices.PointOfService.PaymentMethodKind MethodOfPaymentKind{ set; };
        String MethodOfPaymentDescription{ get; };
        String MethodOfPaymentDescription{ set; };
        String AccountHolderName{ get; };
        String AccountHolderName{ set; };
        String AccountIssuerName{ get; };
        String AccountIssuerName{ set; };
        String AccountLast4Digits{ get; };
        String AccountLast4Digits{ set; };
        Windows.Globalization.CurrencyAmount AuthorizedAmount{ get; };
        Windows.Globalization.CurrencyAmount AuthorizedAmount{ set; };
        Windows.Globalization.CurrencyAmount Tip{ get; };
        Windows.Globalization.CurrencyAmount Tip{ set; };
        Windows.Globalization.CurrencyAmount Donation{ get; };
        Windows.Globalization.CurrencyAmount Donation{ set; };
        Windows.Globalization.CurrencyAmount CashBack{ get; };
        Windows.Globalization.CurrencyAmount CashBack{ set; };
        Windows.Globalization.CurrencyAmount AccountBalance{ get; };
        Windows.Globalization.CurrencyAmount AccountBalance{ set; };
        String CustomerEmail{ get; };
        String CustomerEmail{ set; };
        Windows.Storage.Streams.IBuffer CustomerSignature{ get; };
        Windows.Storage.Streams.IBuffer CustomerSignature{ set; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceRefundRequestEventArgs", 71f8153b-c010-42ed-8885-efa0a2376a67)]
    runtimeclass PaymentDeviceRefundRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceRefundRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceVoidTransactionRequest", da8b7b26-32ba-40ac-a16b-a0f582f883c5)]
    runtimeclass PaymentDeviceVoidTransactionRequest
    {
        String TransactionId{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceVoidTransactionRequestEventArgs", 97a74252-114c-4b32-9b54-9a98f890ee1c)]
    runtimeclass PaymentDeviceVoidTransactionRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceVoidTransactionRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceVoidTokenRequest", 7dca9e88-15b8-443a-9a2e-bca8cb618bd0)]
    runtimeclass PaymentDeviceVoidTokenRequest
    {
        String TokenId{ get; };
        Windows.Foundation.IAsyncAction ReportCompletedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
        Windows.Foundation.IAsyncAction ReportFailedAsync(Windows.Devices.PointOfService.PaymentOperationStatus status);
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceVoidTokenRequestEventArgs", 66db2589-d461-4682-a95a-abaa4cd0c3e0)]
    runtimeclass PaymentDeviceVoidTokenRequestEventArgs
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceVoidTokenRequest Request{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceConnectorInfo", 764e7ae7-2b85-446f-8c36-9f5bc30ea2ac)]
    runtimeclass PaymentDeviceConnectorInfo
    {
        String CompanyName{ get; };
        String CompanyName{ set; };
        String Name{ get; };
        String Name{ set; };
        String Version{ get; };
        String Version{ set; };
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceConnection", bf27c13d-8b8f-49c6-8c73-c6ea0a5d01fd)]
    runtimeclass PaymentDeviceConnection
        : Windows.Foundation.IClosable
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceConnectorInfo ConnectorInfo{ get; };
        void Start();
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceGetTerminalsRequestEventArgs>  PaymentDeviceGetTerminalsRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceOpenTerminalRequestEventArgs>  PaymentDeviceOpenTerminalRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceCloseTerminalRequestEventArgs>  PaymentDeviceCloseTerminalRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceReadCapabilitiesRequestEventArgs>  PaymentDeviceReadCapabilitiesRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceReadConfigurationRequestEventArgs>  PaymentDeviceReadConfigurationRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceWriteConfigurationRequestEventArgs>  PaymentDeviceWriteConfigurationRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDevicePaymentAuthorizationRequestEventArgs>  PaymentDevicePaymentAuthorizationRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDevicePaymentRequestEventArgs>  PaymentDevicePaymentRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceRefundRequestEventArgs>  PaymentDeviceRefundRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceVoidTransactionRequestEventArgs>  PaymentDeviceVoidTransactionRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Devices.PointOfService.Provider.PaymentDeviceConnection, Windows.Devices.PointOfService.Provider.PaymentDeviceVoidTokenRequestEventArgs>  PaymentDeviceVoidTokenRequested;
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysDisabledByDefault)]
    [interface_name("Windows.Devices.PointOfService.Provider.IPaymentDeviceConnectionTriggerDetails", 3137fffc-97a4-42e6-9681-33741302ba18)]
    runtimeclass PaymentDeviceConnectionTriggerDetails
    {
        Windows.Devices.PointOfService.Provider.PaymentDeviceConnection Connection{ get; };
    }

}
