











namespace Windows.UI.Composition.Scenes
{
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [webhosthidden]
    enum SceneAlphaMode
    {
        Opaque,
        AlphaTest,
        Blend,
    };

    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [webhosthidden]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    enum SceneComponentType
    {
        MeshRendererComponent,
    };

    [feature(Velocity_AlwaysAlwaysEnabled)]
    [webhosthidden]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    enum SceneAttributeSemantic
    {
        Index,
        Vertex,
        Normal,
        TexCoord0,
        TexCoord1,
        Color,
        Tangent,
    };

    [feature(Velocity_AlwaysAlwaysEnabled)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [webhosthidden]
    enum SceneWrappingMode
    {
        ClampToEdge,
        MirroredRepeat,
        Repeat,
    };



    [dualapipartition(0xa000006)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [webhosthidden]
    [constructor_name("Windows.UI.Composition.Scenes.ISceneObjectFactory", 14fe799a-33e4-52ef-956c-44229d21f2c1)]
    [default_interface]
    [interface_name("Windows.UI.Composition.Scenes.ISceneObject", 1e94249b-0f1b-49eb-a819-877d8450005b)]
    [threading(both)]
    unsealed runtimeclass SceneObject
        : Windows.UI.Composition.CompositionObject
    {
    }



    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    [constructor_name("Windows.UI.Composition.Scenes.ISceneComponentFactory", 5fbc5574-ddd8-5889-ab5b-d8fa716e7c9e)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneComponent", ae20fc96-226c-44bd-95cb-dd5ed9ebe9a5)]
    [threading(both)]
    unsealed runtimeclass SceneComponent
        : Windows.UI.Composition.Scenes.SceneObject
    {
        Windows.UI.Composition.Scenes.SceneComponentType ComponentType{ get; };
    }


    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [webhosthidden]
    [interface_name("Windows.UI.Composition.Scenes.ISceneBoundingBox", 5d8ffc70-c618-4083-8251-9962593114aa)]
    runtimeclass SceneBoundingBox
        : Windows.UI.Composition.Scenes.SceneObject
    {
        Windows.Foundation.Numerics.Vector3 Center{ get; };
        Windows.Foundation.Numerics.Vector3 Extents{ get; };
        Windows.Foundation.Numerics.Vector3 Max{ get; };
        Windows.Foundation.Numerics.Vector3 Min{ get; };
        Windows.Foundation.Numerics.Vector3 Size{ get; };
    }



    [webhosthidden]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000006)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [static_name("Windows.UI.Composition.Scenes.ISceneMeshStatics", 8412316c-7b57-473f-966b-81dc277b1751)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneMesh", ee9a1530-1155-4c0c-92bd-40020cf78347)]
    [threading(both)]
    runtimeclass SceneMesh
        : Windows.UI.Composition.Scenes.SceneObject
    {
        static Windows.UI.Composition.Scenes.SceneMesh Create(Windows.UI.Composition.Compositor compositor);
        Windows.UI.Composition.Scenes.SceneBoundingBox Bounds{ get; };
        Windows.Graphics.DirectX.DirectXPrimitiveTopology PrimitiveTopology{ get; };
        Windows.Graphics.DirectX.DirectXPrimitiveTopology PrimitiveTopology{ set; };
        void FillMeshAttribute(SceneAttributeSemantic semantic, Windows.Graphics.DirectX.DirectXPixelFormat format, Windows.Foundation.MemoryBuffer memory);
    }



    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [dualapipartition(0xa000006)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [constructor_name("Windows.UI.Composition.Scenes.ISceneRendererComponentFactory", 1db6ed6c-aa2c-5967-9035-56352dc69658)]
    [default_interface]
    [interface_name("Windows.UI.Composition.Scenes.ISceneRendererComponent", f1acb857-cf4f-4025-9b25-a2d1944cf507)]
    [threading(both)]
    unsealed runtimeclass SceneRendererComponent
        : Windows.UI.Composition.Scenes.SceneComponent
    {
    }



    [webhosthidden]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    [constructor_name("Windows.UI.Composition.Scenes.ISceneMaterialInputFactory", a88feb74-7d0a-5e4c-a748-1015af9ca74f)]
    [default_interface]
    [interface_name("Windows.UI.Composition.Scenes.ISceneMaterialInput", 422a1642-1ef1-485c-97e9-ae6f95ad812f)]
    [threading(both)]
    unsealed runtimeclass SceneMaterialInput
        : Windows.UI.Composition.Scenes.SceneObject
    {
    }



    [feature(Velocity_AlwaysAlwaysEnabled)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000006)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [webhosthidden]
    [static_name("Windows.UI.Composition.Scenes.ISceneSurfaceMaterialInputStatics", 5a2394d3-6429-4589-bbcf-b84f4f3cfbfe)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneSurfaceMaterialInput", 9937da5c-a9ca-4cfc-b3aa-088356518742)]
    [threading(both)]
    runtimeclass SceneSurfaceMaterialInput
        : Windows.UI.Composition.Scenes.SceneMaterialInput
    {
        static Windows.UI.Composition.Scenes.SceneSurfaceMaterialInput Create(Windows.UI.Composition.Compositor compositor);
        Windows.UI.Composition.CompositionBitmapInterpolationMode BitmapInterpolationMode{ get; };
        Windows.UI.Composition.CompositionBitmapInterpolationMode BitmapInterpolationMode{ set; };
        Windows.UI.Composition.ICompositionSurface Surface{ get; };
        Windows.UI.Composition.ICompositionSurface Surface{ set; };
        Windows.UI.Composition.Scenes.SceneWrappingMode WrappingUMode{ get; };
        Windows.UI.Composition.Scenes.SceneWrappingMode WrappingUMode{ set; };
        Windows.UI.Composition.Scenes.SceneWrappingMode WrappingVMode{ get; };
        Windows.UI.Composition.Scenes.SceneWrappingMode WrappingVMode{ set; };
    }



    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [constructor_name("Windows.UI.Composition.Scenes.ISceneMaterialFactory", 67536c19-a707-5254-a495-7fdc799893b9)]
    [default_interface]
    [interface_name("Windows.UI.Composition.Scenes.ISceneMaterial", 8ca74b7c-30df-4e07-9490-37875af1a123)]
    [threading(both)]
    unsealed runtimeclass SceneMaterial
        : Windows.UI.Composition.Scenes.SceneObject
    {
    }



    [dualapipartition(0xa000006)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [constructor_name("Windows.UI.Composition.Scenes.IScenePbrMaterialFactory", 2e3f3dfe-0b85-5727-b5be-b7d3cbac37fa)]
    [interface_name("Windows.UI.Composition.Scenes.IScenePbrMaterial", aab6ebbe-d680-46df-8294-b6800a9f95e7)]
    [threading(both)]
    unsealed runtimeclass ScenePbrMaterial
        : Windows.UI.Composition.Scenes.SceneMaterial
    {
        Single AlphaCutoff{ get; };
        Single AlphaCutoff{ set; };
        Windows.UI.Composition.Scenes.SceneAlphaMode AlphaMode{ get; };
        Windows.UI.Composition.Scenes.SceneAlphaMode AlphaMode{ set; };
        Windows.UI.Composition.Scenes.SceneMaterialInput EmissiveInput{ get; };
        Windows.UI.Composition.Scenes.SceneMaterialInput EmissiveInput{ set; };
        Windows.Foundation.Numerics.Vector3 EmissiveFactor{ get; };
        Windows.Foundation.Numerics.Vector3 EmissiveFactor{ set; };
        Boolean IsDoubleSided{ get; };
        Boolean IsDoubleSided{ set; };
        Windows.UI.Composition.Scenes.SceneMaterialInput NormalInput{ get; };
        Windows.UI.Composition.Scenes.SceneMaterialInput NormalInput{ set; };
        Single NormalScale{ get; };
        Single NormalScale{ set; };
        Windows.UI.Composition.Scenes.SceneMaterialInput OcclusionInput{ get; };
        Windows.UI.Composition.Scenes.SceneMaterialInput OcclusionInput{ set; };
        Single OcclusionStrength{ get; };
        Single OcclusionStrength{ set; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000006)]
    [webhosthidden]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [static_name("Windows.UI.Composition.Scenes.ISceneMetallicRoughnessMaterialStatics", 3bddca50-6d9d-4531-8dc4-b27e3e49b7ab)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneMetallicRoughnessMaterial", c1d91446-799c-429e-a4e4-5da645f18e61)]
    [threading(both)]
    runtimeclass SceneMetallicRoughnessMaterial
        : Windows.UI.Composition.Scenes.ScenePbrMaterial
    {
        static Windows.UI.Composition.Scenes.SceneMetallicRoughnessMaterial Create(Windows.UI.Composition.Compositor compositor);
        Windows.UI.Composition.Scenes.SceneMaterialInput BaseColorInput{ get; };
        Windows.UI.Composition.Scenes.SceneMaterialInput BaseColorInput{ set; };
        Windows.Foundation.Numerics.Vector4 BaseColorFactor{ get; };
        Windows.Foundation.Numerics.Vector4 BaseColorFactor{ set; };
        Single MetallicFactor{ get; };
        Single MetallicFactor{ set; };
        Windows.UI.Composition.Scenes.SceneMaterialInput MetallicRoughnessInput{ get; };
        Windows.UI.Composition.Scenes.SceneMaterialInput MetallicRoughnessInput{ set; };
        Single RoughnessFactor{ get; };
        Single RoughnessFactor{ set; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [dualapipartition(0xa000006)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [default_interface]
    [interface_name("Windows.UI.Composition.Scenes.ISceneMeshMaterialAttributeMap", ce843171-3d43-4855-aa69-31ff988d049d)]
    runtimeclass SceneMeshMaterialAttributeMap
        : Windows.UI.Composition.Scenes.SceneObject
        , Windows.Foundation.Collections.IMap<String, Windows.UI.Composition.Scenes.SceneAttributeSemantic>
        , Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, Windows.UI.Composition.Scenes.SceneAttributeSemantic> >
    {
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000006)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [webhosthidden]
    [static_name("Windows.UI.Composition.Scenes.ISceneMeshRendererComponentStatics", 4954f37a-4459-4521-bd6e-2b38b8d711ea)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneMeshRendererComponent", 9929f7e3-6364-477e-98fe-74ed9fd4c2de)]
    [threading(both)]
    runtimeclass SceneMeshRendererComponent
        : Windows.UI.Composition.Scenes.SceneRendererComponent
    {
        static Windows.UI.Composition.Scenes.SceneMeshRendererComponent Create(Windows.UI.Composition.Compositor compositor);
        Windows.UI.Composition.Scenes.SceneMaterial Material{ get; };
        Windows.UI.Composition.Scenes.SceneMaterial Material{ set; };
        Windows.UI.Composition.Scenes.SceneMesh Mesh{ get; };
        Windows.UI.Composition.Scenes.SceneMesh Mesh{ set; };
        Windows.UI.Composition.Scenes.SceneMeshMaterialAttributeMap UVMappings{ get; };
    }


    [dualapipartition(0xa000006)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [static_name("Windows.UI.Composition.Scenes.ISceneNodeStatics", 579a0faa-be9d-4210-908c-93d15feed0b7)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneNode", acf2c247-f307-4581-9c41-af2e29c3b016)]
    [threading(both)]
    runtimeclass SceneNode
        : Windows.UI.Composition.Scenes.SceneObject
    {
        static Windows.UI.Composition.Scenes.SceneNode Create(Windows.UI.Composition.Compositor compositor);
        Windows.UI.Composition.Scenes.SceneNodeCollection Children{ get; };
        Windows.UI.Composition.Scenes.SceneComponentCollection Components{ get; };
        Windows.UI.Composition.Scenes.SceneNode Parent{ get; };
        Windows.UI.Composition.Scenes.SceneModelTransform Transform{ get; };
        Windows.UI.Composition.Scenes.SceneComponent FindFirstComponentOfType(SceneComponentType value);
    }


    [dualapipartition(0xa000006)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [static_name("Windows.UI.Composition.Scenes.ISceneVisualStatics", b8347e9a-50aa-4527-8d34-de4cb8ea88b4)]
    [interface_name("Windows.UI.Composition.Scenes.ISceneVisual", 8e672c1e-d734-47b1-be14-3d694ffa4301)]
    [threading(both)]
    runtimeclass SceneVisual
        : Windows.UI.Composition.ContainerVisual
    {
        static Windows.UI.Composition.Scenes.SceneVisual Create(Windows.UI.Composition.Compositor compositor);
        Windows.UI.Composition.Scenes.SceneNode Root{ get; };
        Windows.UI.Composition.Scenes.SceneNode Root{ set; };
    }


    [webhosthidden]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [marshaling_behavior(agile)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    runtimeclass SceneNodeCollection
        : Windows.UI.Composition.Scenes.SceneObject
        , [default]Windows.Foundation.Collections.IVector<Windows.UI.Composition.Scenes.SceneNode>
        , Windows.Foundation.Collections.IIterable<Windows.UI.Composition.Scenes.SceneNode>
    {

        [feature(Velocity_AlwaysAlwaysEnabled)]
        [interface_name("Windows.UI.Composition.Scenes.ISceneNodeCollection", 29ada101-2dd9-4332-be63-60d2cf4269f2)]
        {
        }
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [webhosthidden]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    runtimeclass SceneComponentCollection
        : Windows.UI.Composition.Scenes.SceneObject
        , [default]Windows.Foundation.Collections.IVector<Windows.UI.Composition.Scenes.SceneComponent>
        , Windows.Foundation.Collections.IIterable<Windows.UI.Composition.Scenes.SceneComponent>
    {

        [feature(Velocity_AlwaysAlwaysEnabled)]
        [interface_name("Windows.UI.Composition.Scenes.ISceneComponentCollection", c483791c-5f46-45e4-b666-a3d2259f9b2e)]
        {
        }
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 8)]
    [feature(Velocity_AlwaysAlwaysEnabled)]
    [dualapipartition(0xa000006)]
    [webhosthidden]
    [interface_name("Windows.UI.Composition.Scenes.ISceneModelTransform", c05576c2-32b1-4269-980d-b98537100ae4)]
    runtimeclass SceneModelTransform
        : Windows.UI.Composition.CompositionTransform
    {
        Windows.Foundation.Numerics.Quaternion Orientation{ get; };
        Windows.Foundation.Numerics.Quaternion Orientation{ set; };
        Single RotationAngle{ get; };
        Single RotationAngle{ set; };
        Single RotationAngleInDegrees{ get; };
        Single RotationAngleInDegrees{ set; };
        Windows.Foundation.Numerics.Vector3 RotationAxis{ get; };
        Windows.Foundation.Numerics.Vector3 RotationAxis{ set; };
        Windows.Foundation.Numerics.Vector3 Scale{ get; };
        Windows.Foundation.Numerics.Vector3 Scale{ set; };
        Windows.Foundation.Numerics.Vector3 Translation{ get; };
        Windows.Foundation.Numerics.Vector3 Translation{ set; };
    }






}
