










namespace Windows.Media.PlayTo
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PlayToConnection may be altered or unavailable for releases after Windows 10. Instead, use CastingConnection.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [interface_name("Windows.Media.PlayTo.IPlayToConnection", 112fbfc8-f235-4fde-8d41-9bf27c9e9a40)]
    runtimeclass PlayToConnection
    {
        [deprecated("PlayToConnection may be altered or unavailable for releases after Windows 10. Instead, use CastingConnection.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToConnectionState State{ get; };
        [deprecated("PlayToConnection may be altered or unavailable for releases after Windows 10. Instead, use CastingConnection.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        event Windows.Foundation.TypedEventHandler <Windows.Media.PlayTo.PlayToConnection, Windows.Media.PlayTo.PlayToConnectionStateChangedEventArgs>  StateChanged;
        [deprecated("PlayToConnection may be altered or unavailable for releases after Windows 10. Instead, use CastingConnection.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        event Windows.Foundation.TypedEventHandler <Windows.Media.PlayTo.PlayToConnection, Windows.Media.PlayTo.PlayToConnectionTransferredEventArgs>  Transferred;
        [deprecated("PlayToConnection may be altered or unavailable for releases after Windows 10. Instead, use CastingConnection.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        event Windows.Foundation.TypedEventHandler <Windows.Media.PlayTo.PlayToConnection, Windows.Media.PlayTo.PlayToConnectionErrorEventArgs>  Error;
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [muse(0x6020000)]
    [deprecated("PlayToSource may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [interface_name("Windows.Media.PlayTo.IPlayToSource", 7f138a08-fbb7-4b09-8356-aa5f4e335c31)]
    runtimeclass PlayToSource
    {
        [deprecated("PlayToSource may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToConnection Connection{ get; };
        [deprecated("PlayToSource may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToSource Next{ get; };
        [deprecated("PlayToSource may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToSource Next{ set; };
        [deprecated("PlayToSource may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        void PlayNext();

        [contract(Windows.Foundation.UniversalApiContract, 1)]
        [interface_name("Windows.Media.PlayTo.IPlayToSourceWithPreferredSourceUri", aab253eb-3301-4dc4-afba-b2f2ed9635a0)]
        {
            [deprecated("PlayToSourceWithPreferredSourceUri may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
            Windows.Foundation.Uri PreferredSourceUri{ get; };
            [deprecated("PlayToSourceWithPreferredSourceUri may be altered or unavailable for releases after Windows 10. Instead, use CastingSource.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
            Windows.Foundation.Uri PreferredSourceUri{ set; };
        }
    }


    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PlayToConnectionState may be altered or unavailable for releases after Windows 10. Instead, use CastingConnectionState.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    enum PlayToConnectionState
    {
        Disconnected,
        Connected,
        Rendering,
    };


    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PlayToConnectionStateChangedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [interface_name("Windows.Media.PlayTo.IPlayToConnectionStateChangedEventArgs", 68c4b50f-0c20-4980-8602-58c62238d423)]
    runtimeclass PlayToConnectionStateChangedEventArgs
    {
        [deprecated("PlayToConnectionStateChangedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToConnectionState PreviousState{ get; };
        [deprecated("PlayToConnectionStateChangedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToConnectionState CurrentState{ get; };
    }


    [marshaling_behavior(agile)]
    [deprecated("PlayToConnectionTransferredEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Media.PlayTo.IPlayToConnectionTransferredEventArgs", fae3193a-0683-47d9-8df0-18cbb48984d8)]
    runtimeclass PlayToConnectionTransferredEventArgs
    {
        [deprecated("PlayToConnectionTransferredEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToSource PreviousSource{ get; };
        [deprecated("PlayToConnectionTransferredEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToSource CurrentSource{ get; };
    }

    [deprecated("PlayToConnectionError may be altered or unavailable for releases after Windows 10. Instead, use CastingConnectionErrorStatus.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum PlayToConnectionError
    {
        None,
        DeviceNotResponding,
        DeviceError,
        DeviceLocked,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        ProtectedPlaybackFailed,
    };


    [deprecated("PlayToConnectionErrorEventArgs may be altered or unavailable for releases after Windows 10. Instead, use CastingConnectionErrorOccurredEventArgs.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Media.PlayTo.IPlayToConnectionErrorEventArgs", bf5eada6-88e6-445f-9d40-d9b9f8939896)]
    runtimeclass PlayToConnectionErrorEventArgs
    {
        [deprecated("PlayToConnectionErrorEventArgs may be altered or unavailable for releases after Windows 10. Instead, use CastingConnectionErrorOccurredEventArgs.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToConnectionError Code{ get; };
        [deprecated("PlayToConnectionErrorEventArgs may be altered or unavailable for releases after Windows 10. Instead, use CastingConnectionErrorOccurredEventArgs.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        String Message{ get; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PlayToSourceSelectedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [interface_name("Windows.Media.PlayTo.IPlayToSourceSelectedEventArgs", 0c9d8511-5202-4dcb-8c67-abda12bb3c12)]
    runtimeclass PlayToSourceSelectedEventArgs
    {
        [deprecated("PlayToSourceSelectedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        String FriendlyName{ get; };
        [deprecated("PlayToSourceSelectedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Storage.Streams.IRandomAccessStreamWithContentType Icon{ get; };
        [deprecated("PlayToSourceSelectedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Boolean SupportsImage{ get; };
        [deprecated("PlayToSourceSelectedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Boolean SupportsAudio{ get; };
        [deprecated("PlayToSourceSelectedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Boolean SupportsVideo{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PlayToSourceDeferral may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [interface_name("Windows.Media.PlayTo.IPlayToSourceDeferral", 4100891d-278e-4f29-859b-a9e501053e7d)]
    runtimeclass PlayToSourceDeferral
    {
        [deprecated("PlayToSourceDeferral may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        void Complete();
    }


    [deprecated("PlayToSourceRequest may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Media.PlayTo.IPlayToSourceRequest", f8584665-64f4-44a0-ac0d-468d2b8fda83)]
    runtimeclass PlayToSourceRequest
    {
        [deprecated("PlayToSourceRequest may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Foundation.DateTime Deadline{ get; };
        [deprecated("PlayToSourceRequest may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        void DisplayErrorString(String errorString);
        [deprecated("PlayToSourceRequest may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToSourceDeferral GetDeferral();
        [deprecated("PlayToSourceRequest may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        void SetSource(PlayToSource value);
    }


    [deprecated("PlayToSourceRequestedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Media.PlayTo.IPlayToSourceRequestedEventArgs", c5cdc330-29df-4ec6-9da9-9fbdfcfc1b3e)]
    runtimeclass PlayToSourceRequestedEventArgs
    {
        [deprecated("PlayToSourceRequestedEventArgs may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Windows.Media.PlayTo.PlayToSourceRequest SourceRequest{ get; };
    }


    [muse(0x6020000)]
    [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Media.PlayTo.IPlayToManagerStatics", 64e6a887-3982-4f3b-ba20-6155e435325b)]
    [interface_name("Windows.Media.PlayTo.IPlayToManager", f56a206e-1b77-42ef-8f0d-b949f8d9b260)]
    runtimeclass PlayToManager
    {
        [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        static Windows.Media.PlayTo.PlayToManager GetForCurrentView();
        [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        static void ShowPlayToUI();
        [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        event Windows.Foundation.TypedEventHandler <Windows.Media.PlayTo.PlayToManager, Windows.Media.PlayTo.PlayToSourceRequestedEventArgs>  SourceRequested;
        [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        event Windows.Foundation.TypedEventHandler <Windows.Media.PlayTo.PlayToManager, Windows.Media.PlayTo.PlayToSourceSelectedEventArgs>  SourceSelected;
        [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Boolean DefaultSourceSelection{ set; };
        [deprecated("PlayToManager may be altered or unavailable for releases after Windows 10.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        Boolean DefaultSourceSelection{ get; };
    }


}
