









namespace Windows.Media.Control
{
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [dualapipartition(0x1)]
    [marshaling_behavior(agile)]
    [default_interface]
    [interface_name("Windows.Media.Control.ICurrentSessionChangedEventArgs", 6969cb39-0bfa-5fe0-8d73-09cc5e5408e1)]
    runtimeclass CurrentSessionChangedEventArgs
    {
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0x1)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [default_interface]
    [interface_name("Windows.Media.Control.ISessionsChangedEventArgs", bbf0cd32-42c4-5a58-b317-f34bbfbd26e0)]
    runtimeclass SessionsChangedEventArgs
    {
    }


    [dualapipartition(0x1)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [default_interface]
    [interface_name("Windows.Media.Control.ITimelinePropertiesChangedEventArgs", 29033a2f-c923-5a77-bcaf-055ff415ad32)]
    runtimeclass TimelinePropertiesChangedEventArgs
    {
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [dualapipartition(0x1)]
    [default_interface]
    [interface_name("Windows.Media.Control.IPlaybackInfoChangedEventArgs", 786756c2-bc0d-50a5-8807-054291fef139)]
    runtimeclass PlaybackInfoChangedEventArgs
    {
    }


    [dualapipartition(0x1)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [default_interface]
    [interface_name("Windows.Media.Control.IMediaPropertiesChangedEventArgs", 7d3741cb-adf0-5cef-91ba-cfabcdd77678)]
    runtimeclass MediaPropertiesChangedEventArgs
    {
    }

    [contract(Windows.Foundation.UniversalApiContract, 7)]
    enum GlobalSystemMediaTransportControlsSessionPlaybackStatus
    {
        Closed,
        Opened,
        Changing,
        Stopped,
        Playing,
        Paused,
    };


    [dualapipartition(0x1)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSession", 7148c835-9b14-5ae2-ab85-dc9b1c14e1a8)]
    runtimeclass GlobalSystemMediaTransportControlsSession
    {
        String SourceAppUserModelId{ get; };
        Windows.Foundation.IAsyncOperation <Windows.Media.Control.GlobalSystemMediaTransportControlsSessionMediaProperties>  TryGetMediaPropertiesAsync();
        Windows.Media.Control.GlobalSystemMediaTransportControlsSessionTimelineProperties GetTimelineProperties();
        Windows.Media.Control.GlobalSystemMediaTransportControlsSessionPlaybackInfo GetPlaybackInfo();
        Windows.Foundation.IAsyncOperation <Boolean>  TryPlayAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryPauseAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryStopAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryRecordAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryFastForwardAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryRewindAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TrySkipNextAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TrySkipPreviousAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryChangeChannelUpAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryChangeChannelDownAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryTogglePlayPauseAsync();
        Windows.Foundation.IAsyncOperation <Boolean>  TryChangeAutoRepeatModeAsync(Windows.Media.MediaPlaybackAutoRepeatMode requestedAutoRepeatMode);
        Windows.Foundation.IAsyncOperation <Boolean>  TryChangePlaybackRateAsync(Double requestedPlaybackRate);
        Windows.Foundation.IAsyncOperation <Boolean>  TryChangeShuffleActiveAsync(Boolean requestedShuffleState);
        Windows.Foundation.IAsyncOperation <Boolean>  TryChangePlaybackPositionAsync(Int64 requestedPlaybackPosition);
        event Windows.Foundation.TypedEventHandler <Windows.Media.Control.GlobalSystemMediaTransportControlsSession, Windows.Media.Control.TimelinePropertiesChangedEventArgs>  TimelinePropertiesChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Media.Control.GlobalSystemMediaTransportControlsSession, Windows.Media.Control.PlaybackInfoChangedEventArgs>  PlaybackInfoChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Media.Control.GlobalSystemMediaTransportControlsSession, Windows.Media.Control.MediaPropertiesChangedEventArgs>  MediaPropertiesChanged;
    }

    [marshaling_behavior(agile)]
    [dualapipartition(0x1)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [static_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionManagerStatics", 2050c4ee-11a0-57de-aed7-c97c70338245)]
    [interface_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionManager", cace8eac-e86e-504a-ab31-5ff8ff1bce49)]
    [threading(both)]
    runtimeclass GlobalSystemMediaTransportControlsSessionManager
    {
        static Windows.Foundation.IAsyncOperation <Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager>  RequestAsync();
        Windows.Media.Control.GlobalSystemMediaTransportControlsSession GetCurrentSession();
        Windows.Foundation.Collections.IVectorView <Windows.Media.Control.GlobalSystemMediaTransportControlsSession>  GetSessions();
        event Windows.Foundation.TypedEventHandler <Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager, Windows.Media.Control.CurrentSessionChangedEventArgs>  CurrentSessionChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager, Windows.Media.Control.SessionsChangedEventArgs>  SessionsChanged;
    }



    [dualapipartition(0x1)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionTimelineProperties", ede34136-6f25-588d-8ecf-ea5b6735aaa5)]
    runtimeclass GlobalSystemMediaTransportControlsSessionTimelineProperties
    {
        Windows.Foundation.TimeSpan StartTime{ get; };
        Windows.Foundation.TimeSpan EndTime{ get; };
        Windows.Foundation.TimeSpan MinSeekTime{ get; };
        Windows.Foundation.TimeSpan MaxSeekTime{ get; };
        Windows.Foundation.TimeSpan Position{ get; };
        Windows.Foundation.DateTime LastUpdatedTime{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [dualapipartition(0x1)]
    [interface_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionPlaybackControls", 6501a3e6-bc7a-503a-bb1b-68f158f3fb03)]
    runtimeclass GlobalSystemMediaTransportControlsSessionPlaybackControls
    {
        Boolean IsPlayEnabled{ get; };
        Boolean IsPauseEnabled{ get; };
        Boolean IsStopEnabled{ get; };
        Boolean IsRecordEnabled{ get; };
        Boolean IsFastForwardEnabled{ get; };
        Boolean IsRewindEnabled{ get; };
        Boolean IsNextEnabled{ get; };
        Boolean IsPreviousEnabled{ get; };
        Boolean IsChannelUpEnabled{ get; };
        Boolean IsChannelDownEnabled{ get; };
        Boolean IsPlayPauseToggleEnabled{ get; };
        Boolean IsShuffleEnabled{ get; };
        Boolean IsRepeatEnabled{ get; };
        Boolean IsPlaybackRateEnabled{ get; };
        Boolean IsPlaybackPositionEnabled{ get; };
    }

    [dualapipartition(0x1)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionPlaybackInfo", 94b4b6cf-e8ba-51ad-87a7-c10ade106127)]
    runtimeclass GlobalSystemMediaTransportControlsSessionPlaybackInfo
    {
        Windows.Media.Control.GlobalSystemMediaTransportControlsSessionPlaybackControls Controls{ get; };
        Windows.Media.Control.GlobalSystemMediaTransportControlsSessionPlaybackStatus PlaybackStatus{ get; };
        Windows.Foundation.IReference <Windows.Media.MediaPlaybackType>  PlaybackType{ get; };
        Windows.Foundation.IReference <Windows.Media.MediaPlaybackAutoRepeatMode>  AutoRepeatMode{ get; };
        Windows.Foundation.IReference <Double>  PlaybackRate{ get; };
        Windows.Foundation.IReference <Boolean>  IsShuffleActive{ get; };
    }


    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [marshaling_behavior(agile)]
    [dualapipartition(0x1)]
    [interface_name("Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionMediaProperties", 68856cf6-adb4-54b2-ac16-05837907acb6)]
    runtimeclass GlobalSystemMediaTransportControlsSessionMediaProperties
    {
        String Title{ get; };
        String Subtitle{ get; };
        String AlbumArtist{ get; };
        String Artist{ get; };
        String AlbumTitle{ get; };
        Int32 TrackNumber{ get; };
        Windows.Foundation.Collections.IVectorView <String>  Genres{ get; };
        Int32 AlbumTrackCount{ get; };
        Windows.Foundation.IReference <Windows.Media.MediaPlaybackType>  PlaybackType{ get; };
        Windows.Storage.Streams.IRandomAccessStreamReference Thumbnail{ get; };
    }



}
