













namespace Windows.Devices.Perception
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PerceptionFrameSourceAccessStatus may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    enum PerceptionFrameSourceAccessStatus
    {
        Unspecified,
        Allowed,
        DeniedByUser,
        DeniedBySystem,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PerceptionFrameSourcePropertyChangeStatus may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    enum PerceptionFrameSourcePropertyChangeStatus
    {
        Unknown,
        Accepted,
        LostControl,
        PropertyNotSupported,
        PropertyReadOnly,
        ValueOutOfRange,
    };


    [marshaling_behavior(agile)]
    [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrameSourceWatcher", 96bd1392-e667-40c4-89f9-1462dea6a9cc)]
    runtimeclass PerceptionColorFrameSourceWatcher
    {
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSourceWatcher, Windows.Devices.Perception.PerceptionColorFrameSourceAddedEventArgs>  SourceAdded;
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSourceWatcher, Windows.Devices.Perception.PerceptionColorFrameSourceRemovedEventArgs>  SourceRemoved;
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSourceWatcher, Object>  Stopped;
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSourceWatcher, Object>  EnumerationCompleted;
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Enumeration.DeviceWatcherStatus Status{ get; };
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void Start();
        [deprecated("PerceptionColorFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void Stop();
    }

    [marshaling_behavior(agile)]
    [deprecated("PerceptionColorFrameSourceAddedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrameSourceAddedEventArgs", d16bf4e6-da24-442c-bbd5-55549b5b94f3)]
    runtimeclass PerceptionColorFrameSourceAddedEventArgs
    {
        [deprecated("PerceptionColorFrameSourceAddedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionColorFrameSource FrameSource{ get; };
    }

    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionColorFrameSourceRemovedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrameSourceRemovedEventArgs", d277fa69-eb4c-42ef-ba4f-288f615c93c1)]
    runtimeclass PerceptionColorFrameSourceRemovedEventArgs
    {
        [deprecated("PerceptionColorFrameSourceRemovedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionColorFrameSource FrameSource{ get; };
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameSourceWatcher", 780e96d1-8d02-4d2b-ada4-5ba624a0eb10)]
    runtimeclass PerceptionDepthFrameSourceWatcher
    {
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSourceWatcher, Windows.Devices.Perception.PerceptionDepthFrameSourceAddedEventArgs>  SourceAdded;
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSourceWatcher, Windows.Devices.Perception.PerceptionDepthFrameSourceRemovedEventArgs>  SourceRemoved;
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSourceWatcher, Object>  Stopped;
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSourceWatcher, Object>  EnumerationCompleted;
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Enumeration.DeviceWatcherStatus Status{ get; };
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void Start();
        [deprecated("PerceptionDepthFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void Stop();
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionDepthFrameSourceAddedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameSourceAddedEventArgs", 93a48168-8bf8-45d2-a2f8-4ac0931cc7a6)]
    runtimeclass PerceptionDepthFrameSourceAddedEventArgs
    {
        [deprecated("PerceptionDepthFrameSourceAddedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionDepthFrameSource FrameSource{ get; };
    }

    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionDepthFrameSourceRemovedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameSourceRemovedEventArgs", a0c0cc4d-e96c-4d81-86dd-38b95e49c6df)]
    runtimeclass PerceptionDepthFrameSourceRemovedEventArgs
    {
        [deprecated("PerceptionDepthFrameSourceRemovedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionDepthFrameSource FrameSource{ get; };
    }


    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameSourceWatcher", 383cff99-d70c-444d-a8b0-720c2e66fe3b)]
    runtimeclass PerceptionInfraredFrameSourceWatcher
    {
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSourceWatcher, Windows.Devices.Perception.PerceptionInfraredFrameSourceAddedEventArgs>  SourceAdded;
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSourceWatcher, Windows.Devices.Perception.PerceptionInfraredFrameSourceRemovedEventArgs>  SourceRemoved;
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSourceWatcher, Object>  Stopped;
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSourceWatcher, Object>  EnumerationCompleted;
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Enumeration.DeviceWatcherStatus Status{ get; };
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void Start();
        [deprecated("PerceptionInfraredFrameSourceWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void Stop();
    }

    [deprecated("PerceptionInfraredFrameSourceAddedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameSourceAddedEventArgs", 6d334120-95ce-4660-907a-d98035aa2b7c)]
    runtimeclass PerceptionInfraredFrameSourceAddedEventArgs
    {
        [deprecated("PerceptionInfraredFrameSourceAddedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionInfraredFrameSource FrameSource{ get; };
    }

    [deprecated("PerceptionInfraredFrameSourceRemovedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameSourceRemovedEventArgs", ea1a8071-7a70-4a61-af94-07303853f695)]
    runtimeclass PerceptionInfraredFrameSourceRemovedEventArgs
    {
        [deprecated("PerceptionInfraredFrameSourceRemovedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionInfraredFrameSource FrameSource{ get; };
    }


    [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.Devices.Perception.IPerceptionColorFrameSourceStatics", 5df3cca2-01f8-4a87-b859-d5e5b7e1de49)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrameSource", dc6dba7c-0b58-468d-9ca1-6db04cc0477c)]
    [threading(both)]
    runtimeclass PerceptionColorFrameSource
    {
        [deprecated("PerceptionColorFrameSource.CreateWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.CreateWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Devices.Perception.PerceptionColorFrameSourceWatcher CreateWatcher();
        [deprecated("PerceptionColorFrameSource.FindAllAsync may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.FindAllAsync instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionColorFrameSource> >  FindAllAsync();
        [deprecated("PerceptionColorFrameSource.FromIdAsync may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.FromIdAsync instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionColorFrameSource>  FromIdAsync(String id);
        [deprecated("PerceptionColorFrameSource.RequestAccessAsync may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourceAccessStatus>  RequestAccessAsync();
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSource, Object>  AvailableChanged;
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSource, Object>  ActiveChanged;
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSource, Windows.Devices.Perception.PerceptionFrameSourcePropertiesChangedEventArgs>  PropertiesChanged;
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSource, Object>  VideoProfileChanged;
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameSource, Object>  CameraIntrinsicsChanged;
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String Id{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String DisplayName{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String DeviceKind{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean Available{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean Active{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsControlled{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [hasvariant]Windows.Foundation.Collections.IMapView <String, Object>  Properties{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionVideoProfile>  SupportedVideoProfiles{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionVideoProfile>  AvailableVideoProfiles{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionVideoProfile VideoProfile{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Media.Devices.Core.CameraIntrinsics CameraIntrinsics{ get; };
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionControlSession AcquireControlSession();
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean CanControlIndependentlyFrom(String targetId);
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsCorrelatedWith(String targetId);
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("hasResult")] Boolean TryGetTransformTo(String targetId, out Windows.Foundation.Numerics.Matrix4x4 result);
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthCorrelatedCameraIntrinsics>  TryGetDepthCorrelatedCameraIntrinsicsAsync(PerceptionDepthFrameSource correlatedDepthFrameSource);
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthCorrelatedCoordinateMapper>  TryGetDepthCorrelatedCoordinateMapperAsync(String targetSourceId, PerceptionDepthFrameSource correlatedDepthFrameSource);
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourcePropertyChangeResult>  TrySetVideoProfileAsync(PerceptionControlSession controlSession, PerceptionVideoProfile profile);
        [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionColorFrameReader OpenReader();

        [contract(Windows.Foundation.UniversalApiContract, 2)]
        [interface_name("Windows.Devices.Perception.IPerceptionColorFrameSource2", f88008e5-5631-45ed-ad98-8c6aa04cfb91)]
        {
            [deprecated("PerceptionColorFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
            String DeviceId{ get; };
        }
    }



    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [static_name("Windows.Devices.Perception.IPerceptionDepthFrameSourceStatics", 5df3cca2-01f8-4a87-b859-d5e5b7e1de48)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameSource", 79d433d6-47fb-4df1-bfc9-f01d40bd9942)]
    [threading(both)]
    runtimeclass PerceptionDepthFrameSource
    {
        [deprecated("PerceptionDepthFrameSource.CreateWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.CreateWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Devices.Perception.PerceptionDepthFrameSourceWatcher CreateWatcher();
        [deprecated("PerceptionDepthFrameSource.FindAllAsync may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.FindAllAsync instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionDepthFrameSource> >  FindAllAsync();
        [deprecated("PerceptionDepthFrameSource.FromIdAsync may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.FromIdAsync instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthFrameSource>  FromIdAsync(String id);
        [deprecated("PerceptionDepthFrameSource.RequestAccessAsync may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourceAccessStatus>  RequestAccessAsync();
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSource, Object>  AvailableChanged;
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSource, Object>  ActiveChanged;
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSource, Windows.Devices.Perception.PerceptionFrameSourcePropertiesChangedEventArgs>  PropertiesChanged;
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSource, Object>  VideoProfileChanged;
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameSource, Object>  CameraIntrinsicsChanged;
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String Id{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String DisplayName{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String DeviceKind{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean Available{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean Active{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsControlled{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [hasvariant]Windows.Foundation.Collections.IMapView <String, Object>  Properties{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionVideoProfile>  SupportedVideoProfiles{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionVideoProfile>  AvailableVideoProfiles{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionVideoProfile VideoProfile{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Media.Devices.Core.CameraIntrinsics CameraIntrinsics{ get; };
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionControlSession AcquireControlSession();
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean CanControlIndependentlyFrom(String targetId);
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsCorrelatedWith(String targetId);
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("hasResult")] Boolean TryGetTransformTo(String targetId, out Windows.Foundation.Numerics.Matrix4x4 result);
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthCorrelatedCameraIntrinsics>  TryGetDepthCorrelatedCameraIntrinsicsAsync(PerceptionDepthFrameSource target);
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthCorrelatedCoordinateMapper>  TryGetDepthCorrelatedCoordinateMapperAsync(String targetId, PerceptionDepthFrameSource depthFrameSourceToMapWith);
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourcePropertyChangeResult>  TrySetVideoProfileAsync(PerceptionControlSession controlSession, PerceptionVideoProfile profile);
        [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionDepthFrameReader OpenReader();

        [contract(Windows.Foundation.UniversalApiContract, 2)]
        [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameSource2", e3d23d2e-6e2c-4e6d-91d9-704cd8dff79d)]
        {
            [deprecated("PerceptionDepthFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
            String DeviceId{ get; };
        }
    }



    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [static_name("Windows.Devices.Perception.IPerceptionInfraredFrameSourceStatics", 5df3cca2-01f8-4a87-b859-d5e5b7e1de47)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameSource", 55b08742-1808-494e-9e30-9d2a7be8f700)]
    [threading(both)]
    runtimeclass PerceptionInfraredFrameSource
    {
        [deprecated("PerceptionInfraredFrameSource.CreateWatcher may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.CreateWatcher instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Devices.Perception.PerceptionInfraredFrameSourceWatcher CreateWatcher();
        [deprecated("PerceptionInfraredFrameSource.FindAllAsync may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.FindAllAsync instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionInfraredFrameSource> >  FindAllAsync();
        [deprecated("PerceptionInfraredFrameSource.FromIdAsync may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation.FromIdAsync instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionInfraredFrameSource>  FromIdAsync(String id);
        [deprecated("PerceptionInfraredFrameSource.RequestAccessAsync may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourceAccessStatus>  RequestAccessAsync();
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSource, Object>  AvailableChanged;
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSource, Object>  ActiveChanged;
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSource, Windows.Devices.Perception.PerceptionFrameSourcePropertiesChangedEventArgs>  PropertiesChanged;
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSource, Object>  VideoProfileChanged;
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameSource, Object>  CameraIntrinsicsChanged;
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String Id{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String DisplayName{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String DeviceKind{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean Available{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean Active{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsControlled{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [hasvariant]Windows.Foundation.Collections.IMapView <String, Object>  Properties{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionVideoProfile>  SupportedVideoProfiles{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.PerceptionVideoProfile>  AvailableVideoProfiles{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionVideoProfile VideoProfile{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Media.Devices.Core.CameraIntrinsics CameraIntrinsics{ get; };
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionControlSession AcquireControlSession();
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean CanControlIndependentlyFrom(String targetId);
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsCorrelatedWith(String targetId);
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("hasResult")] Boolean TryGetTransformTo(String targetId, out Windows.Foundation.Numerics.Matrix4x4 result);
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthCorrelatedCameraIntrinsics>  TryGetDepthCorrelatedCameraIntrinsicsAsync(PerceptionDepthFrameSource target);
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionDepthCorrelatedCoordinateMapper>  TryGetDepthCorrelatedCoordinateMapperAsync(String targetId, PerceptionDepthFrameSource depthFrameSourceToMapWith);
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourcePropertyChangeResult>  TrySetVideoProfileAsync(PerceptionControlSession controlSession, PerceptionVideoProfile profile);
        [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionInfraredFrameReader OpenReader();

        [contract(Windows.Foundation.UniversalApiContract, 2)]
        [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameSource2", dcd4d798-4b0b-4300-8d85-410817faa032)]
        {
            [deprecated("PerceptionInfraredFrameSource may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameSource instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
            String DeviceId{ get; };
        }
    }












    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PerceptionControlSession may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.Perception.IPerceptionControlSession", 99998653-5a3d-417f-9239-f1889e548b48)]
    runtimeclass PerceptionControlSession
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionControlSession may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionControlSession, Object>  ControlLost;
        [deprecated("PerceptionControlSession may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.IAsyncOperation <Windows.Devices.Perception.PerceptionFrameSourcePropertyChangeResult>  TrySetPropertyAsync(String name, [hasvariant]Object value);
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionFrameSourcePropertyChangeResult may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.Devices.Perception.IPerceptionFrameSourcePropertyChangeResult", 1e33390a-3c90-4d22-b898-f42bba6418ff)]
    runtimeclass PerceptionFrameSourcePropertyChangeResult
    {
        [deprecated("PerceptionFrameSourcePropertyChangeResult may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionFrameSourcePropertyChangeStatus Status{ get; };
        [deprecated("PerceptionFrameSourcePropertyChangeResult may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [variant]Object NewValue{ get; };
    }






    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PerceptionFrameSourcePropertiesChangedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.Perception.IPerceptionFrameSourcePropertiesChangedEventArgs", 6c68e068-bcf1-4ecc-b891-7625d1244b6b)]
    runtimeclass PerceptionFrameSourcePropertiesChangedEventArgs
    {
        [deprecated("PerceptionFrameSourcePropertiesChangedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Collections.CollectionChange CollectionChange{ get; };
        [deprecated("PerceptionFrameSourcePropertiesChangedEventArgs may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        String Key{ get; };
    }

    [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionVideoProfile", 75763ea3-011a-470e-8225-6f05ade25648)]
    runtimeclass PerceptionVideoProfile
    {
        [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Graphics.Imaging.BitmapPixelFormat BitmapPixelFormat{ get; };
        [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Graphics.Imaging.BitmapAlphaMode BitmapAlphaMode{ get; };
        [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Int32 Width{ get; };
        [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Int32 Height{ get; };
        [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.TimeSpan FrameDuration{ get; };
        [deprecated("PerceptionVideoProfile may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameFormat instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsEqual(PerceptionVideoProfile other);
    }

    [marshaling_behavior(agile)]
    [deprecated("PerceptionDepthCorrelatedCameraIntrinsics may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthCorrelatedCameraIntrinsics", 6548ca01-86de-5be1-6582-807fcf4c95cf)]
    runtimeclass PerceptionDepthCorrelatedCameraIntrinsics
    {
        [deprecated("PerceptionDepthCorrelatedCameraIntrinsics may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Numerics.Vector3 UnprojectPixelAtCorrelatedDepth(Windows.Foundation.Point pixelCoordinate, PerceptionDepthFrame depthFrame);
        [deprecated("PerceptionDepthCorrelatedCameraIntrinsics may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void UnprojectPixelsAtCorrelatedDepth(Windows.Foundation.Point[] sourceCoordinates, PerceptionDepthFrame depthFrame, ref Windows.Foundation.Numerics.Vector3[] results);
        [deprecated("PerceptionDepthCorrelatedCameraIntrinsics may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("result")] Windows.Foundation.IAsyncAction UnprojectRegionPixelsAtCorrelatedDepthAsync(Windows.Foundation.Rect region, PerceptionDepthFrame depthFrame, ref Windows.Foundation.Numerics.Vector3[] results);
        [deprecated("PerceptionDepthCorrelatedCameraIntrinsics may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("result")] Windows.Foundation.IAsyncAction UnprojectAllPixelsAtCorrelatedDepthAsync(PerceptionDepthFrame depthFrame, ref Windows.Foundation.Numerics.Vector3[] results);
    }

    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [deprecated("PerceptionDepthCorrelatedCoordinateMapper may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthCorrelatedCoordinateMapper", 5b4d9d1d-b5f6-469c-b8c2-b97a45e6863b)]
    runtimeclass PerceptionDepthCorrelatedCoordinateMapper
    {
        [deprecated("PerceptionDepthCorrelatedCoordinateMapper may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.Point MapPixelToTarget(Windows.Foundation.Point sourcePixelCoordinate, PerceptionDepthFrame depthFrame);
        [deprecated("PerceptionDepthCorrelatedCoordinateMapper may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        void MapPixelsToTarget(Windows.Foundation.Point[] sourceCoordinates, PerceptionDepthFrame depthFrame, ref Windows.Foundation.Point[] results);
        [deprecated("PerceptionDepthCorrelatedCoordinateMapper may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("result")] Windows.Foundation.IAsyncAction MapRegionOfPixelsToTargetAsync(Windows.Foundation.Rect region, PerceptionDepthFrame depthFrame, ref Windows.Foundation.Point[] targetCoordinates);
        [deprecated("PerceptionDepthCorrelatedCoordinateMapper may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.Core.DepthCorrelatedCoordinateMapper instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        [return_name("result")] Windows.Foundation.IAsyncAction MapAllPixelsToTargetAsync(PerceptionDepthFrame depthFrame, ref Windows.Foundation.Point[] targetCoordinates);
    }

    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [deprecated("PerceptionColorFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrameReader", 7650f56e-b9f5-461b-83ad-f222af2aaadc)]
    runtimeclass PerceptionColorFrameReader
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionColorFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionColorFrameReader, Windows.Devices.Perception.PerceptionColorFrameArrivedEventArgs>  FrameArrived;
        [deprecated("PerceptionColorFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionColorFrameSource Source{ get; };
        [deprecated("PerceptionColorFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsPaused{ get; };
        [deprecated("PerceptionColorFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsPaused{ set; };
        [deprecated("PerceptionColorFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionColorFrame TryReadLatestFrame();
    }



    [deprecated("PerceptionDepthFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameReader", b1a3c09f-299b-4612-a4f7-270f25a096ec)]
    runtimeclass PerceptionDepthFrameReader
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionDepthFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionDepthFrameReader, Windows.Devices.Perception.PerceptionDepthFrameArrivedEventArgs>  FrameArrived;
        [deprecated("PerceptionDepthFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionDepthFrameSource Source{ get; };
        [deprecated("PerceptionDepthFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsPaused{ get; };
        [deprecated("PerceptionDepthFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsPaused{ set; };
        [deprecated("PerceptionDepthFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionDepthFrame TryReadLatestFrame();
    }



    [deprecated("PerceptionInfraredFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameReader", 7960ce18-d39b-4fc8-a04a-929734c6756c)]
    runtimeclass PerceptionInfraredFrameReader
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionInfraredFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        event Windows.Foundation.TypedEventHandler <Windows.Devices.Perception.PerceptionInfraredFrameReader, Windows.Devices.Perception.PerceptionInfraredFrameArrivedEventArgs>  FrameArrived;
        [deprecated("PerceptionInfraredFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionInfraredFrameSource Source{ get; };
        [deprecated("PerceptionInfraredFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsPaused{ get; };
        [deprecated("PerceptionInfraredFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Boolean IsPaused{ set; };
        [deprecated("PerceptionInfraredFrameReader may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameReader instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionInfraredFrame TryReadLatestFrame();
    }




    [deprecated("PerceptionColorFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrameArrivedEventArgs", 8fad02d5-86f7-4d8d-b966-5a3761ba9f59)]
    runtimeclass PerceptionColorFrameArrivedEventArgs
    {
        [deprecated("PerceptionColorFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.TimeSpan RelativeTime{ get; };
        [deprecated("PerceptionColorFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionColorFrame TryOpenFrame();
    }

    [deprecated("PerceptionColorFrame may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.VideoMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Devices.Perception.IPerceptionColorFrame", fe621549-2cbf-4f94-9861-f817ea317747)]
    runtimeclass PerceptionColorFrame
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionColorFrame may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.VideoMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Media.VideoFrame VideoFrame{ get; };
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("PerceptionDepthFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrameArrivedEventArgs", 443d25b2-b282-4637-9173-ac978435c985)]
    runtimeclass PerceptionDepthFrameArrivedEventArgs
    {
        [deprecated("PerceptionDepthFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.TimeSpan RelativeTime{ get; };
        [deprecated("PerceptionDepthFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionDepthFrame TryOpenFrame();
    }

    [deprecated("PerceptionDepthFrame may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.DepthMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.Perception.IPerceptionDepthFrame", a37b81fc-9906-4ffd-9161-0024b360b657)]
    runtimeclass PerceptionDepthFrame
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionDepthFrame may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.DepthMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Media.VideoFrame VideoFrame{ get; };
    }


    [dualapipartition(0xa000000)]
    [deprecated("PerceptionInfraredFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrameArrivedEventArgs", 9f77fac7-b4bd-4857-9d50-be8ef075daef)]
    runtimeclass PerceptionInfraredFrameArrivedEventArgs
    {
        [deprecated("PerceptionInfraredFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Foundation.TimeSpan RelativeTime{ get; };
        [deprecated("PerceptionInfraredFrameArrivedEventArgs may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.MediaFrameArrivedEventArgs instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Devices.Perception.PerceptionInfraredFrame TryOpenFrame();
    }

    [deprecated("PerceptionInfraredFrame may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.InfraredMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.Devices.Perception.IPerceptionInfraredFrame", b0886276-849e-4c7a-8ae6-b56064532153)]
    runtimeclass PerceptionInfraredFrame
        : Windows.Foundation.IClosable
    {
        [deprecated("PerceptionInfraredFrame may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.InfraredMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        Windows.Media.VideoFrame VideoFrame{ get; };
    }









    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [static_name("Windows.Devices.Perception.IKnownPerceptionFrameSourcePropertiesStatics", 5df1cca2-01f8-4a87-b859-d5e5b7e1de47)]
    [threading(both)]
    runtimeclass KnownPerceptionFrameSourceProperties
    {
        [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String Id{ get; };
        [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String PhysicalDeviceIds{ get; };
        [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String FrameKind{ get; };
        [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String DeviceModelVersion{ get; };
        [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Devices.Enumeration.DeviceInformation instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String EnclosureLocation{ get; };

        [contract(Windows.Foundation.UniversalApiContract, 2)]
        [static_name("Windows.Devices.Perception.IKnownPerceptionFrameSourcePropertiesStatics2", a9c86871-05dc-4a4d-8a5c-a4ecf26bbc46)]
        {
            [deprecated("KnownPerceptionFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
            static String DeviceId{ get; };
        }
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("KnownPerceptionVideoFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Devices.Perception.IKnownPerceptionVideoFrameSourcePropertiesStatics", 5df1cca2-01f8-4a87-b859-d5e5b7e1de48)]
    [threading(both)]
    runtimeclass KnownPerceptionVideoFrameSourceProperties
    {
        [deprecated("KnownPerceptionVideoFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String VideoProfile{ get; };
        [deprecated("KnownPerceptionVideoFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String SupportedVideoProfiles{ get; };
        [deprecated("KnownPerceptionVideoFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String AvailableVideoProfiles{ get; };
        [deprecated("KnownPerceptionVideoFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String IsMirrored{ get; };
        [deprecated("KnownPerceptionVideoFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String CameraIntrinsics{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [deprecated("KnownPerceptionInfraredFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [static_name("Windows.Devices.Perception.IKnownPerceptionInfraredFrameSourcePropertiesStatics", 5df1cca2-01f8-4a87-b859-d5e5b7e1de49)]
    [threading(both)]
    runtimeclass KnownPerceptionInfraredFrameSourceProperties
    {
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.Exposure may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.ExposureControl instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String Exposure{ get; };
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.AutoExposureEnabled may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.ExposureControl.Auto instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String AutoExposureEnabled{ get; };
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.ExposureCompensation may be unavailable after Windows Creator Update.  Use Windows.Media.Devices.ExposureCompensationControl instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String ExposureCompensation{ get; };
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.ActiveIlluminationEnabled may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String ActiveIlluminationEnabled{ get; };
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.AmbientSubtractionEnabled may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String AmbientSubtractionEnabled{ get; };
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.StructureLightPatternEnabled may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String StructureLightPatternEnabled{ get; };
        [deprecated("KnownPerceptionInfraredFrameSourceProperties.InterleavedIlluminationEnabled may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String InterleavedIlluminationEnabled{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("KnownPerceptionDepthFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [static_name("Windows.Devices.Perception.IKnownPerceptionDepthFrameSourcePropertiesStatics", 5df1cca2-01f8-4a87-b859-d5e5b7e1de4a)]
    [threading(both)]
    runtimeclass KnownPerceptionDepthFrameSourceProperties
    {
        [deprecated("KnownPerceptionDepthFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.DepthMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String MinDepth{ get; };
        [deprecated("KnownPerceptionDepthFrameSourceProperties may be unavailable after Windows Creator Update.  Use Windows.Media.Capture.Frames.DepthMediaFrame instead.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String MaxDepth{ get; };
    }

    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("KnownPerceptionColorFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Devices.Perception.IKnownPerceptionColorFrameSourcePropertiesStatics", 5df1cca2-01f8-4a87-b859-d5e5b7e1de4b)]
    [threading(both)]
    runtimeclass KnownPerceptionColorFrameSourceProperties
    {
        [deprecated("KnownPerceptionColorFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String Exposure{ get; };
        [deprecated("KnownPerceptionColorFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String AutoExposureEnabled{ get; };
        [deprecated("KnownPerceptionColorFrameSourceProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String ExposureCompensation{ get; };
    }

    [marshaling_behavior(agile)]
    [deprecated("KnownPerceptionVideoProfileProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.Devices.Perception.IKnownPerceptionVideoProfilePropertiesStatics", 8f08e2e7-5a76-43e3-a13a-da3d91a9ef98)]
    [threading(both)]
    runtimeclass KnownPerceptionVideoProfileProperties
    {
        [deprecated("KnownPerceptionVideoProfileProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String BitmapPixelFormat{ get; };
        [deprecated("KnownPerceptionVideoProfileProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String BitmapAlphaMode{ get; };
        [deprecated("KnownPerceptionVideoProfileProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String Width{ get; };
        [deprecated("KnownPerceptionVideoProfileProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String Height{ get; };
        [deprecated("KnownPerceptionVideoProfileProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String FrameDuration{ get; };
    }

    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [deprecated("KnownCameraIntrinsicsProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
    [static_name("Windows.Devices.Perception.IKnownCameraIntrinsicsPropertiesStatics", 08c03978-437a-4d97-a663-fd3195600249)]
    [threading(both)]
    runtimeclass KnownCameraIntrinsicsProperties
    {
        [deprecated("KnownCameraIntrinsicsProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String FocalLength{ get; };
        [deprecated("KnownCameraIntrinsicsProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String PrincipalPoint{ get; };
        [deprecated("KnownCameraIntrinsicsProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String RadialDistortion{ get; };
        [deprecated("KnownCameraIntrinsicsProperties may be unavailable after Windows Creator Update.  Please refer to Windows.Media.Capture.Frames APIs on MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x40000)]
        static String TangentialDistortion{ get; };
    }

}
namespace Windows.Devices.Perception.Internal
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

}
namespace Windows.Devices.Perception
{
    [uuid(01d3ad1b-6507-428b-875d-007c18f41fca)]
    [contract(Windows.Devices.Perception.Internal.InternalContract, 1)]
    interface IPerceptionFrameSourceSet
    {
        Windows.Foundation.Collections.IVectorView <Object>  FrameSources{ get; };
    };


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Devices.Perception.Internal.InternalContract, 1)]
    [static_name("Windows.Devices.Perception.IFaceAuthenticationFrameSourceSetStatics", 8b106bb5-6491-4f9b-93e7-48329573fcbd)]
    [interface_name("Windows.Devices.Perception.IFaceAuthenticationFrameSourceSet", af056e9b-a5d4-4814-bf66-8b75e93f70b4)]
    [threading(both)]
    runtimeclass FaceAuthenticationFrameSourceSet
        : Windows.Devices.Perception.IPerceptionFrameSourceSet
    {
        static event Windows.Foundation.EventHandler <Object>  FaceAuthenticationFrameSourceSetsChanged;
        static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.Devices.Perception.FaceAuthenticationFrameSourceSet> >  FindAllAsync();
        void EnterFaceAuthenticationMode();
        void ExitFaceAuthenticationMode();
    }





    [marshaling_behavior(agile)]
    [contract(Windows.Devices.Perception.Internal.InternalContract, 1)]
    [interface_name("Windows.Devices.Perception.IVideoFrameSourceIntrinsicParameters", 24f12b9b-181b-4b93-9f91-5d17e2009581)]
    runtimeclass VideoFrameSourceIntrinsicParameters
    {
        Windows.Foundation.Numerics.Vector2 FocalLength{ get; };
        Windows.Foundation.Numerics.Vector2 PrincipalPoint{ get; };
        Windows.Foundation.Numerics.Vector3 RadialDistortion{ get; };
        Windows.Foundation.Numerics.Vector2 TangentialDistortion{ get; };
    }


    [contract(Windows.Devices.Perception.Internal.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Devices.Perception.IPerceptionFrameTypesStatics", e96bb763-8f23-4942-b83b-aaaef6378e78)]
    [threading(both)]
    runtimeclass PerceptionFrameTypes
    {
        static String Color{ get; };
        static String Depth{ get; };
        static String Infrared{ get; };
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Devices.Perception.Internal.InternalContract, 1)]
    [interface_name("Windows.Devices.Perception.IVideoFrameSourceCoordinateMapper", c1493e56-488f-47bd-8059-1999fe258f8c)]
    runtimeclass VideoFrameSourceCoordinateMapper
    {
        [method_name("ProjectCoordinate")] Windows.Foundation.Numerics.Vector3 Project(Windows.Foundation.Numerics.Vector3 coord);
        [method_name("UnprojectCoordinate")] Windows.Foundation.Numerics.Vector3 Unproject(Windows.Foundation.Numerics.Vector3 coord);
        [method_name("RegisterCoordinate")] Windows.Foundation.Numerics.Vector3 Register(Windows.Foundation.Numerics.Vector3 coord);
        [method_name("TransformCoordinate")] Windows.Foundation.Numerics.Vector3 Transform(Windows.Foundation.Numerics.Vector3 coord);
        void UnprojectDepth(UInt16[] depths, ref Windows.Foundation.Numerics.Vector3[] results);
        void RegisterDepth(UInt16[] depths, ref Windows.Foundation.Numerics.Vector3[] results);
        Windows.Foundation.Numerics.Matrix4x4 ToTargetTransform{ get; };
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Devices.Perception.Internal.InternalContract, 1)]
    [interface_name("Windows.Devices.Perception.IVideoFrameSourceCoordinateTransform", 7fbd55ae-898d-4529-96c1-57c7e9235384)]
    runtimeclass VideoFrameSourceCoordinateTransform
    {
        [method_name("ProjectCoordinate")] Windows.Foundation.Numerics.Vector3 Project(Windows.Foundation.Numerics.Vector3 coord);
        [method_name("UnprojectCoordinate")] Windows.Foundation.Numerics.Vector3 Unproject(Windows.Foundation.Numerics.Vector3 pixelCoordinate);
        [method_name("UnprojectCoordinateWithDepth")] Windows.Foundation.Numerics.Vector3 Unproject(Windows.Foundation.Numerics.Vector2 pixelCoordinate, Double depth);
        void UnprojectDepth(UInt16[] depths, ref Windows.Foundation.Numerics.Vector3[] results);
        Windows.Devices.Perception.VideoFrameSourceIntrinsicParameters IntrinsicParameters{ get; };
    }

}
