







namespace Windows.Internal.Shell.PlatformExtensions
{
    [contract(Windows.Internal.Shell.PlatformExtensions.InternalContract, 1)]
    [uuid(0c0239d8-6d5a-4eee-97ec-db7e85d64c49)]
    interface IPasswordEnrollmentStatics
    {
        Windows.Internal.UI.Auth.Enrollment.PasswordCredentialEnrollment GetPasswordEnrollment(Windows.Internal.UI.Auth.DeviceLock.DeviceLockSettings deviceLockSettings);
        Windows.Internal.UI.Auth.Enrollment.PicturePasswordCredentialEnrollment GetPicturePasswordEnrollment(Windows.Internal.UI.Auth.Enrollment.PasswordCredentialEnrollment passwordCredentialEnrollment, Windows.Internal.UI.Auth.DeviceLock.DeviceLockSettings deviceLockSettings);
    };

}
