












namespace Windows.Graphics.Capture
{
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [dualapipartition(0xa000004)]
    [interface_name("Windows.Graphics.Capture.IDirect3D11CaptureFrame", fa50c623-38da-4b32-acf3-fa9734ad800e)]
    runtimeclass Direct3D11CaptureFrame
        : Windows.Foundation.IClosable
    {
        Windows.Graphics.DirectX.Direct3D11.IDirect3DSurface Surface{ get; };
        Windows.Foundation.TimeSpan SystemRelativeTime{ get; };
        Windows.Graphics.SizeInt32 ContentSize{ get; };
    }


    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [interface_name("Windows.Graphics.Capture.IGraphicsCaptureItem", 79c3f95b-31f7-4ec2-a464-632ef5d30760)]
    [threading(both)]
    runtimeclass GraphicsCaptureItem
    {

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [static_name("Windows.Graphics.Capture.IGraphicsCaptureItemStatics", a87ebea5-457c-5788-ab47-0cf1d3637e74)]
        {
            static Windows.Graphics.Capture.GraphicsCaptureItem CreateFromVisual(Windows.UI.Composition.Visual visual);
        }
        String DisplayName{ get; };
        Windows.Graphics.SizeInt32 Size{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.Graphics.Capture.GraphicsCaptureItem, Object>  Closed;
    }



    [webhosthidden]
    [dualapipartition(0xa000004)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Capture.IGraphicsCapturePicker", 5a1711b3-ad79-4b4a-9336-1318fdde3539)]
    [threading(both)]
    runtimeclass GraphicsCapturePicker
    {
        GraphicsCapturePicker();
        Windows.Foundation.IAsyncOperation <Windows.Graphics.Capture.GraphicsCaptureItem>  PickSingleItemAsync();
    }



    [webhosthidden]
    [dualapipartition(0xa000004)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [static_name("Windows.Graphics.Capture.IGraphicsCaptureSessionStatics", 2224a540-5974-49aa-b232-0882536f4cb5)]
    [interface_name("Windows.Graphics.Capture.IGraphicsCaptureSession", 814e42a9-f70f-4ad7-939b-fddcc6eb880d)]
    [threading(both)]
    runtimeclass GraphicsCaptureSession
        : Windows.Foundation.IClosable
    {
        static Boolean IsSupported();
        void StartCapture();
    }


    [marshaling_behavior(agile)]
    [dualapipartition(0xa000004)]
    [webhosthidden]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [static_name("Windows.Graphics.Capture.IDirect3D11CaptureFramePoolStatics", 7784056a-67aa-4d53-ae54-1088d5a8ca21)]
    [interface_name("Windows.Graphics.Capture.IDirect3D11CaptureFramePool", 24eb6d22-1975-422e-82e7-780dbd8ddf24)]
    [threading(both)]
    runtimeclass Direct3D11CaptureFramePool
        : Windows.Foundation.IClosable
    {

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [static_name("Windows.Graphics.Capture.IDirect3D11CaptureFramePoolStatics2", 589b103f-6bbc-5df5-a991-02e28b3b66d5)]
        {
            static Windows.Graphics.Capture.Direct3D11CaptureFramePool CreateFreeThreaded(Windows.Graphics.DirectX.Direct3D11.IDirect3DDevice device, Windows.Graphics.DirectX.DirectXPixelFormat pixelFormat, Int32 numberOfBuffers, Windows.Graphics.SizeInt32 size);
        }
        static Windows.Graphics.Capture.Direct3D11CaptureFramePool Create(Windows.Graphics.DirectX.Direct3D11.IDirect3DDevice device, Windows.Graphics.DirectX.DirectXPixelFormat pixelFormat, Int32 numberOfBuffers, Windows.Graphics.SizeInt32 size);
        void Recreate(Windows.Graphics.DirectX.Direct3D11.IDirect3DDevice device, Windows.Graphics.DirectX.DirectXPixelFormat pixelFormat, Int32 numberOfBuffers, Windows.Graphics.SizeInt32 size);
        Windows.Graphics.Capture.Direct3D11CaptureFrame TryGetNextFrame();
        event Windows.Foundation.TypedEventHandler <Windows.Graphics.Capture.Direct3D11CaptureFramePool, Object>  FrameArrived;
        Windows.Graphics.Capture.GraphicsCaptureSession CreateCaptureSession(GraphicsCaptureItem item);
        Windows.System.DispatcherQueue DispatcherQueue{ get; };
    }



}
