










namespace Windows.ApplicationModel.Activation
{
    [contract(Windows.Foundation.UniversalApiContract, 2)]
    [uuid(eba0d1e4-ecc6-4148-94ed-f4b37ec05b3e)]
    interface IDevicePairingActivatedEventArgs requires Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
        Windows.Devices.Enumeration.DeviceInformation DeviceInformation{ get; };
    };

    [contract(Windows.Foundation.UniversalApiContract, 2)]
    [marshaling_behavior(agile)]
    runtimeclass DevicePairingActivatedEventArgs
        : [default]Windows.ApplicationModel.Activation.IDevicePairingActivatedEventArgs
        , Windows.ApplicationModel.Activation.IActivatedEventArgs
        , [contract(Windows.Foundation.UniversalApiContract, 3)]
        Windows.ApplicationModel.Activation.IActivatedEventArgsWithUser
    {
    }

}
namespace Windows.UI.WebUI
{
    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 2)]
    runtimeclass WebUIDevicePairingActivatedEventArgs
        : [default]Windows.ApplicationModel.Activation.IDevicePairingActivatedEventArgs
        , Windows.ApplicationModel.Activation.IActivatedEventArgs
        , Windows.UI.WebUI.IActivatedEventArgsDeferral
        , [contract(Windows.Foundation.UniversalApiContract, 3)]
        Windows.ApplicationModel.Activation.IActivatedEventArgsWithUser
    {
    }

}
