










namespace Windows.UI.Xaml.Controls
{
    [contractversion(1)]
    [internal]
    apicontract InkToolbarPrivateApiContract{};

    [webhosthidden]
    [contract(Windows.UI.Xaml.Controls.InkToolbarPrivateApiContract, 1)]
    enum InkToolbarEraserFlyoutItemKind
    {
        StrokeEraser,
        PrecisionSmallEraser,
        PrecisionLargeEraser,
        ClearAll,
    };

    [contract(Windows.UI.Xaml.Controls.InkToolbarPrivateApiContract, 1)]
    [webhosthidden]
    enum InkToolbarEraserKind
    {
        Stroke,
        PrecisionSmall,
        PrecisionLarge,
    };


    [marshaling_behavior(agile)]
    [contract(Windows.UI.Xaml.Controls.InkToolbarPrivateApiContract, 1)]
    [webhosthidden]
    [interface_name("Windows.UI.Xaml.Controls.IInkToolbarEraserFlyoutItemClickedEventArgs", d7a7aa25-1556-4408-8283-740bb407a248)]
    [threading(both)]
    runtimeclass InkToolbarEraserFlyoutItemClickedEventArgs
    {
        InkToolbarEraserFlyoutItemClickedEventArgs();
        Windows.UI.Xaml.Controls.InkToolbarEraserFlyoutItemKind EraserFlyoutItemKind{ get; };
        Boolean Handled{ get; };
        Boolean Handled{ set; };
    }



    [webhosthidden]
    [contract(Windows.UI.Xaml.Controls.InkToolbarPrivateApiContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.UI.Xaml.Controls.IInkToolbarEraserButtonInternalStatics", 7098507d-09c0-4c27-8e8b-3108f2bf22b1)]
    [constructor_name("Windows.UI.Xaml.Controls.IInkToolbarEraserButtonInternalFactory", 5cdbc91f-bf33-4437-b261-45f5f2b9adc4)]
    [interface_name("Windows.UI.Xaml.Controls.IInkToolbarEraserButtonInternal", d331fa8f-fcfd-4a3a-b48a-fd0e2424b5c4)]
    [threading(both)]
    unsealed runtimeclass InkToolbarEraserButtonInternal
        : Windows.UI.Xaml.DependencyObject
    {
        static Windows.UI.Xaml.DependencyProperty SelectedEraserProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty IsStrokeEraserVisibleProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ArePrecisionErasersVisibleProperty{ get; };
        static Windows.UI.Xaml.Controls.InkToolbarEraserButtonInternal GetInkToolbarEraserButtonInternal(InkToolbarEraserButton eraser);
        Windows.UI.Xaml.Controls.InkToolbarEraserKind SelectedEraser{ get; };
        Windows.UI.Xaml.Controls.InkToolbarEraserKind SelectedEraser{ set; };
        Boolean IsStrokeEraserVisible{ get; };
        Boolean IsStrokeEraserVisible{ set; };
        Boolean ArePrecisionErasersVisible{ get; };
        Boolean ArePrecisionErasersVisible{ set; };
    }



    [contract(Windows.UI.Xaml.Controls.InkToolbarPrivateApiContract, 1)]
    [webhosthidden]
    [marshaling_behavior(agile)]
    [constructor_name("Windows.UI.Xaml.Controls.IInkToolbarInternalFactory", 13fb78b6-faac-4239-be0e-2a0af3a3d618)]
    [static_name("Windows.UI.Xaml.Controls.IInkToolbarInternalStatics", c975df33-2d6f-4609-8db4-d5b13dafe9c4)]
    [interface_name("Windows.UI.Xaml.Controls.IInkToolbarInternal", 2db5de57-86c1-448a-a089-a9950d6e18db)]
    [threading(both)]
    unsealed runtimeclass InkToolbarInternal
        : Windows.UI.Xaml.DependencyObject
    {
        static Windows.UI.Xaml.Controls.InkToolbarInternal GetInkToolbarInternal(InkToolbar inkToolbar);
        event Windows.Foundation.TypedEventHandler <Windows.UI.Xaml.Controls.InkToolbarInternal, Windows.UI.Xaml.Controls.InkToolbarEraserFlyoutItemClickedEventArgs>  EraserFlyoutItemClicked;
    }



}
