






namespace Windows.System
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [flags]
    enum VirtualKeyModifiers
    {
        None,
        Control,
        Menu,
        Shift = 4,
        Windows = 8,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum VirtualKey
    {
        None,
        LeftButton,
        RightButton,
        Cancel,
        MiddleButton,
        XButton1,
        XButton2,
        Back = 8,
        Tab,
        Clear = 12,
        Enter,
        Shift = 16,
        Control,
        Menu,
        Pause,
        CapitalLock,
        Kana,
        Hangul = 21,
        Junja = 23,
        Final,
        Hanja,
        Kanji = 25,
        Escape = 27,
        Convert,
        NonConvert,
        Accept,
        ModeChange,
        Space,
        PageUp,
        PageDown,
        End,
        Home,
        Left,
        Up,
        Right,
        Down,
        Select,
        Print,
        Execute,
        Snapshot,
        Insert,
        Delete,
        Help,
        Number0,
        Number1,
        Number2,
        Number3,
        Number4,
        Number5,
        Number6,
        Number7,
        Number8,
        Number9,
        A = 65,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftWindows,
        RightWindows,
        Application,
        Sleep = 95,
        NumberPad0,
        NumberPad1,
        NumberPad2,
        NumberPad3,
        NumberPad4,
        NumberPad5,
        NumberPad6,
        NumberPad7,
        NumberPad8,
        NumberPad9,
        Multiply,
        Add,
        Separator,
        Subtract,
        Decimal,
        Divide,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationView,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationMenu,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationUp,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationDown,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationLeft,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationRight,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationAccept,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        NavigationCancel,
        NumberKeyLock,
        Scroll,
        LeftShift = 160,
        RightShift,
        LeftControl,
        RightControl,
        LeftMenu,
        RightMenu,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GoBack,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GoForward,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Refresh,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Stop,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Search,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Favorites,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GoHome,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadA = 195,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadB,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadX,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadY,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightShoulder,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftShoulder,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftTrigger,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightTrigger,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadDPadUp,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadDPadDown,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadDPadLeft,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadDPadRight,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadMenu,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadView,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftThumbstickButton,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightThumbstickButton,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftThumbstickUp,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftThumbstickDown,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftThumbstickRight,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadLeftThumbstickLeft,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightThumbstickUp,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightThumbstickDown,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightThumbstickRight,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GamepadRightThumbstickLeft,
    };

}
