









namespace Windows.UI.Input
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.UI.Input.InternalContract, 1)]
    [uuid(fb518206-2fd1-47a1-8365-6703a543a391)]
    interface IRadialControllerMenuPrivateStatics
    {
        Windows.UI.Input.RadialControllerMenu CreateForWindow(UInt64 inputSink, UInt64 mainMenu);
    };

    [uuid(82d85228-c737-4aa5-8168-7fcd0835c87c)]
    [contract(Windows.UI.Input.InternalContract, 1)]
    interface IRadialControllerMenuItemInternal
    {
        UInt32 InternalId{ get; };
        UInt32 InternalId{ set; };
        Windows.UI.Input.RadialControllerMenuKnownIcon KnownIcon{ get; };
        Windows.Storage.Streams.IRandomAccessStreamReference Icon{ get; };
        String Glyph{ get; };
        String FontFamily{ get; };
        Windows.Foundation.Uri FontFileUri{ get; };
        void Invoke();
    };

    [uuid(86c2633e-6199-4d4a-a204-3b395fcc497c)]
    [contract(Windows.UI.Input.InternalContract, 1)]
    interface IRadialControllerMenuConfigInternal
    {
        void RefreshConnectionToShell();
    };

    [contract(Windows.UI.Input.InternalContract, 1)]
    [uuid(973fd148-efb0-4e95-ac89-f48a9099b019)]
    interface IRadialControllerPrivate
    {
        UInt64 InputSink{ get; };
    };

}
