






namespace Windows.UI.Text.Core
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum CoreTextInputScope
    {
        Default,
        Url,
        FilePath,
        FileName,
        EmailUserName,
        EmailAddress,
        UserName,
        PersonalFullName,
        PersonalNamePrefix,
        PersonalGivenName,
        PersonalMiddleName,
        PersonalSurname,
        PersonalNameSuffix,
        Address,
        AddressPostalCode,
        AddressStreet,
        AddressStateOrProvince,
        AddressCity,
        AddressCountryName,
        AddressCountryShortName,
        CurrencyAmountAndSymbol,
        CurrencyAmount,
        Date,
        DateMonth,
        DateDay,
        DateYear,
        DateMonthName,
        DateDayName,
        Number = 29,
        SingleCharacter,
        Password,
        TelephoneNumber,
        TelephoneCountryCode,
        TelephoneAreaCode,
        TelephoneLocalNumber,
        Time,
        TimeHour,
        TimeMinuteOrSecond,
        NumberFullWidth,
        AlphanumericHalfWidth,
        AlphanumericFullWidth,
        CurrencyChinese,
        Bopomofo,
        Hiragana,
        KatakanaHalfWidth,
        KatakanaFullWidth,
        Hanja,
        HangulHalfWidth,
        HangulFullWidth,
        Search,
        Formula,
        SearchIncremental,
        ChineseHalfWidth,
        ChineseFullWidth,
        NativeScript,
        Text = 57,
        Chat,
        NameOrPhoneNumber,
        EmailUserNameOrAddress,
        Private,
        Maps,
        PasswordNumeric,
        FormulaNumber = 67,
        [contract(Windows.Foundation.UniversalApiContract, 3)]
        ChatWithoutEmoji,
        [contract(Windows.Foundation.UniversalApiContract, 5)]
        Digits = 28,
        [contract(Windows.Foundation.UniversalApiContract, 5)]
        PinNumeric = 64,
        [contract(Windows.Foundation.UniversalApiContract, 5)]
        PinAlphanumeric,
    };

}
