














namespace Windows.Web.UI
{
    [uuid(3f921316-bc70-4bda-9136-c94370899fab)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    interface IWebViewControl
    {
        Windows.Foundation.Uri Source{ get; };
        Windows.Foundation.Uri Source{ set; };
        String DocumentTitle{ get; };
        Boolean CanGoBack{ get; };
        Boolean CanGoForward{ get; };
        Windows.UI.Color DefaultBackgroundColor{ set; };
        Windows.UI.Color DefaultBackgroundColor{ get; };
        Boolean ContainsFullScreenElement{ get; };
        Windows.Web.UI.WebViewControlSettings Settings{ get; };
        Windows.Foundation.Collections.IVectorView <Windows.Web.UI.WebViewControlDeferredPermissionRequest>  DeferredPermissionRequests{ get; };
        void GoForward();
        void GoBack();
        void Refresh();
        void Stop();
        void Navigate(Windows.Foundation.Uri source);
        void NavigateToString(String text);
        void NavigateToLocalStreamUri(Windows.Foundation.Uri source, Windows.Web.IUriToStreamResolver streamResolver);
        void NavigateWithHttpRequestMessage(Windows.Web.Http.HttpRequestMessage requestMessage);
        Windows.Foundation.IAsyncOperation <String>  InvokeScriptAsync(String scriptName, Windows.Foundation.Collections.IIterable <String>  arguments);
        Windows.Foundation.IAsyncAction CapturePreviewToStreamAsync(Windows.Storage.Streams.IRandomAccessStream stream);
        Windows.Foundation.IAsyncOperation <Windows.ApplicationModel.DataTransfer.DataPackage>  CaptureSelectedContentToDataPackageAsync();
        Windows.Foundation.Uri BuildLocalStreamUri(String contentIdentifier, String relativePath);
        void GetDeferredPermissionRequestById(UInt32 id, out WebViewControlDeferredPermissionRequest result);
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlNavigationStartingEventArgs>  NavigationStarting;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlContentLoadingEventArgs>  ContentLoading;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlDOMContentLoadedEventArgs>  DOMContentLoaded;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlNavigationCompletedEventArgs>  NavigationCompleted;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlNavigationStartingEventArgs>  FrameNavigationStarting;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlContentLoadingEventArgs>  FrameContentLoading;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlDOMContentLoadedEventArgs>  FrameDOMContentLoaded;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlNavigationCompletedEventArgs>  FrameNavigationCompleted;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlScriptNotifyEventArgs>  ScriptNotify;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlLongRunningScriptDetectedEventArgs>  LongRunningScriptDetected;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Object>  UnsafeContentWarningDisplaying;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlUnviewableContentIdentifiedEventArgs>  UnviewableContentIdentified;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlPermissionRequestedEventArgs>  PermissionRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlUnsupportedUriSchemeIdentifiedEventArgs>  UnsupportedUriSchemeIdentified;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlNewWindowRequestedEventArgs>  NewWindowRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Object>  ContainsFullScreenElementChanged;
        event Windows.Foundation.TypedEventHandler <Windows.Web.UI.IWebViewControl, Windows.Web.UI.WebViewControlWebResourceRequestedEventArgs>  WebResourceRequested;
    };

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlSettings", c9967fbf-5e98-4cfd-8cce-27b0911e3de8)]
    runtimeclass WebViewControlSettings
    {
        Boolean IsJavaScriptEnabled{ set; };
        Boolean IsJavaScriptEnabled{ get; };
        Boolean IsIndexedDBEnabled{ set; };
        Boolean IsIndexedDBEnabled{ get; };
        Boolean IsScriptNotifyAllowed{ set; };
        Boolean IsScriptNotifyAllowed{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlDeferredPermissionRequest", 2ce349e0-d759-445c-9926-8995298f152b)]
    runtimeclass WebViewControlDeferredPermissionRequest
    {
        UInt32 Id{ get; };
        Windows.Foundation.Uri Uri{ get; };
        Windows.Web.UI.WebViewControlPermissionType PermissionType{ get; };
        void Allow();
        void Deny();
    }

    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Web.UI.IWebViewControlNavigationStartingEventArgs", 0c9057c5-0a08-41c7-863b-71e3a9549137)]
    runtimeclass WebViewControlNavigationStartingEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
        Boolean Cancel{ get; };
        Boolean Cancel{ set; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlContentLoadingEventArgs", 9a3fccb2-b9bb-404b-a22b-66dccd1250c6)]
    runtimeclass WebViewControlContentLoadingEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
    }

    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Web.UI.IWebViewControlDOMContentLoadedEventArgs", be8bc008-9541-4545-9ff2-2df585b29f7d)]
    runtimeclass WebViewControlDOMContentLoadedEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
    }

    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Web.UI.IWebViewControlNavigationCompletedEventArgs", 20409918-4a15-4c46-a55d-f79edb0bde8b)]
    runtimeclass WebViewControlNavigationCompletedEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
        Boolean IsSuccess{ get; };
        Windows.Web.WebErrorStatus WebErrorStatus{ get; };
    }

    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Web.UI.IWebViewControlScriptNotifyEventArgs", 491de57b-6f49-41bb-b591-51b85b817037)]
    runtimeclass WebViewControlScriptNotifyEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
        String Value{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlLongRunningScriptDetectedEventArgs", 2a6e5bba-98b4-45bc-bbeb-0f69ce49c599)]
    runtimeclass WebViewControlLongRunningScriptDetectedEventArgs
    {
        Windows.Foundation.TimeSpan ExecutionTime{ get; };
        Boolean StopPageScriptExecution{ get; };
        Boolean StopPageScriptExecution{ set; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlUnviewableContentIdentifiedEventArgs", 4a9680db-88f2-4e20-b693-b4e2df4aa581)]
    runtimeclass WebViewControlUnviewableContentIdentifiedEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
        Windows.Foundation.Uri Referrer{ get; };
        String MediaType{ get; };
    }

    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Web.UI.IWebViewControlPermissionRequestedEventArgs", 27204d51-2488-4cc5-968e-0a771e59c147)]
    runtimeclass WebViewControlPermissionRequestedEventArgs
    {
        Windows.Web.UI.WebViewControlPermissionRequest PermissionRequest{ get; };
    }

    [marshaling_behavior(standard)]
    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [interface_name("Windows.Web.UI.IWebViewControlUnsupportedUriSchemeIdentifiedEventArgs", e3b81944-e4fc-43dc-94ca-f980f30bc51d)]
    runtimeclass WebViewControlUnsupportedUriSchemeIdentifiedEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
        Boolean Handled{ get; };
        Boolean Handled{ set; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlNewWindowRequestedEventArgs", 3df44bbb-a124-46d5-a083-d02cacdff5ad)]
    runtimeclass WebViewControlNewWindowRequestedEventArgs
    {
        Windows.Foundation.Uri Uri{ get; };
        Windows.Foundation.Uri Referrer{ get; };
        Boolean Handled{ get; };
        Boolean Handled{ set; };

        [contract(Windows.Foundation.UniversalApiContract, 7)]
        [interface_name("Windows.Web.UI.IWebViewControlNewWindowRequestedEventArgs2", b53c5ca6-2aae-4bfc-92b9-c30e92b48098)]
        {
            Windows.Web.UI.IWebViewControl NewWindow{ get; };
            Windows.Web.UI.IWebViewControl NewWindow{ set; };
            Windows.Foundation.Deferral GetDeferral();
        }
    }

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlWebResourceRequestedEventArgs", 44d6524d-55a4-4d8b-891c-931d8e25d42e)]
    runtimeclass WebViewControlWebResourceRequestedEventArgs
    {
        Windows.Foundation.Deferral GetDeferral();
        Windows.Web.Http.HttpRequestMessage Request{ get; };
        Windows.Web.Http.HttpResponseMessage Response{ set; };
        Windows.Web.Http.HttpResponseMessage Response{ get; };
    }

    [uuid(4d3c06f9-c8df-41cc-8bd5-2a947b204503)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    interface IWebViewControl2
    {
        void AddInitializeScript(String script);
    };

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    enum WebViewControlPermissionState
    {
        Unknown,
        Defer,
        Allow,
        Deny,
    };

    [contract(Windows.Foundation.UniversalApiContract, 6)]
    enum WebViewControlPermissionType
    {
        Geolocation,
        UnlimitedIndexedDBQuota,
        Media,
        PointerLock,
        WebNotifications,
        Screen,
        [contract(Windows.Foundation.UniversalApiContract, 7)]
        ImmersiveView,
    };




    [contract(Windows.Foundation.UniversalApiContract, 6)]
    [marshaling_behavior(standard)]
    [interface_name("Windows.Web.UI.IWebViewControlPermissionRequest", e5bc836c-f22f-40e2-95b2-7729f840eb7f)]
    runtimeclass WebViewControlPermissionRequest
    {
        UInt32 Id{ get; };
        Windows.Foundation.Uri Uri{ get; };
        Windows.Web.UI.WebViewControlPermissionType PermissionType{ get; };
        Windows.Web.UI.WebViewControlPermissionState State{ get; };
        void Defer();
        void Allow();
        void Deny();
    }













}
