







namespace Windows.UI.Internal.Input
{
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [webhosthidden]
    enum SuppressionState
    {
        Unsuppressed,
        Suppressed,
    };

    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    enum MouseInputEventType
    {
        MouseMoved,
        MouseScrolled,
        MouseLeftButtonDown,
        MouseLeftButtonUp,
        MouseRightButtonDown,
        MouseRightButtonUp,
        MouseMiddleButtonDown,
        MouseMiddleButtonUp,
        MouseXButtonDown,
        MouseXButtonUp,
    };


    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [webhosthidden]
    [static_name("Windows.UI.Internal.Input.IMouseInputObserverStatics", ba554bc2-b190-5471-98c2-0f3997ddccba)]
    [interface_name("Windows.UI.Internal.Input.IMouseInputObserver", 1c0853e4-a571-5120-b72b-091c7c550380)]
    [threading(both)]
    runtimeclass MouseInputObserver
    {
        static Windows.UI.Internal.Input.MouseInputObserver Create();
        Boolean Observing{ get; };
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.MouseInputObserver, Windows.UI.Internal.Input.MouseInputEventArgs>  MouseInputGenerated;
        Windows.UI.Internal.Input.SuppressionState GetSuppressionState();
        Boolean SuppressInput();
        void UnsuppressInput();
    }

    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [interface_name("Windows.UI.Internal.Input.IMouseInputEventArgs", 23fcf005-d307-50cd-89c6-0fad8ec1e146)]
    runtimeclass MouseInputEventArgs
    {
        UInt64 InputTime{ get; };
        UInt64 ExtraInfo{ get; };
        Windows.Foundation.Point Position{ get; };
        Windows.UI.Internal.Input.MouseInputEventType EventType{ get; };
        UInt16 WheelDelta{ get; };
        UInt16 XButtonID{ get; };
        Boolean WasInjected{ get; };
    }



}
