








namespace Windows.Security.Authentication.Web
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum WebAuthenticationStatus
    {
        Success,
        UserCancel,
        ErrorHttp,
    };

    [flags]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum WebAuthenticationOptions
    {
        None,
        SilentMode,
        UseTitle,
        UseHttpPost = 4,
        UseCorporateNetwork = 8,
    };


    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.Security.Authentication.Web.IWebAuthenticationResult", 64002b4b-ede9-470a-a5cd-0323faf6e262)]
    runtimeclass WebAuthenticationResult
    {
        String ResponseData{ get; };
        Windows.Security.Authentication.Web.WebAuthenticationStatus ResponseStatus{ get; };
        UInt32 ResponseErrorDetail{ get; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.Security.Authentication.Web.IWebAuthenticationBrokerStatics2", 73cdfb9e-14e7-41da-a971-aaf4410b621e)]
    [threading(both)]
    runtimeclass WebAuthenticationBroker
    {
        [method_name("AuthenticateAndContinue")] static void AuthenticateAndContinue(Windows.Foundation.Uri requestUri);
        [method_name("AuthenticateWithCallbackUriAndContinue")] static void AuthenticateAndContinue(Windows.Foundation.Uri requestUri, Windows.Foundation.Uri callbackUri);
        [method_name("AuthenticateWithCallbackUriContinuationDataAndOptionsAndContinue")] static void AuthenticateAndContinue(Windows.Foundation.Uri requestUri, Windows.Foundation.Uri callbackUri, Windows.Foundation.Collections.ValueSet continuationData, WebAuthenticationOptions options);
        [method_name("AuthenticateSilentlyAsync")] static Windows.Foundation.IAsyncOperation <Windows.Security.Authentication.Web.WebAuthenticationResult>  AuthenticateSilentlyAsync(Windows.Foundation.Uri requestUri);
        [method_name("AuthenticateSilentlyWithOptionsAsync")] static Windows.Foundation.IAsyncOperation <Windows.Security.Authentication.Web.WebAuthenticationResult>  AuthenticateSilentlyAsync(Windows.Foundation.Uri requestUri, WebAuthenticationOptions options);

        [contract(Windows.Foundation.UniversalApiContract, 1)]
        [static_name("Windows.Security.Authentication.Web.IWebAuthenticationBrokerStatics", 2f149f1a-e673-40b5-bc22-201a6864a37b)]
        {
            [method_name("AuthenticateWithCallbackUriAsync")] static Windows.Foundation.IAsyncOperation <Windows.Security.Authentication.Web.WebAuthenticationResult>  AuthenticateAsync(WebAuthenticationOptions options, Windows.Foundation.Uri requestUri, Windows.Foundation.Uri callbackUri);
            [method_name("AuthenticateWithoutCallbackUriAsync")] static Windows.Foundation.IAsyncOperation <Windows.Security.Authentication.Web.WebAuthenticationResult>  AuthenticateAsync(WebAuthenticationOptions options, Windows.Foundation.Uri requestUri);
            static Windows.Foundation.Uri GetCurrentApplicationCallbackUri();
        }
    }

}
