







namespace Windows.Media
{
    [contractversion(1)]
    apicontract MediaControlContract{};

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum SoundLevel
    {
        Muted,
        Low,
        Full,
    };


    [contract(Windows.Media.MediaControlContract, 1)]
    [marshaling_behavior(agile)]
    [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
    [static_name("Windows.Media.IMediaControl", 98f1fbe1-7a8d-42cb-b6fe-8fe698264f13)]
    [threading(mta)]
    runtimeclass MediaControl
    {
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  SoundLevelChanged;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  PlayPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  PausePressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  StopPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  PlayPauseTogglePressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  RecordPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  NextTrackPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  PreviousTrackPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  FastForwardPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  RewindPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  ChannelUpPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static event Windows.Foundation.EventHandler <Object>  ChannelDownPressed;
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static Windows.Media.SoundLevel SoundLevel{ get; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static String TrackName{ set; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static String TrackName{ get; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static String ArtistName{ set; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static String ArtistName{ get; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static Boolean IsPlaying{ set; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static Boolean IsPlaying{ get; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static Windows.Foundation.Uri AlbumArt{ set; };
        [deprecated("MediaControl may be altered or unavailable for releases after Windows 8.1. Instead, use SystemMediaTransportControls.", deprecate, Windows.Media.MediaControlContract, 0x10000)]
        static Windows.Foundation.Uri AlbumArt{ get; };
    }

}
