









namespace Windows.Internal.StateRepository
{
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [static_name("Windows.Internal.StateRepository.IPackageFamilyUserResourceStatics", c7c3633f-dbcb-4536-8624-6a401b44732a)]
    [interface_name("Windows.Internal.StateRepository.IPackageFamilyUserResource", 21c45654-6fdf-4137-a331-5797846d7217)]
    [threading(both)]
    runtimeclass PackageFamilyUserResource
    {
        static void Add(PackageFamilyUserResource value);
        static void Update(PackageFamilyUserResource value);
        static void Delete(PackageFamilyUserResource value);
        static void DeleteById(Int64 packageFamilyUserResourceID);
        static void DeleteByPackageFamilyUserAndResourceId(PackageFamilyUser PackageFamilyUser, String ResourceId);
        static Boolean Exists(Int64 packageFamilyUserResourceID);
        static Boolean ExistsByPackageFamilyUser(PackageFamilyUser PackageFamilyUser);
        static Boolean ExistsByPackageFamilyUserAndResourceId(PackageFamilyUser PackageFamilyUser, String ResourceId);
        static Windows.Internal.StateRepository.PackageFamilyUserResource TryGet(Int64 packageFamilyUserResourceID);
        static Windows.Internal.StateRepository.PackageFamilyUserResource TryGetByPackageFamilyUserAndResourceId(PackageFamilyUser PackageFamilyUser, String ResourceId);
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.PackageFamilyUserResource>  Find();
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.PackageFamilyUserResource>  FindByPackageFamilyUser(PackageFamilyUser PackageFamilyUser);
        PackageFamilyUserResource();
        Int64 _PackageFamilyUserResourceID{ get; };
        Int64 _PackageFamilyUserResourceID{ set; };
        UInt64 _Revision{ get; };
        UInt64 _Revision{ set; };
        Int64 PackageFamilyUser{ get; };
        Int64 PackageFamilyUser{ set; };
        Windows.Internal.StateRepository.PackageFamilyUser GetPackageFamilyUser();
        void SetPackageFamilyUser(PackageFamilyUser value);
        String ResourceId{ get; };
        String ResourceId{ set; };
        Boolean Is_DictionaryNull{ get; };
        void Set_DictionaryToNull();
        void Get_Dictionary(out UInt8[] value);
        void Set_Dictionary(UInt8[] value);
        Windows.Foundation.Collections.IPropertySet Get_DictionaryAsPropertySet();
    }


}
