











namespace Windows.Internal.StateRepository
{
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [contract(Windows.Internal.StateRepository.StateRepositoryContract, 1)]
    [static_name("Windows.Internal.StateRepository.IProvisionedPackageDeletedStatics", a0f5d047-b0df-448d-8a60-2cb74e8e2f85)]
    [interface_name("Windows.Internal.StateRepository.IProvisionedPackageDeleted", fe4c53e9-71a6-4571-b8e8-8c165e97cdf3)]
    [threading(both)]
    runtimeclass ProvisionedPackageDeleted
    {
        static Boolean Exists(Int64 provisionedPackageDeletedID);
        static Boolean ExistsByPackageIdentity(PackageIdentity PackageIdentity);
        static Boolean ExistsByPath(String Path);
        static Windows.Internal.StateRepository.ProvisionedPackageDeleted TryGet(Int64 provisionedPackageDeletedID);
        static Windows.Internal.StateRepository.ProvisionedPackageDeleted TryGetByPackageIdentity(PackageIdentity PackageIdentity);
        static Windows.Internal.StateRepository.ProvisionedPackageDeleted TryGetByPath(String Path);
        static Windows.Foundation.Collections.IVectorView <Windows.Internal.StateRepository.ProvisionedPackageDeleted>  Find();
        ProvisionedPackageDeleted();
        Int64 _ProvisionedPackageID{ get; };
        Int64 _ProvisionedPackageID{ set; };
        UInt64 _Revision{ get; };
        UInt64 _Revision{ set; };
        Int64 PackageIdentity{ get; };
        Int64 PackageIdentity{ set; };
        Windows.Internal.StateRepository.PackageIdentity GetPackageIdentity();
        void SetPackageIdentity(PackageIdentity value);
        Windows.Internal.StateRepository.ProvisionedPackageFlags Flags{ get; };
        Windows.Internal.StateRepository.ProvisionedPackageFlags Flags{ set; };
        Boolean DoNotKeepAfterPcReset{ get; };
        Boolean DoNotKeepAfterPcReset{ set; };
        Boolean RegisterOnlyForDefaultAccount{ get; };
        Boolean RegisterOnlyForDefaultAccount{ set; };
        String Path{ get; };
        String Path{ set; };
        Windows.Storage.StorageFolder GetPathAsStorageFolder();
        void SetPathAsStorageFolder(Windows.Storage.IStorageFolder value);
        Windows.Internal.StateRepository.SignatureOrigin SignatureOrigin{ get; };
        Windows.Internal.StateRepository.SignatureOrigin SignatureOrigin{ set; };
        Boolean IsRegionNull{ get; };
        void SetRegionToNull();
        String Region{ get; };
        String Region{ set; };
        Boolean Is_DictionaryNull{ get; };
        void Set_DictionaryToNull();
        void Get_Dictionary(out UInt8[] value);
        void Set_Dictionary(UInt8[] value);
        Windows.Foundation.Collections.IPropertySet Get_DictionaryAsPropertySet();
    }


}
