








namespace Windows.UI.Internal.Input
{
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    enum CursorDeviceType
    {
        Mouse,
        Pen,
    };

    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    struct CursorDeviceDescription
    {
        UInt64 deviceId;
        CursorDeviceType deviceType;
    };


    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.Internal.Input.ICursorDeviceWatcher", 049ea583-56a1-5a01-a538-b86d23da6c5f)]
    runtimeclass CursorDeviceWatcher
    {
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.CursorDeviceWatcher, Windows.UI.Internal.Input.CursorDeviceWatcherAddedEventArgs>  Added;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.CursorDeviceWatcher, Windows.UI.Internal.Input.CursorDeviceWatcherRemovedEventArgs>  Removed;
        event Windows.Foundation.TypedEventHandler <Windows.UI.Internal.Input.CursorDeviceWatcher, Object>  EnumerationCompleted;
        void Start();
        void Stop();
    }

    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.Internal.Input.ISystemCursorManager", 1e4681eb-1dd7-5947-bcb0-aaf31fc18c4b)]
    [threading(both)]
    runtimeclass SystemCursorManager
    {
        SystemCursorManager();
        void CreateCursor(UInt64 deviceId, UInt64 workspaceLuid, Windows.UI.Composition.Compositor compositorForCursor, Windows.UI.Composition.Visual rootForCursor);
        void LoadCursorAsset(UInt64 deviceId, UInt64 shapeId, String fileName);
        void SetCursorScale(UInt64 deviceId, Single scale);
        void SetCursorVisibility(UInt64 deviceId, Boolean visibility);
        Windows.UI.Internal.Input.CursorDeviceWatcher DeviceWatcher{ get; };
    }


    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [webhosthidden]
    [marshaling_behavior(agile)]
    [interface_name("Windows.UI.Internal.Input.ICursorDeviceWatcherAddedEventArgs", 1d84fd35-b741-5fa6-a6ef-2157b3145692)]
    runtimeclass CursorDeviceWatcherAddedEventArgs
    {
        Windows.UI.Internal.Input.CursorDeviceDescription Device{ get; };
    }

    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [interface_name("Windows.UI.Internal.Input.ICursorDeviceWatcherRemovedEventArgs", d5915c1c-bf99-52ad-bea4-0eb56a9ab7bb)]
    runtimeclass CursorDeviceWatcherRemovedEventArgs
    {
        UInt64 DeviceId{ get; };
    }



}
