






namespace Windows.Media.Render
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum AudioRenderCategory
    {
        Other,
        [deprecated("ForegroundOnlyMedia is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        ForegroundOnlyMedia,
        [deprecated("BackgroundCapableMedia is deprecated and might not work on all platforms. For more info, see MSDN.", deprecate, Windows.Foundation.UniversalApiContract, 0x10000)]
        BackgroundCapableMedia,
        Communications,
        Alerts,
        SoundEffects,
        GameEffects,
        GameMedia,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        GameChat,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Speech,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Movie,
        [contract(Windows.Foundation.UniversalApiContract, 1)]
        Media,
    };

}
