






namespace Windows.UI.Input.Inking
{
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    enum PenHandedness
    {
        Right,
        Left,
    };

    [contract(Windows.Foundation.UniversalApiContract, 7)]
    enum HandwritingLineHeight
    {
        Small,
        Medium,
        Large,
    };



    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 7)]
    [static_name("Windows.UI.Input.Inking.IPenAndInkSettingsStatics", ed6dd036-5708-5c3c-96db-f2f552eab641)]
    [interface_name("Windows.UI.Input.Inking.IPenAndInkSettings", bc2ceb8f-0066-44a8-bb7a-b839b3deb8f5)]
    [threading(both)]
    runtimeclass PenAndInkSettings
    {
        static Windows.UI.Input.Inking.PenAndInkSettings GetDefault();
        Boolean IsHandwritingDirectlyIntoTextFieldEnabled{ get; };
        Windows.UI.Input.Inking.PenHandedness PenHandedness{ get; };
        Windows.UI.Input.Inking.HandwritingLineHeight HandwritingLineHeight{ get; };
        String FontFamilyName{ get; };
        Boolean UserConsentsToHandwritingTelemetryCollection{ get; };
        Boolean IsTouchHandwritingEnabled{ get; };
    }

}
