







namespace Windows.Internal.Holographic.UI
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Internal.Holographic.UI.InternalContract, 1)]
    enum PresentationMode
    {
        Desktop,
        Holographic,
    };


    [contract(Windows.Internal.Holographic.UI.InternalContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.Internal.Holographic.UI.IHolographicViewPropertiesStatics", de27a01f-b561-4531-a278-fd012679ef1e)]
    runtimeclass HolographicViewProperties
    {
        static Windows.Internal.Holographic.UI.PresentationMode GetPresentationModeForCurrentWindow();
        static Windows.Internal.Holographic.UI.PresentationMode GetPresentationModeForCoreWindow(Windows.UI.Core.ICoreWindow coreWindow);
    }

}
