







namespace Windows.System.RemoteDesktop
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(standard)]
    [static_name("Windows.System.RemoteDesktop.IInteractiveSessionStatics", 60884631-dd3a-4576-9c8d-e8027618bdce)]
    [threading(both)]
    runtimeclass InteractiveSession
    {
        static Boolean IsRemote{ get; };
    }

}
