










namespace Windows.Graphics.Printing.Workflow
{
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    enum PrintWorkflowSessionStatus
    {
        Started,
        Completed,
        Aborted,
        Closed,
    };

    [contract(Windows.Foundation.UniversalApiContract, 5)]
    enum PrintWorkflowSubmittedStatus
    {
        Succeeded,
        Canceled,
        Failed,
    };


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowBackgroundSession", 5b7913ba-0c5e-528a-7458-86a46cbddc45)]
    runtimeclass PrintWorkflowBackgroundSession
    {
        event Windows.Foundation.TypedEventHandler <Windows.Graphics.Printing.Workflow.PrintWorkflowBackgroundSession, Windows.Graphics.Printing.Workflow.PrintWorkflowBackgroundSetupRequestedEventArgs>  SetupRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Graphics.Printing.Workflow.PrintWorkflowBackgroundSession, Windows.Graphics.Printing.Workflow.PrintWorkflowSubmittedEventArgs>  Submitted;
        Windows.Graphics.Printing.Workflow.PrintWorkflowSessionStatus Status{ get; };
        void Start();
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowBackgroundSetupRequestedEventArgs", 43e97342-1750-59c9-61fb-383748a20362)]
    runtimeclass PrintWorkflowBackgroundSetupRequestedEventArgs
    {
        Windows.Foundation.IAsyncOperation <Windows.Graphics.Printing.PrintTicket.WorkflowPrintTicket>  GetUserPrintTicketAsync();
        Windows.Graphics.Printing.Workflow.PrintWorkflowConfiguration Configuration{ get; };
        void SetRequiresUI();
        Windows.Foundation.Deferral GetDeferral();
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowSubmittedEventArgs", 3add0a41-3794-5569-5c87-40e8ff720f83)]
    runtimeclass PrintWorkflowSubmittedEventArgs
    {
        Windows.Graphics.Printing.Workflow.PrintWorkflowSubmittedOperation Operation{ get; };
        Windows.Graphics.Printing.Workflow.PrintWorkflowTarget GetTarget(Windows.Graphics.Printing.PrintTicket.WorkflowPrintTicket jobPrintTicket);
        Windows.Foundation.Deferral GetDeferral();
    }



    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowForegroundSession", c79b63d0-f8ec-4ceb-953a-c8876157dd33)]
    runtimeclass PrintWorkflowForegroundSession
    {
        event Windows.Foundation.TypedEventHandler <Windows.Graphics.Printing.Workflow.PrintWorkflowForegroundSession, Windows.Graphics.Printing.Workflow.PrintWorkflowForegroundSetupRequestedEventArgs>  SetupRequested;
        event Windows.Foundation.TypedEventHandler <Windows.Graphics.Printing.Workflow.PrintWorkflowForegroundSession, Windows.Graphics.Printing.Workflow.PrintWorkflowXpsDataAvailableEventArgs>  XpsDataAvailable;
        Windows.Graphics.Printing.Workflow.PrintWorkflowSessionStatus Status{ get; };
        void Start();
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowForegroundSetupRequestedEventArgs", bbe38247-9c1b-4dd3-9b2b-c80468d941b3)]
    runtimeclass PrintWorkflowForegroundSetupRequestedEventArgs
    {
        Windows.Foundation.IAsyncOperation <Windows.Graphics.Printing.PrintTicket.WorkflowPrintTicket>  GetUserPrintTicketAsync();
        Windows.Graphics.Printing.Workflow.PrintWorkflowConfiguration Configuration{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }

    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowXpsDataAvailableEventArgs", 4d11c331-54d1-434e-be0e-82c5fa58e5b2)]
    runtimeclass PrintWorkflowXpsDataAvailableEventArgs
    {
        Windows.Graphics.Printing.Workflow.PrintWorkflowSubmittedOperation Operation{ get; };
        Windows.Foundation.Deferral GetDeferral();
    }


    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowConfiguration", d0aac4ed-fd4b-5df5-4bb6-8d0d159ebe3f)]
    runtimeclass PrintWorkflowConfiguration
    {
        String SourceAppDisplayName{ get; };
        String JobTitle{ get; };
        String SessionId{ get; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowSourceContent", 1a28c641-ceb1-4533-bb73-fbe63eefdb18)]
    runtimeclass PrintWorkflowSourceContent
    {
        Windows.Foundation.IAsyncOperation <Windows.Graphics.Printing.PrintTicket.WorkflowPrintTicket>  GetJobPrintTicketAsync();
        Windows.Graphics.Printing.Workflow.PrintWorkflowSpoolStreamContent GetSourceSpoolDataAsStreamContent();
        Windows.Graphics.Printing.Workflow.PrintWorkflowObjectModelSourceFileContent GetSourceSpoolDataAsXpsObjectModel();
    }


    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowSubmittedOperation", 2e4e6216-3be1-5f0f-5c81-a5a2bd4eab0e)]
    runtimeclass PrintWorkflowSubmittedOperation
    {
        void Complete(PrintWorkflowSubmittedStatus status);
        Windows.Graphics.Printing.Workflow.PrintWorkflowConfiguration Configuration{ get; };
        Windows.Graphics.Printing.Workflow.PrintWorkflowSourceContent XpsContent{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowTarget", 29da276c-0a73-5aed-4f3d-970d3251f057)]
    runtimeclass PrintWorkflowTarget
    {
        Windows.Graphics.Printing.Workflow.PrintWorkflowStreamTarget TargetAsStream{ get; };
        Windows.Graphics.Printing.Workflow.PrintWorkflowObjectModelTargetPackage TargetAsXpsObjectModelPackage{ get; };
    }


    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowStreamTarget", b23bba84-8565-488b-9839-1c9e7c7aa916)]
    runtimeclass PrintWorkflowStreamTarget
    {
        Windows.Storage.Streams.IOutputStream GetOutputStream();
    }

    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [default_interface]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowObjectModelTargetPackage", 7d96bc74-9b54-4ca1-ad3a-979c3d44ddac)]
    runtimeclass PrintWorkflowObjectModelTargetPackage
    {
    }




    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowSpoolStreamContent", 72e55ece-e406-4b74-84e1-3ff3fdcdaf70)]
    runtimeclass PrintWorkflowSpoolStreamContent
    {
        Windows.Storage.Streams.IInputStream GetInputStream();
    }

    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [default_interface]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowObjectModelSourceFileContent", c36c8a6a-8a2a-419a-b3c3-2090e6bfab2f)]
    runtimeclass PrintWorkflowObjectModelSourceFileContent
    {
    }






    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowUIActivatedEventArgs", bc8a844d-09eb-5746-72a6-8dc8b5edbe9b)]
    runtimeclass PrintWorkflowUIActivatedEventArgs
        : Windows.ApplicationModel.Activation.IActivatedEventArgsWithUser
        , Windows.ApplicationModel.Activation.IActivatedEventArgs
    {
        Windows.Graphics.Printing.Workflow.PrintWorkflowForegroundSession PrintWorkflowSession{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 5)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.Graphics.Printing.Workflow.IPrintWorkflowTriggerDetails", 5739d868-9d86-4052-b0cb-f310becd59bb)]
    runtimeclass PrintWorkflowTriggerDetails
    {
        Windows.Graphics.Printing.Workflow.PrintWorkflowBackgroundSession PrintWorkflowSession{ get; };
    }

}
