







namespace Windows.System
{
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum UserAuthenticationStatus
    {
        Unauthenticated,
        LocallyAuthenticated,
        RemotelyAuthenticated,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum UserType
    {
        LocalUser,
        RemoteUser,
        LocalGuest,
        RemoteGuest,
        [contract(Windows.Foundation.UniversalApiContract, 6)]
        [feature(Velocity_AlwaysDisabledByDefault)]
        SystemManaged,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum UserPictureSize
    {
        Size64x64,
        Size208x208,
        Size424x424,
        Size1080x1080,
    };

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    enum UserWatcherStatus
    {
        Created,
        Started,
        EnumerationCompleted,
        Stopping,
        Stopped,
        Aborted,
    };


    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.System.IUserWatcher", 155eb23b-242a-45e0-a2e9-3171fc6a7fbb)]
    runtimeclass UserWatcher
    {
        Windows.System.UserWatcherStatus Status{ get; };
        void Start();
        void Stop();
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Windows.System.UserChangedEventArgs>  Added;
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Windows.System.UserChangedEventArgs>  Removed;
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Windows.System.UserChangedEventArgs>  Updated;
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Windows.System.UserChangedEventArgs>  AuthenticationStatusChanged;
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Windows.System.UserAuthenticationStatusChangingEventArgs>  AuthenticationStatusChanging;
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Object>  EnumerationCompleted;
        event Windows.Foundation.TypedEventHandler <Windows.System.UserWatcher, Object>  Stopped;
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [interface_name("Windows.System.IUserChangedEventArgs", 086459dc-18c6-48db-bc99-724fb9203ccc)]
    runtimeclass UserChangedEventArgs
    {
        Windows.System.User User{ get; };
    }

    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [marshaling_behavior(agile)]
    [dualapipartition(0xa000000)]
    [interface_name("Windows.System.IUserAuthenticationStatusChangingEventArgs", 8c030f28-a711-4c1e-ab48-04179c15938f)]
    runtimeclass UserAuthenticationStatusChangingEventArgs
    {
        Windows.System.UserAuthenticationStatusChangeDeferral GetDeferral();
        Windows.System.User User{ get; };
        Windows.System.UserAuthenticationStatus NewStatus{ get; };
        Windows.System.UserAuthenticationStatus CurrentStatus{ get; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [static_name("Windows.System.IUserStatics", 155eb23b-242a-45e0-a2e9-3171fc6a7fdd)]
    [interface_name("Windows.System.IUser", df9a26c6-e746-4bcd-b5d4-120103c4209b)]
    [threading(both)]
    runtimeclass User
    {
        static Windows.System.UserWatcher CreateWatcher();
        [default_overload]
        [method_name("FindAllAsync")] static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.System.User> >  FindAllAsync();
        [method_name("FindAllAsyncByType")] static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.System.User> >  FindAllAsync(UserType type);
        [method_name("FindAllAsyncByTypeAndStatus")] static Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.System.User> >  FindAllAsync(UserType type, UserAuthenticationStatus status);
        static Windows.System.User GetFromId(String nonRoamableId);

        [contract(Windows.Foundation.UniversalApiContract, 6)]
        [feature(Velocity_AlwaysDisabledByDefault)]
        [static_name("Windows.System.IUserStatics2", 74a37e11-2eb5-4487-b0d5-2c6790e013e9)]
        {
            static Windows.System.User GetDefault();
        }
        String NonRoamableId{ get; };
        Windows.System.UserAuthenticationStatus AuthenticationStatus{ get; };
        Windows.System.UserType Type{ get; };
        Windows.Foundation.IAsyncOperation <Object>  GetPropertyAsync(String value);
        Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IPropertySet>  GetPropertiesAsync(Windows.Foundation.Collections.IVectorView <String>  values);
        Windows.Foundation.IAsyncOperation <Windows.Storage.Streams.IRandomAccessStreamReference>  GetPictureAsync(UserPictureSize desiredSize);
    }




    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [interface_name("Windows.System.IUserAuthenticationStatusChangeDeferral", 88b59568-bb30-42fb-a270-e9902e40efa7)]
    runtimeclass UserAuthenticationStatusChangeDeferral
    {
        void Complete();
    }



    [dualapipartition(0xa000000)]
    [marshaling_behavior(agile)]
    [contract(Windows.Foundation.UniversalApiContract, 1)]
    [static_name("Windows.System.IKnownUserPropertiesStatics", 7755911a-70c5-48e5-b637-5ba3441e4ee4)]
    [threading(both)]
    runtimeclass KnownUserProperties
    {
        static String DisplayName{ get; };
        static String FirstName{ get; };
        static String LastName{ get; };
        static String ProviderName{ get; };
        static String AccountName{ get; };
        static String GuestHost{ get; };
        static String PrincipalName{ get; };
        static String DomainName{ get; };
        static String SessionInitiationProtocolUri{ get; };
    }



    [contract(Windows.Foundation.UniversalApiContract, 3)]
    [dualapipartition(0xa000002)]
    [marshaling_behavior(agile)]
    [static_name("Windows.System.IUserPickerStatics", de3290dc-7e73-4df6-a1ae-4d7eca82b40d)]
    [interface_name("Windows.System.IUserPicker", 7d548008-f1e3-4a6c-8ddc-a9bb0f488aed)]
    [threading(both)]
    runtimeclass UserPicker
    {
        UserPicker();
        static Boolean IsSupported();
        Boolean AllowGuestAccounts{ get; };
        Boolean AllowGuestAccounts{ set; };
        Windows.System.User SuggestedSelectedUser{ get; };
        Windows.System.User SuggestedSelectedUser{ set; };
        [remote_sync]Windows.Foundation.IAsyncOperation <Windows.System.User>  PickSingleUserAsync();
    }

}
