










namespace Windows.ApplicationModel.Internal
{
    [contractversion(1)]
    [internal]
    apicontract IAppDipslayInfoInternalContract{};

    [contract(Windows.ApplicationModel.Internal.IAppDipslayInfoInternalContract, 1)]
    [uuid(676532a9-b7d3-49b3-8fd2-8e9fdacb209f)]
    interface IAppDisplayInfoInternalStatics
    {
        Windows.ApplicationModel.AppDisplayInfo CreateFromApplicationId(Int64 applicationId);
        Windows.ApplicationModel.AppDisplayInfo CreateFromUserAndApplicationId(Windows.Internal.StateRepository.User user, Int64 applicationId);
        Windows.ApplicationModel.AppDisplayInfo Create(String displayName, String description, Windows.Storage.Streams.RandomAccessStreamReference logo);
    };

}
