





namespace Windows.Internal.ComposableShell.ComposerHints
{
    [contractversion(1)]
    [internal]
    apicontract InternalContract{};

    [contract(Windows.Internal.ComposableShell.ComposerHints.InternalContract, 1)]
    [uuid(47232b7f-a62f-46c0-98e1-d3fe52481265)]
    interface IComposerHintsProvider
    {
        Windows.Foundation.Collections.IObservableMap <String, Object>  Hints{ get; };
        Windows.Foundation.IAsyncOperation <Boolean>  UpdatePropertyAsync(String propertyName, Object value);
    };

    [contract(Windows.Internal.ComposableShell.ComposerHints.InternalContract, 1)]
    [uuid(e52df149-deaf-483b-95ce-0a41997643f6)]
    interface IComposerHintsProviderManager
    {
        [method_name("CreateProviderForPackageAsync")] [default_overload]
        Windows.Foundation.IAsyncOperation <Windows.Internal.ComposableShell.ComposerHints.IComposerHintsProvider>  CreateProviderAsync(String packageFamilyName, String id);
        [method_name("CreateProviderForIdAsync")] Windows.Foundation.IAsyncOperation <Windows.Internal.ComposableShell.ComposerHints.IComposerHintsProvider>  CreateProviderAsync(String id);
    };

}
