








namespace Windows.ApplicationModel.Resources.Management
{
    [contractversion(2)]
    apicontract ResourceIndexerContract{};

    [contract(Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 1)]
    enum IndexedResourceType
    {
        String,
        Path,
        EmbeddedData,
    };


    [marshaling_behavior(agile)]
    [webhosthidden]
    [contract(Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 1)]
    [interface_name("Windows.ApplicationModel.Resources.Management.IIndexedResourceCandidate", 0e619ef3-faec-4414-a9d7-54acd5953f29)]
    runtimeclass IndexedResourceCandidate
    {
        Windows.ApplicationModel.Resources.Management.IndexedResourceType Type{ get; };
        Windows.Foundation.Uri Uri{ get; };
        Windows.Foundation.Collections.IMapView <String, String>  Metadata{ get; };
        Windows.Foundation.Collections.IVectorView <Windows.ApplicationModel.Resources.Management.IndexedResourceQualifier>  Qualifiers{ get; };
        String ValueAsString{ get; };
        String GetQualifierValue(String qualifierName);
    }


    [webhosthidden]
    [deprecated("Use CreateResourceIndexer in mrmsupport.dll instead of ResourceIndexer.  For more info, see MSDN.", deprecate, Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 0x20000)]
    [contract(Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 1)]
    [marshaling_behavior(agile)]
    [constructor_name("Windows.ApplicationModel.Resources.Management.IResourceIndexerFactory", b8de3f09-31cd-4d97-bd30-8d39f742bc61)]
    [interface_name("Windows.ApplicationModel.Resources.Management.IResourceIndexer", 2d4cf9a5-e32f-4ab2-8748-96350a016da3)]
    [threading(both)]
    runtimeclass ResourceIndexer
    {
        [deprecated("Use CreateResourceIndexer in mrmsupport.dll instead of IResourceIndexerFactory.  For more info, see MSDN.", deprecate, Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 0x20000)]
        [method_name( "CreateResourceIndexer" )] ResourceIndexer(Windows.Foundation.Uri projectRoot);

        [contract(Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 1)]
        [constructor_name("Windows.ApplicationModel.Resources.Management.IResourceIndexerFactory2", 6040f18d-d5e5-4b60-9201-cd279cbcfed9)]
        {
            [deprecated("Use CreateResourceIndexer in mrmsupport.dll instead of IResourceIndexerFactory2.  For more info, see MSDN.", deprecate, Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 0x20000)]
            [method_name( "CreateResourceIndexerWithExtension" )] ResourceIndexer(Windows.Foundation.Uri projectRoot, Windows.Foundation.Uri extensionDllPath);
        }
        [deprecated("Use IndexFilePath in mrmsupport.dll instead of IResourceIndexer.  For more info, see MSDN.", deprecate, Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 0x20000)]
        Windows.ApplicationModel.Resources.Management.IndexedResourceCandidate IndexFilePath(Windows.Foundation.Uri filePath);
        [deprecated("Use IndexFilePath in mrmsupport.dll instead of IResourceIndexer.  For more info, see MSDN.", deprecate, Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 0x20000)]
        Windows.Foundation.IAsyncOperation <Windows.Foundation.Collections.IVectorView <Windows.ApplicationModel.Resources.Management.IndexedResourceCandidate> >  IndexFileContentsAsync(Windows.Foundation.Uri file);
    }




    [marshaling_behavior(agile)]
    [contract(Windows.ApplicationModel.Resources.Management.ResourceIndexerContract, 1)]
    [webhosthidden]
    [interface_name("Windows.ApplicationModel.Resources.Management.IIndexedResourceQualifier", dae3bb9b-d304-497f-a168-a340042c8adb)]
    runtimeclass IndexedResourceQualifier
    {
        String QualifierName{ get; };
        String QualifierValue{ get; };
    }

}
