









namespace Windows.UI.Internal.Input
{
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    enum DragHitTestConfiguration
    {
        Self,
        ChildDragAreas,
        Both,
    };



    [webhosthidden]
    [contract(Windows.UI.Internal.Input.ISMInternalContract, 1)]
    [marshaling_behavior(agile)]
    [static_name("Windows.UI.Internal.Input.IInputDragSourceStatics", 28afb0fa-5d24-52cd-bb2e-ad08604633b1)]
    [interface_name("Windows.UI.Internal.Input.IInputDragSource", 8ef276ad-3ffe-4705-a5a2-72e39d375b27)]
    [threading(both)]
    runtimeclass InputDragSource
        : Windows.UI.Internal.Input.InputObjectPartner
    {
        static Boolean IsSupported{ get; };
        static Windows.UI.Internal.Input.InputDragSource GetForInputSite(InputSite inputSite);
        UInt64 Id{ get; };
        UInt64 Id{ set; };
        Guid Type{ get; };
        Guid Type{ set; };
        Windows.UI.Internal.Input.DragHitTestConfiguration HitTestConfiguration{ get; };
        Windows.UI.Internal.Input.DragHitTestConfiguration HitTestConfiguration{ set; };
    }

}
