// WARNING: Please don't edit this file. It was generated by Python/WinRT

#pragma once

#include "pybase.h"

#if __has_include("py.Windows.Graphics.DirectX.h")
#include "py.Windows.Graphics.DirectX.h"
#endif

#include <winrt/Windows.Graphics.DirectX.Direct3D11.h>

namespace py
{
    template<>
    struct winrt_type<winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice>
    {
        static PyTypeObject* python_type;
    
        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };
    
    template<>
    struct winrt_type<winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DSurface>
    {
        static PyTypeObject* python_type;
    
        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };
    
    template<>
    struct winrt_type<winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DMultisampleDescription>
    {
        static PyTypeObject* python_type;
    
        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };
    
    template<>
    struct winrt_type<winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DSurfaceDescription>
    {
        static PyTypeObject* python_type;
    
        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };
    
    template<>
    struct converter<winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DMultisampleDescription>
    {
        static PyObject* convert(winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DMultisampleDescription instance) noexcept;
        static winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DMultisampleDescription convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DSurfaceDescription>
    {
        static PyObject* convert(winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DSurfaceDescription instance) noexcept;
        static winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DSurfaceDescription convert_to(PyObject* obj);
    };
    
}
