import "Windows.Foundation.idl";
import "test_component_base.idl";

namespace test_component_derived
{
    namespace Nested
    {
        unsealed runtimeclass Derived : test_component_base.Base
        {
            Derived();
            Derived(String name);

            void DerivedMethod();
        }

        unsealed runtimeclass MoreDerived : Derived
        {
            MoreDerived();
            MoreDerived(String name);

            void MoreDerivedMethod();
        }
    }
}
