parameters:
  - name: "BuildConfiguration"
    type: string
    default: "release"
  - name: "BuildPlatform"
    type: string
    default: "x86"
  - name: OfficialBuild
    type: boolean
    default: false

jobs:
- job: Build_ABI_Tool
  displayName: Build Binaries
  pool:
    type: windows

  variables:
    ob_outputDirectory: '$(Build.SourcesDirectory)\out'
    ob_artifactSuffix: ${{ parameters.BuildConfiguration }}_${{ parameters.BuildPlatform }}
    StagingFolder: $(ob_outputDirectory)
      
    ob_sdl_prefast_enabled: true
    ob_sdl_prefast_runDuring: 'Build'
    ob_sdl_checkCompliantCompilerWarnings: true

  steps:

  - task: NuGetToolInstaller@1
    displayName: Use NuGet 6.7
    continueOnError: True
    inputs:
      versionSpec: 6.7

  - task: VSBuild@1
    displayName: Build Tools
    inputs:
      solution: '$(Build.SourcesDirectory)\src\tool\abi\abi.sln'
      msbuildArgs: /p:XlangBuildVersion="$(Build.BuildNumber)"
      platform: ${{ parameters.BuildPlatform }}
      configuration: ${{ parameters.BuildConfiguration }}
      clean: true      

  - task: CopyFiles@2
    displayName: Stage abi.*
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\src\tool\abi\${{ parameters.BuildConfiguration }}
      Contents: >-
        abi.exe
        abi.pdb
      TargetFolder: $(ob_outputDirectory)\abi

  - task: onebranch.pipeline.signing@1
    displayName: '🔒 Onebranch Signing for abi.exe'
    condition: eq(${{ parameters.OfficialBuild }}, 'true')
    inputs:
      command: sign
      signing_profile: external_distribution
      files_to_sign: '**/*.dll;**/*.exe'
      search_root: $(ob_outputDirectory)\abi
